// Autogenerated from Pigeon (v25.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#undef _HAS_EXCEPTIONS

#include "messages.g.h"

#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace biometric_signature {
using flutter::BasicMessageChannel;
using flutter::CustomEncodableValue;
using flutter::EncodableList;
using flutter::EncodableMap;
using flutter::EncodableValue;

FlutterError CreateConnectionError(const std::string channel_name) {
  return FlutterError(
      "channel-error",
      "Unable to establish connection on channel: '" + channel_name + "'.",
      EncodableValue(""));
}

// BiometricAvailability

BiometricAvailability::BiometricAvailability() {}

BiometricAvailability::BiometricAvailability(
  const bool* can_authenticate,
  const bool* has_enrolled_biometrics,
  const EncodableList* available_biometrics,
  const std::string* reason)
 : can_authenticate_(can_authenticate ? std::optional<bool>(*can_authenticate) : std::nullopt),
    has_enrolled_biometrics_(has_enrolled_biometrics ? std::optional<bool>(*has_enrolled_biometrics) : std::nullopt),
    available_biometrics_(available_biometrics ? std::optional<EncodableList>(*available_biometrics) : std::nullopt),
    reason_(reason ? std::optional<std::string>(*reason) : std::nullopt) {}

const bool* BiometricAvailability::can_authenticate() const {
  return can_authenticate_ ? &(*can_authenticate_) : nullptr;
}

void BiometricAvailability::set_can_authenticate(const bool* value_arg) {
  can_authenticate_ = value_arg ? std::optional<bool>(*value_arg) : std::nullopt;
}

void BiometricAvailability::set_can_authenticate(bool value_arg) {
  can_authenticate_ = value_arg;
}


const bool* BiometricAvailability::has_enrolled_biometrics() const {
  return has_enrolled_biometrics_ ? &(*has_enrolled_biometrics_) : nullptr;
}

void BiometricAvailability::set_has_enrolled_biometrics(const bool* value_arg) {
  has_enrolled_biometrics_ = value_arg ? std::optional<bool>(*value_arg) : std::nullopt;
}

void BiometricAvailability::set_has_enrolled_biometrics(bool value_arg) {
  has_enrolled_biometrics_ = value_arg;
}


const EncodableList* BiometricAvailability::available_biometrics() const {
  return available_biometrics_ ? &(*available_biometrics_) : nullptr;
}

void BiometricAvailability::set_available_biometrics(const EncodableList* value_arg) {
  available_biometrics_ = value_arg ? std::optional<EncodableList>(*value_arg) : std::nullopt;
}

void BiometricAvailability::set_available_biometrics(const EncodableList& value_arg) {
  available_biometrics_ = value_arg;
}


const std::string* BiometricAvailability::reason() const {
  return reason_ ? &(*reason_) : nullptr;
}

void BiometricAvailability::set_reason(const std::string_view* value_arg) {
  reason_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void BiometricAvailability::set_reason(std::string_view value_arg) {
  reason_ = value_arg;
}


EncodableList BiometricAvailability::ToEncodableList() const {
  EncodableList list;
  list.reserve(4);
  list.push_back(can_authenticate_ ? EncodableValue(*can_authenticate_) : EncodableValue());
  list.push_back(has_enrolled_biometrics_ ? EncodableValue(*has_enrolled_biometrics_) : EncodableValue());
  list.push_back(available_biometrics_ ? EncodableValue(*available_biometrics_) : EncodableValue());
  list.push_back(reason_ ? EncodableValue(*reason_) : EncodableValue());
  return list;
}

BiometricAvailability BiometricAvailability::FromEncodableList(const EncodableList& list) {
  BiometricAvailability decoded;
  auto& encodable_can_authenticate = list[0];
  if (!encodable_can_authenticate.IsNull()) {
    decoded.set_can_authenticate(std::get<bool>(encodable_can_authenticate));
  }
  auto& encodable_has_enrolled_biometrics = list[1];
  if (!encodable_has_enrolled_biometrics.IsNull()) {
    decoded.set_has_enrolled_biometrics(std::get<bool>(encodable_has_enrolled_biometrics));
  }
  auto& encodable_available_biometrics = list[2];
  if (!encodable_available_biometrics.IsNull()) {
    decoded.set_available_biometrics(std::get<EncodableList>(encodable_available_biometrics));
  }
  auto& encodable_reason = list[3];
  if (!encodable_reason.IsNull()) {
    decoded.set_reason(std::get<std::string>(encodable_reason));
  }
  return decoded;
}

// KeyCreationResult

KeyCreationResult::KeyCreationResult() {}

KeyCreationResult::KeyCreationResult(
  const std::string* public_key,
  const std::vector<uint8_t>* public_key_bytes,
  const std::string* error,
  const BiometricError* code,
  const std::string* algorithm,
  const int64_t* key_size,
  const std::string* decrypting_public_key,
  const std::string* decrypting_algorithm,
  const int64_t* decrypting_key_size,
  const bool* is_hybrid_mode,
  const AuthenticationType* authentication_type)
 : public_key_(public_key ? std::optional<std::string>(*public_key) : std::nullopt),
    public_key_bytes_(public_key_bytes ? std::optional<std::vector<uint8_t>>(*public_key_bytes) : std::nullopt),
    error_(error ? std::optional<std::string>(*error) : std::nullopt),
    code_(code ? std::optional<BiometricError>(*code) : std::nullopt),
    algorithm_(algorithm ? std::optional<std::string>(*algorithm) : std::nullopt),
    key_size_(key_size ? std::optional<int64_t>(*key_size) : std::nullopt),
    decrypting_public_key_(decrypting_public_key ? std::optional<std::string>(*decrypting_public_key) : std::nullopt),
    decrypting_algorithm_(decrypting_algorithm ? std::optional<std::string>(*decrypting_algorithm) : std::nullopt),
    decrypting_key_size_(decrypting_key_size ? std::optional<int64_t>(*decrypting_key_size) : std::nullopt),
    is_hybrid_mode_(is_hybrid_mode ? std::optional<bool>(*is_hybrid_mode) : std::nullopt),
    authentication_type_(authentication_type ? std::optional<AuthenticationType>(*authentication_type) : std::nullopt) {}

const std::string* KeyCreationResult::public_key() const {
  return public_key_ ? &(*public_key_) : nullptr;
}

void KeyCreationResult::set_public_key(const std::string_view* value_arg) {
  public_key_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void KeyCreationResult::set_public_key(std::string_view value_arg) {
  public_key_ = value_arg;
}


const std::vector<uint8_t>* KeyCreationResult::public_key_bytes() const {
  return public_key_bytes_ ? &(*public_key_bytes_) : nullptr;
}

void KeyCreationResult::set_public_key_bytes(const std::vector<uint8_t>* value_arg) {
  public_key_bytes_ = value_arg ? std::optional<std::vector<uint8_t>>(*value_arg) : std::nullopt;
}

void KeyCreationResult::set_public_key_bytes(const std::vector<uint8_t>& value_arg) {
  public_key_bytes_ = value_arg;
}


const std::string* KeyCreationResult::error() const {
  return error_ ? &(*error_) : nullptr;
}

void KeyCreationResult::set_error(const std::string_view* value_arg) {
  error_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void KeyCreationResult::set_error(std::string_view value_arg) {
  error_ = value_arg;
}


const BiometricError* KeyCreationResult::code() const {
  return code_ ? &(*code_) : nullptr;
}

void KeyCreationResult::set_code(const BiometricError* value_arg) {
  code_ = value_arg ? std::optional<BiometricError>(*value_arg) : std::nullopt;
}

void KeyCreationResult::set_code(const BiometricError& value_arg) {
  code_ = value_arg;
}


const std::string* KeyCreationResult::algorithm() const {
  return algorithm_ ? &(*algorithm_) : nullptr;
}

void KeyCreationResult::set_algorithm(const std::string_view* value_arg) {
  algorithm_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void KeyCreationResult::set_algorithm(std::string_view value_arg) {
  algorithm_ = value_arg;
}


const int64_t* KeyCreationResult::key_size() const {
  return key_size_ ? &(*key_size_) : nullptr;
}

void KeyCreationResult::set_key_size(const int64_t* value_arg) {
  key_size_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void KeyCreationResult::set_key_size(int64_t value_arg) {
  key_size_ = value_arg;
}


const std::string* KeyCreationResult::decrypting_public_key() const {
  return decrypting_public_key_ ? &(*decrypting_public_key_) : nullptr;
}

void KeyCreationResult::set_decrypting_public_key(const std::string_view* value_arg) {
  decrypting_public_key_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void KeyCreationResult::set_decrypting_public_key(std::string_view value_arg) {
  decrypting_public_key_ = value_arg;
}


const std::string* KeyCreationResult::decrypting_algorithm() const {
  return decrypting_algorithm_ ? &(*decrypting_algorithm_) : nullptr;
}

void KeyCreationResult::set_decrypting_algorithm(const std::string_view* value_arg) {
  decrypting_algorithm_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void KeyCreationResult::set_decrypting_algorithm(std::string_view value_arg) {
  decrypting_algorithm_ = value_arg;
}


const int64_t* KeyCreationResult::decrypting_key_size() const {
  return decrypting_key_size_ ? &(*decrypting_key_size_) : nullptr;
}

void KeyCreationResult::set_decrypting_key_size(const int64_t* value_arg) {
  decrypting_key_size_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void KeyCreationResult::set_decrypting_key_size(int64_t value_arg) {
  decrypting_key_size_ = value_arg;
}


const bool* KeyCreationResult::is_hybrid_mode() const {
  return is_hybrid_mode_ ? &(*is_hybrid_mode_) : nullptr;
}

void KeyCreationResult::set_is_hybrid_mode(const bool* value_arg) {
  is_hybrid_mode_ = value_arg ? std::optional<bool>(*value_arg) : std::nullopt;
}

void KeyCreationResult::set_is_hybrid_mode(bool value_arg) {
  is_hybrid_mode_ = value_arg;
}


const AuthenticationType* KeyCreationResult::authentication_type() const {
  return authentication_type_ ? &(*authentication_type_) : nullptr;
}

void KeyCreationResult::set_authentication_type(const AuthenticationType* value_arg) {
  authentication_type_ = value_arg ? std::optional<AuthenticationType>(*value_arg) : std::nullopt;
}

void KeyCreationResult::set_authentication_type(const AuthenticationType& value_arg) {
  authentication_type_ = value_arg;
}


EncodableList KeyCreationResult::ToEncodableList() const {
  EncodableList list;
  list.reserve(11);
  list.push_back(public_key_ ? EncodableValue(*public_key_) : EncodableValue());
  list.push_back(public_key_bytes_ ? EncodableValue(*public_key_bytes_) : EncodableValue());
  list.push_back(error_ ? EncodableValue(*error_) : EncodableValue());
  list.push_back(code_ ? CustomEncodableValue(*code_) : EncodableValue());
  list.push_back(algorithm_ ? EncodableValue(*algorithm_) : EncodableValue());
  list.push_back(key_size_ ? EncodableValue(*key_size_) : EncodableValue());
  list.push_back(decrypting_public_key_ ? EncodableValue(*decrypting_public_key_) : EncodableValue());
  list.push_back(decrypting_algorithm_ ? EncodableValue(*decrypting_algorithm_) : EncodableValue());
  list.push_back(decrypting_key_size_ ? EncodableValue(*decrypting_key_size_) : EncodableValue());
  list.push_back(is_hybrid_mode_ ? EncodableValue(*is_hybrid_mode_) : EncodableValue());
  list.push_back(authentication_type_ ? CustomEncodableValue(*authentication_type_) : EncodableValue());
  return list;
}

KeyCreationResult KeyCreationResult::FromEncodableList(const EncodableList& list) {
  KeyCreationResult decoded;
  auto& encodable_public_key = list[0];
  if (!encodable_public_key.IsNull()) {
    decoded.set_public_key(std::get<std::string>(encodable_public_key));
  }
  auto& encodable_public_key_bytes = list[1];
  if (!encodable_public_key_bytes.IsNull()) {
    decoded.set_public_key_bytes(std::get<std::vector<uint8_t>>(encodable_public_key_bytes));
  }
  auto& encodable_error = list[2];
  if (!encodable_error.IsNull()) {
    decoded.set_error(std::get<std::string>(encodable_error));
  }
  auto& encodable_code = list[3];
  if (!encodable_code.IsNull()) {
    decoded.set_code(std::any_cast<const BiometricError&>(std::get<CustomEncodableValue>(encodable_code)));
  }
  auto& encodable_algorithm = list[4];
  if (!encodable_algorithm.IsNull()) {
    decoded.set_algorithm(std::get<std::string>(encodable_algorithm));
  }
  auto& encodable_key_size = list[5];
  if (!encodable_key_size.IsNull()) {
    decoded.set_key_size(std::get<int64_t>(encodable_key_size));
  }
  auto& encodable_decrypting_public_key = list[6];
  if (!encodable_decrypting_public_key.IsNull()) {
    decoded.set_decrypting_public_key(std::get<std::string>(encodable_decrypting_public_key));
  }
  auto& encodable_decrypting_algorithm = list[7];
  if (!encodable_decrypting_algorithm.IsNull()) {
    decoded.set_decrypting_algorithm(std::get<std::string>(encodable_decrypting_algorithm));
  }
  auto& encodable_decrypting_key_size = list[8];
  if (!encodable_decrypting_key_size.IsNull()) {
    decoded.set_decrypting_key_size(std::get<int64_t>(encodable_decrypting_key_size));
  }
  auto& encodable_is_hybrid_mode = list[9];
  if (!encodable_is_hybrid_mode.IsNull()) {
    decoded.set_is_hybrid_mode(std::get<bool>(encodable_is_hybrid_mode));
  }
  auto& encodable_authentication_type = list[10];
  if (!encodable_authentication_type.IsNull()) {
    decoded.set_authentication_type(std::any_cast<const AuthenticationType&>(std::get<CustomEncodableValue>(encodable_authentication_type)));
  }
  return decoded;
}

// SignatureResult

SignatureResult::SignatureResult() {}

SignatureResult::SignatureResult(
  const std::string* signature,
  const std::vector<uint8_t>* signature_bytes,
  const std::string* public_key,
  const std::string* error,
  const BiometricError* code,
  const std::string* algorithm,
  const int64_t* key_size,
  const AuthenticationType* authentication_type)
 : signature_(signature ? std::optional<std::string>(*signature) : std::nullopt),
    signature_bytes_(signature_bytes ? std::optional<std::vector<uint8_t>>(*signature_bytes) : std::nullopt),
    public_key_(public_key ? std::optional<std::string>(*public_key) : std::nullopt),
    error_(error ? std::optional<std::string>(*error) : std::nullopt),
    code_(code ? std::optional<BiometricError>(*code) : std::nullopt),
    algorithm_(algorithm ? std::optional<std::string>(*algorithm) : std::nullopt),
    key_size_(key_size ? std::optional<int64_t>(*key_size) : std::nullopt),
    authentication_type_(authentication_type ? std::optional<AuthenticationType>(*authentication_type) : std::nullopt) {}

const std::string* SignatureResult::signature() const {
  return signature_ ? &(*signature_) : nullptr;
}

void SignatureResult::set_signature(const std::string_view* value_arg) {
  signature_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void SignatureResult::set_signature(std::string_view value_arg) {
  signature_ = value_arg;
}


const std::vector<uint8_t>* SignatureResult::signature_bytes() const {
  return signature_bytes_ ? &(*signature_bytes_) : nullptr;
}

void SignatureResult::set_signature_bytes(const std::vector<uint8_t>* value_arg) {
  signature_bytes_ = value_arg ? std::optional<std::vector<uint8_t>>(*value_arg) : std::nullopt;
}

void SignatureResult::set_signature_bytes(const std::vector<uint8_t>& value_arg) {
  signature_bytes_ = value_arg;
}


const std::string* SignatureResult::public_key() const {
  return public_key_ ? &(*public_key_) : nullptr;
}

void SignatureResult::set_public_key(const std::string_view* value_arg) {
  public_key_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void SignatureResult::set_public_key(std::string_view value_arg) {
  public_key_ = value_arg;
}


const std::string* SignatureResult::error() const {
  return error_ ? &(*error_) : nullptr;
}

void SignatureResult::set_error(const std::string_view* value_arg) {
  error_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void SignatureResult::set_error(std::string_view value_arg) {
  error_ = value_arg;
}


const BiometricError* SignatureResult::code() const {
  return code_ ? &(*code_) : nullptr;
}

void SignatureResult::set_code(const BiometricError* value_arg) {
  code_ = value_arg ? std::optional<BiometricError>(*value_arg) : std::nullopt;
}

void SignatureResult::set_code(const BiometricError& value_arg) {
  code_ = value_arg;
}


const std::string* SignatureResult::algorithm() const {
  return algorithm_ ? &(*algorithm_) : nullptr;
}

void SignatureResult::set_algorithm(const std::string_view* value_arg) {
  algorithm_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void SignatureResult::set_algorithm(std::string_view value_arg) {
  algorithm_ = value_arg;
}


const int64_t* SignatureResult::key_size() const {
  return key_size_ ? &(*key_size_) : nullptr;
}

void SignatureResult::set_key_size(const int64_t* value_arg) {
  key_size_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void SignatureResult::set_key_size(int64_t value_arg) {
  key_size_ = value_arg;
}


const AuthenticationType* SignatureResult::authentication_type() const {
  return authentication_type_ ? &(*authentication_type_) : nullptr;
}

void SignatureResult::set_authentication_type(const AuthenticationType* value_arg) {
  authentication_type_ = value_arg ? std::optional<AuthenticationType>(*value_arg) : std::nullopt;
}

void SignatureResult::set_authentication_type(const AuthenticationType& value_arg) {
  authentication_type_ = value_arg;
}


EncodableList SignatureResult::ToEncodableList() const {
  EncodableList list;
  list.reserve(8);
  list.push_back(signature_ ? EncodableValue(*signature_) : EncodableValue());
  list.push_back(signature_bytes_ ? EncodableValue(*signature_bytes_) : EncodableValue());
  list.push_back(public_key_ ? EncodableValue(*public_key_) : EncodableValue());
  list.push_back(error_ ? EncodableValue(*error_) : EncodableValue());
  list.push_back(code_ ? CustomEncodableValue(*code_) : EncodableValue());
  list.push_back(algorithm_ ? EncodableValue(*algorithm_) : EncodableValue());
  list.push_back(key_size_ ? EncodableValue(*key_size_) : EncodableValue());
  list.push_back(authentication_type_ ? CustomEncodableValue(*authentication_type_) : EncodableValue());
  return list;
}

SignatureResult SignatureResult::FromEncodableList(const EncodableList& list) {
  SignatureResult decoded;
  auto& encodable_signature = list[0];
  if (!encodable_signature.IsNull()) {
    decoded.set_signature(std::get<std::string>(encodable_signature));
  }
  auto& encodable_signature_bytes = list[1];
  if (!encodable_signature_bytes.IsNull()) {
    decoded.set_signature_bytes(std::get<std::vector<uint8_t>>(encodable_signature_bytes));
  }
  auto& encodable_public_key = list[2];
  if (!encodable_public_key.IsNull()) {
    decoded.set_public_key(std::get<std::string>(encodable_public_key));
  }
  auto& encodable_error = list[3];
  if (!encodable_error.IsNull()) {
    decoded.set_error(std::get<std::string>(encodable_error));
  }
  auto& encodable_code = list[4];
  if (!encodable_code.IsNull()) {
    decoded.set_code(std::any_cast<const BiometricError&>(std::get<CustomEncodableValue>(encodable_code)));
  }
  auto& encodable_algorithm = list[5];
  if (!encodable_algorithm.IsNull()) {
    decoded.set_algorithm(std::get<std::string>(encodable_algorithm));
  }
  auto& encodable_key_size = list[6];
  if (!encodable_key_size.IsNull()) {
    decoded.set_key_size(std::get<int64_t>(encodable_key_size));
  }
  auto& encodable_authentication_type = list[7];
  if (!encodable_authentication_type.IsNull()) {
    decoded.set_authentication_type(std::any_cast<const AuthenticationType&>(std::get<CustomEncodableValue>(encodable_authentication_type)));
  }
  return decoded;
}

// DecryptResult

DecryptResult::DecryptResult() {}

DecryptResult::DecryptResult(
  const std::string* decrypted_data,
  const std::string* error,
  const BiometricError* code,
  const AuthenticationType* authentication_type)
 : decrypted_data_(decrypted_data ? std::optional<std::string>(*decrypted_data) : std::nullopt),
    error_(error ? std::optional<std::string>(*error) : std::nullopt),
    code_(code ? std::optional<BiometricError>(*code) : std::nullopt),
    authentication_type_(authentication_type ? std::optional<AuthenticationType>(*authentication_type) : std::nullopt) {}

const std::string* DecryptResult::decrypted_data() const {
  return decrypted_data_ ? &(*decrypted_data_) : nullptr;
}

void DecryptResult::set_decrypted_data(const std::string_view* value_arg) {
  decrypted_data_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void DecryptResult::set_decrypted_data(std::string_view value_arg) {
  decrypted_data_ = value_arg;
}


const std::string* DecryptResult::error() const {
  return error_ ? &(*error_) : nullptr;
}

void DecryptResult::set_error(const std::string_view* value_arg) {
  error_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void DecryptResult::set_error(std::string_view value_arg) {
  error_ = value_arg;
}


const BiometricError* DecryptResult::code() const {
  return code_ ? &(*code_) : nullptr;
}

void DecryptResult::set_code(const BiometricError* value_arg) {
  code_ = value_arg ? std::optional<BiometricError>(*value_arg) : std::nullopt;
}

void DecryptResult::set_code(const BiometricError& value_arg) {
  code_ = value_arg;
}


const AuthenticationType* DecryptResult::authentication_type() const {
  return authentication_type_ ? &(*authentication_type_) : nullptr;
}

void DecryptResult::set_authentication_type(const AuthenticationType* value_arg) {
  authentication_type_ = value_arg ? std::optional<AuthenticationType>(*value_arg) : std::nullopt;
}

void DecryptResult::set_authentication_type(const AuthenticationType& value_arg) {
  authentication_type_ = value_arg;
}


EncodableList DecryptResult::ToEncodableList() const {
  EncodableList list;
  list.reserve(4);
  list.push_back(decrypted_data_ ? EncodableValue(*decrypted_data_) : EncodableValue());
  list.push_back(error_ ? EncodableValue(*error_) : EncodableValue());
  list.push_back(code_ ? CustomEncodableValue(*code_) : EncodableValue());
  list.push_back(authentication_type_ ? CustomEncodableValue(*authentication_type_) : EncodableValue());
  return list;
}

DecryptResult DecryptResult::FromEncodableList(const EncodableList& list) {
  DecryptResult decoded;
  auto& encodable_decrypted_data = list[0];
  if (!encodable_decrypted_data.IsNull()) {
    decoded.set_decrypted_data(std::get<std::string>(encodable_decrypted_data));
  }
  auto& encodable_error = list[1];
  if (!encodable_error.IsNull()) {
    decoded.set_error(std::get<std::string>(encodable_error));
  }
  auto& encodable_code = list[2];
  if (!encodable_code.IsNull()) {
    decoded.set_code(std::any_cast<const BiometricError&>(std::get<CustomEncodableValue>(encodable_code)));
  }
  auto& encodable_authentication_type = list[3];
  if (!encodable_authentication_type.IsNull()) {
    decoded.set_authentication_type(std::any_cast<const AuthenticationType&>(std::get<CustomEncodableValue>(encodable_authentication_type)));
  }
  return decoded;
}

// KeyInfo

KeyInfo::KeyInfo() {}

KeyInfo::KeyInfo(
  const bool* exists,
  const bool* is_valid,
  const std::string* algorithm,
  const int64_t* key_size,
  const bool* is_hybrid_mode,
  const std::string* public_key,
  const std::string* decrypting_public_key,
  const std::string* decrypting_algorithm,
  const int64_t* decrypting_key_size)
 : exists_(exists ? std::optional<bool>(*exists) : std::nullopt),
    is_valid_(is_valid ? std::optional<bool>(*is_valid) : std::nullopt),
    algorithm_(algorithm ? std::optional<std::string>(*algorithm) : std::nullopt),
    key_size_(key_size ? std::optional<int64_t>(*key_size) : std::nullopt),
    is_hybrid_mode_(is_hybrid_mode ? std::optional<bool>(*is_hybrid_mode) : std::nullopt),
    public_key_(public_key ? std::optional<std::string>(*public_key) : std::nullopt),
    decrypting_public_key_(decrypting_public_key ? std::optional<std::string>(*decrypting_public_key) : std::nullopt),
    decrypting_algorithm_(decrypting_algorithm ? std::optional<std::string>(*decrypting_algorithm) : std::nullopt),
    decrypting_key_size_(decrypting_key_size ? std::optional<int64_t>(*decrypting_key_size) : std::nullopt) {}

const bool* KeyInfo::exists() const {
  return exists_ ? &(*exists_) : nullptr;
}

void KeyInfo::set_exists(const bool* value_arg) {
  exists_ = value_arg ? std::optional<bool>(*value_arg) : std::nullopt;
}

void KeyInfo::set_exists(bool value_arg) {
  exists_ = value_arg;
}


const bool* KeyInfo::is_valid() const {
  return is_valid_ ? &(*is_valid_) : nullptr;
}

void KeyInfo::set_is_valid(const bool* value_arg) {
  is_valid_ = value_arg ? std::optional<bool>(*value_arg) : std::nullopt;
}

void KeyInfo::set_is_valid(bool value_arg) {
  is_valid_ = value_arg;
}


const std::string* KeyInfo::algorithm() const {
  return algorithm_ ? &(*algorithm_) : nullptr;
}

void KeyInfo::set_algorithm(const std::string_view* value_arg) {
  algorithm_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void KeyInfo::set_algorithm(std::string_view value_arg) {
  algorithm_ = value_arg;
}


const int64_t* KeyInfo::key_size() const {
  return key_size_ ? &(*key_size_) : nullptr;
}

void KeyInfo::set_key_size(const int64_t* value_arg) {
  key_size_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void KeyInfo::set_key_size(int64_t value_arg) {
  key_size_ = value_arg;
}


const bool* KeyInfo::is_hybrid_mode() const {
  return is_hybrid_mode_ ? &(*is_hybrid_mode_) : nullptr;
}

void KeyInfo::set_is_hybrid_mode(const bool* value_arg) {
  is_hybrid_mode_ = value_arg ? std::optional<bool>(*value_arg) : std::nullopt;
}

void KeyInfo::set_is_hybrid_mode(bool value_arg) {
  is_hybrid_mode_ = value_arg;
}


const std::string* KeyInfo::public_key() const {
  return public_key_ ? &(*public_key_) : nullptr;
}

void KeyInfo::set_public_key(const std::string_view* value_arg) {
  public_key_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void KeyInfo::set_public_key(std::string_view value_arg) {
  public_key_ = value_arg;
}


const std::string* KeyInfo::decrypting_public_key() const {
  return decrypting_public_key_ ? &(*decrypting_public_key_) : nullptr;
}

void KeyInfo::set_decrypting_public_key(const std::string_view* value_arg) {
  decrypting_public_key_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void KeyInfo::set_decrypting_public_key(std::string_view value_arg) {
  decrypting_public_key_ = value_arg;
}


const std::string* KeyInfo::decrypting_algorithm() const {
  return decrypting_algorithm_ ? &(*decrypting_algorithm_) : nullptr;
}

void KeyInfo::set_decrypting_algorithm(const std::string_view* value_arg) {
  decrypting_algorithm_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void KeyInfo::set_decrypting_algorithm(std::string_view value_arg) {
  decrypting_algorithm_ = value_arg;
}


const int64_t* KeyInfo::decrypting_key_size() const {
  return decrypting_key_size_ ? &(*decrypting_key_size_) : nullptr;
}

void KeyInfo::set_decrypting_key_size(const int64_t* value_arg) {
  decrypting_key_size_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void KeyInfo::set_decrypting_key_size(int64_t value_arg) {
  decrypting_key_size_ = value_arg;
}


EncodableList KeyInfo::ToEncodableList() const {
  EncodableList list;
  list.reserve(9);
  list.push_back(exists_ ? EncodableValue(*exists_) : EncodableValue());
  list.push_back(is_valid_ ? EncodableValue(*is_valid_) : EncodableValue());
  list.push_back(algorithm_ ? EncodableValue(*algorithm_) : EncodableValue());
  list.push_back(key_size_ ? EncodableValue(*key_size_) : EncodableValue());
  list.push_back(is_hybrid_mode_ ? EncodableValue(*is_hybrid_mode_) : EncodableValue());
  list.push_back(public_key_ ? EncodableValue(*public_key_) : EncodableValue());
  list.push_back(decrypting_public_key_ ? EncodableValue(*decrypting_public_key_) : EncodableValue());
  list.push_back(decrypting_algorithm_ ? EncodableValue(*decrypting_algorithm_) : EncodableValue());
  list.push_back(decrypting_key_size_ ? EncodableValue(*decrypting_key_size_) : EncodableValue());
  return list;
}

KeyInfo KeyInfo::FromEncodableList(const EncodableList& list) {
  KeyInfo decoded;
  auto& encodable_exists = list[0];
  if (!encodable_exists.IsNull()) {
    decoded.set_exists(std::get<bool>(encodable_exists));
  }
  auto& encodable_is_valid = list[1];
  if (!encodable_is_valid.IsNull()) {
    decoded.set_is_valid(std::get<bool>(encodable_is_valid));
  }
  auto& encodable_algorithm = list[2];
  if (!encodable_algorithm.IsNull()) {
    decoded.set_algorithm(std::get<std::string>(encodable_algorithm));
  }
  auto& encodable_key_size = list[3];
  if (!encodable_key_size.IsNull()) {
    decoded.set_key_size(std::get<int64_t>(encodable_key_size));
  }
  auto& encodable_is_hybrid_mode = list[4];
  if (!encodable_is_hybrid_mode.IsNull()) {
    decoded.set_is_hybrid_mode(std::get<bool>(encodable_is_hybrid_mode));
  }
  auto& encodable_public_key = list[5];
  if (!encodable_public_key.IsNull()) {
    decoded.set_public_key(std::get<std::string>(encodable_public_key));
  }
  auto& encodable_decrypting_public_key = list[6];
  if (!encodable_decrypting_public_key.IsNull()) {
    decoded.set_decrypting_public_key(std::get<std::string>(encodable_decrypting_public_key));
  }
  auto& encodable_decrypting_algorithm = list[7];
  if (!encodable_decrypting_algorithm.IsNull()) {
    decoded.set_decrypting_algorithm(std::get<std::string>(encodable_decrypting_algorithm));
  }
  auto& encodable_decrypting_key_size = list[8];
  if (!encodable_decrypting_key_size.IsNull()) {
    decoded.set_decrypting_key_size(std::get<int64_t>(encodable_decrypting_key_size));
  }
  return decoded;
}

// CreateKeysConfig

CreateKeysConfig::CreateKeysConfig() {}

CreateKeysConfig::CreateKeysConfig(
  const SignatureType* signature_type,
  const bool* enforce_biometric,
  const bool* set_invalidated_by_biometric_enrollment,
  const bool* use_device_credentials,
  const bool* enable_decryption,
  const std::string* prompt_subtitle,
  const std::string* prompt_description,
  const std::string* cancel_button_text,
  const bool* fail_if_exists)
 : signature_type_(signature_type ? std::optional<SignatureType>(*signature_type) : std::nullopt),
    enforce_biometric_(enforce_biometric ? std::optional<bool>(*enforce_biometric) : std::nullopt),
    set_invalidated_by_biometric_enrollment_(set_invalidated_by_biometric_enrollment ? std::optional<bool>(*set_invalidated_by_biometric_enrollment) : std::nullopt),
    use_device_credentials_(use_device_credentials ? std::optional<bool>(*use_device_credentials) : std::nullopt),
    enable_decryption_(enable_decryption ? std::optional<bool>(*enable_decryption) : std::nullopt),
    prompt_subtitle_(prompt_subtitle ? std::optional<std::string>(*prompt_subtitle) : std::nullopt),
    prompt_description_(prompt_description ? std::optional<std::string>(*prompt_description) : std::nullopt),
    cancel_button_text_(cancel_button_text ? std::optional<std::string>(*cancel_button_text) : std::nullopt),
    fail_if_exists_(fail_if_exists ? std::optional<bool>(*fail_if_exists) : std::nullopt) {}

const SignatureType* CreateKeysConfig::signature_type() const {
  return signature_type_ ? &(*signature_type_) : nullptr;
}

void CreateKeysConfig::set_signature_type(const SignatureType* value_arg) {
  signature_type_ = value_arg ? std::optional<SignatureType>(*value_arg) : std::nullopt;
}

void CreateKeysConfig::set_signature_type(const SignatureType& value_arg) {
  signature_type_ = value_arg;
}


const bool* CreateKeysConfig::enforce_biometric() const {
  return enforce_biometric_ ? &(*enforce_biometric_) : nullptr;
}

void CreateKeysConfig::set_enforce_biometric(const bool* value_arg) {
  enforce_biometric_ = value_arg ? std::optional<bool>(*value_arg) : std::nullopt;
}

void CreateKeysConfig::set_enforce_biometric(bool value_arg) {
  enforce_biometric_ = value_arg;
}


const bool* CreateKeysConfig::set_invalidated_by_biometric_enrollment() const {
  return set_invalidated_by_biometric_enrollment_ ? &(*set_invalidated_by_biometric_enrollment_) : nullptr;
}

void CreateKeysConfig::set_set_invalidated_by_biometric_enrollment(const bool* value_arg) {
  set_invalidated_by_biometric_enrollment_ = value_arg ? std::optional<bool>(*value_arg) : std::nullopt;
}

void CreateKeysConfig::set_set_invalidated_by_biometric_enrollment(bool value_arg) {
  set_invalidated_by_biometric_enrollment_ = value_arg;
}


const bool* CreateKeysConfig::use_device_credentials() const {
  return use_device_credentials_ ? &(*use_device_credentials_) : nullptr;
}

void CreateKeysConfig::set_use_device_credentials(const bool* value_arg) {
  use_device_credentials_ = value_arg ? std::optional<bool>(*value_arg) : std::nullopt;
}

void CreateKeysConfig::set_use_device_credentials(bool value_arg) {
  use_device_credentials_ = value_arg;
}


const bool* CreateKeysConfig::enable_decryption() const {
  return enable_decryption_ ? &(*enable_decryption_) : nullptr;
}

void CreateKeysConfig::set_enable_decryption(const bool* value_arg) {
  enable_decryption_ = value_arg ? std::optional<bool>(*value_arg) : std::nullopt;
}

void CreateKeysConfig::set_enable_decryption(bool value_arg) {
  enable_decryption_ = value_arg;
}


const std::string* CreateKeysConfig::prompt_subtitle() const {
  return prompt_subtitle_ ? &(*prompt_subtitle_) : nullptr;
}

void CreateKeysConfig::set_prompt_subtitle(const std::string_view* value_arg) {
  prompt_subtitle_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void CreateKeysConfig::set_prompt_subtitle(std::string_view value_arg) {
  prompt_subtitle_ = value_arg;
}


const std::string* CreateKeysConfig::prompt_description() const {
  return prompt_description_ ? &(*prompt_description_) : nullptr;
}

void CreateKeysConfig::set_prompt_description(const std::string_view* value_arg) {
  prompt_description_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void CreateKeysConfig::set_prompt_description(std::string_view value_arg) {
  prompt_description_ = value_arg;
}


const std::string* CreateKeysConfig::cancel_button_text() const {
  return cancel_button_text_ ? &(*cancel_button_text_) : nullptr;
}

void CreateKeysConfig::set_cancel_button_text(const std::string_view* value_arg) {
  cancel_button_text_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void CreateKeysConfig::set_cancel_button_text(std::string_view value_arg) {
  cancel_button_text_ = value_arg;
}


const bool* CreateKeysConfig::fail_if_exists() const {
  return fail_if_exists_ ? &(*fail_if_exists_) : nullptr;
}

void CreateKeysConfig::set_fail_if_exists(const bool* value_arg) {
  fail_if_exists_ = value_arg ? std::optional<bool>(*value_arg) : std::nullopt;
}

void CreateKeysConfig::set_fail_if_exists(bool value_arg) {
  fail_if_exists_ = value_arg;
}


EncodableList CreateKeysConfig::ToEncodableList() const {
  EncodableList list;
  list.reserve(9);
  list.push_back(signature_type_ ? CustomEncodableValue(*signature_type_) : EncodableValue());
  list.push_back(enforce_biometric_ ? EncodableValue(*enforce_biometric_) : EncodableValue());
  list.push_back(set_invalidated_by_biometric_enrollment_ ? EncodableValue(*set_invalidated_by_biometric_enrollment_) : EncodableValue());
  list.push_back(use_device_credentials_ ? EncodableValue(*use_device_credentials_) : EncodableValue());
  list.push_back(enable_decryption_ ? EncodableValue(*enable_decryption_) : EncodableValue());
  list.push_back(prompt_subtitle_ ? EncodableValue(*prompt_subtitle_) : EncodableValue());
  list.push_back(prompt_description_ ? EncodableValue(*prompt_description_) : EncodableValue());
  list.push_back(cancel_button_text_ ? EncodableValue(*cancel_button_text_) : EncodableValue());
  list.push_back(fail_if_exists_ ? EncodableValue(*fail_if_exists_) : EncodableValue());
  return list;
}

CreateKeysConfig CreateKeysConfig::FromEncodableList(const EncodableList& list) {
  CreateKeysConfig decoded;
  auto& encodable_signature_type = list[0];
  if (!encodable_signature_type.IsNull()) {
    decoded.set_signature_type(std::any_cast<const SignatureType&>(std::get<CustomEncodableValue>(encodable_signature_type)));
  }
  auto& encodable_enforce_biometric = list[1];
  if (!encodable_enforce_biometric.IsNull()) {
    decoded.set_enforce_biometric(std::get<bool>(encodable_enforce_biometric));
  }
  auto& encodable_set_invalidated_by_biometric_enrollment = list[2];
  if (!encodable_set_invalidated_by_biometric_enrollment.IsNull()) {
    decoded.set_set_invalidated_by_biometric_enrollment(std::get<bool>(encodable_set_invalidated_by_biometric_enrollment));
  }
  auto& encodable_use_device_credentials = list[3];
  if (!encodable_use_device_credentials.IsNull()) {
    decoded.set_use_device_credentials(std::get<bool>(encodable_use_device_credentials));
  }
  auto& encodable_enable_decryption = list[4];
  if (!encodable_enable_decryption.IsNull()) {
    decoded.set_enable_decryption(std::get<bool>(encodable_enable_decryption));
  }
  auto& encodable_prompt_subtitle = list[5];
  if (!encodable_prompt_subtitle.IsNull()) {
    decoded.set_prompt_subtitle(std::get<std::string>(encodable_prompt_subtitle));
  }
  auto& encodable_prompt_description = list[6];
  if (!encodable_prompt_description.IsNull()) {
    decoded.set_prompt_description(std::get<std::string>(encodable_prompt_description));
  }
  auto& encodable_cancel_button_text = list[7];
  if (!encodable_cancel_button_text.IsNull()) {
    decoded.set_cancel_button_text(std::get<std::string>(encodable_cancel_button_text));
  }
  auto& encodable_fail_if_exists = list[8];
  if (!encodable_fail_if_exists.IsNull()) {
    decoded.set_fail_if_exists(std::get<bool>(encodable_fail_if_exists));
  }
  return decoded;
}

// CreateSignatureConfig

CreateSignatureConfig::CreateSignatureConfig() {}

CreateSignatureConfig::CreateSignatureConfig(
  const std::string* prompt_subtitle,
  const std::string* prompt_description,
  const std::string* cancel_button_text,
  const bool* allow_device_credentials,
  const bool* should_migrate)
 : prompt_subtitle_(prompt_subtitle ? std::optional<std::string>(*prompt_subtitle) : std::nullopt),
    prompt_description_(prompt_description ? std::optional<std::string>(*prompt_description) : std::nullopt),
    cancel_button_text_(cancel_button_text ? std::optional<std::string>(*cancel_button_text) : std::nullopt),
    allow_device_credentials_(allow_device_credentials ? std::optional<bool>(*allow_device_credentials) : std::nullopt),
    should_migrate_(should_migrate ? std::optional<bool>(*should_migrate) : std::nullopt) {}

const std::string* CreateSignatureConfig::prompt_subtitle() const {
  return prompt_subtitle_ ? &(*prompt_subtitle_) : nullptr;
}

void CreateSignatureConfig::set_prompt_subtitle(const std::string_view* value_arg) {
  prompt_subtitle_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void CreateSignatureConfig::set_prompt_subtitle(std::string_view value_arg) {
  prompt_subtitle_ = value_arg;
}


const std::string* CreateSignatureConfig::prompt_description() const {
  return prompt_description_ ? &(*prompt_description_) : nullptr;
}

void CreateSignatureConfig::set_prompt_description(const std::string_view* value_arg) {
  prompt_description_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void CreateSignatureConfig::set_prompt_description(std::string_view value_arg) {
  prompt_description_ = value_arg;
}


const std::string* CreateSignatureConfig::cancel_button_text() const {
  return cancel_button_text_ ? &(*cancel_button_text_) : nullptr;
}

void CreateSignatureConfig::set_cancel_button_text(const std::string_view* value_arg) {
  cancel_button_text_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void CreateSignatureConfig::set_cancel_button_text(std::string_view value_arg) {
  cancel_button_text_ = value_arg;
}


const bool* CreateSignatureConfig::allow_device_credentials() const {
  return allow_device_credentials_ ? &(*allow_device_credentials_) : nullptr;
}

void CreateSignatureConfig::set_allow_device_credentials(const bool* value_arg) {
  allow_device_credentials_ = value_arg ? std::optional<bool>(*value_arg) : std::nullopt;
}

void CreateSignatureConfig::set_allow_device_credentials(bool value_arg) {
  allow_device_credentials_ = value_arg;
}


const bool* CreateSignatureConfig::should_migrate() const {
  return should_migrate_ ? &(*should_migrate_) : nullptr;
}

void CreateSignatureConfig::set_should_migrate(const bool* value_arg) {
  should_migrate_ = value_arg ? std::optional<bool>(*value_arg) : std::nullopt;
}

void CreateSignatureConfig::set_should_migrate(bool value_arg) {
  should_migrate_ = value_arg;
}


EncodableList CreateSignatureConfig::ToEncodableList() const {
  EncodableList list;
  list.reserve(5);
  list.push_back(prompt_subtitle_ ? EncodableValue(*prompt_subtitle_) : EncodableValue());
  list.push_back(prompt_description_ ? EncodableValue(*prompt_description_) : EncodableValue());
  list.push_back(cancel_button_text_ ? EncodableValue(*cancel_button_text_) : EncodableValue());
  list.push_back(allow_device_credentials_ ? EncodableValue(*allow_device_credentials_) : EncodableValue());
  list.push_back(should_migrate_ ? EncodableValue(*should_migrate_) : EncodableValue());
  return list;
}

CreateSignatureConfig CreateSignatureConfig::FromEncodableList(const EncodableList& list) {
  CreateSignatureConfig decoded;
  auto& encodable_prompt_subtitle = list[0];
  if (!encodable_prompt_subtitle.IsNull()) {
    decoded.set_prompt_subtitle(std::get<std::string>(encodable_prompt_subtitle));
  }
  auto& encodable_prompt_description = list[1];
  if (!encodable_prompt_description.IsNull()) {
    decoded.set_prompt_description(std::get<std::string>(encodable_prompt_description));
  }
  auto& encodable_cancel_button_text = list[2];
  if (!encodable_cancel_button_text.IsNull()) {
    decoded.set_cancel_button_text(std::get<std::string>(encodable_cancel_button_text));
  }
  auto& encodable_allow_device_credentials = list[3];
  if (!encodable_allow_device_credentials.IsNull()) {
    decoded.set_allow_device_credentials(std::get<bool>(encodable_allow_device_credentials));
  }
  auto& encodable_should_migrate = list[4];
  if (!encodable_should_migrate.IsNull()) {
    decoded.set_should_migrate(std::get<bool>(encodable_should_migrate));
  }
  return decoded;
}

// DecryptConfig

DecryptConfig::DecryptConfig() {}

DecryptConfig::DecryptConfig(
  const std::string* prompt_subtitle,
  const std::string* prompt_description,
  const std::string* cancel_button_text,
  const bool* allow_device_credentials,
  const bool* should_migrate)
 : prompt_subtitle_(prompt_subtitle ? std::optional<std::string>(*prompt_subtitle) : std::nullopt),
    prompt_description_(prompt_description ? std::optional<std::string>(*prompt_description) : std::nullopt),
    cancel_button_text_(cancel_button_text ? std::optional<std::string>(*cancel_button_text) : std::nullopt),
    allow_device_credentials_(allow_device_credentials ? std::optional<bool>(*allow_device_credentials) : std::nullopt),
    should_migrate_(should_migrate ? std::optional<bool>(*should_migrate) : std::nullopt) {}

const std::string* DecryptConfig::prompt_subtitle() const {
  return prompt_subtitle_ ? &(*prompt_subtitle_) : nullptr;
}

void DecryptConfig::set_prompt_subtitle(const std::string_view* value_arg) {
  prompt_subtitle_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void DecryptConfig::set_prompt_subtitle(std::string_view value_arg) {
  prompt_subtitle_ = value_arg;
}


const std::string* DecryptConfig::prompt_description() const {
  return prompt_description_ ? &(*prompt_description_) : nullptr;
}

void DecryptConfig::set_prompt_description(const std::string_view* value_arg) {
  prompt_description_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void DecryptConfig::set_prompt_description(std::string_view value_arg) {
  prompt_description_ = value_arg;
}


const std::string* DecryptConfig::cancel_button_text() const {
  return cancel_button_text_ ? &(*cancel_button_text_) : nullptr;
}

void DecryptConfig::set_cancel_button_text(const std::string_view* value_arg) {
  cancel_button_text_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void DecryptConfig::set_cancel_button_text(std::string_view value_arg) {
  cancel_button_text_ = value_arg;
}


const bool* DecryptConfig::allow_device_credentials() const {
  return allow_device_credentials_ ? &(*allow_device_credentials_) : nullptr;
}

void DecryptConfig::set_allow_device_credentials(const bool* value_arg) {
  allow_device_credentials_ = value_arg ? std::optional<bool>(*value_arg) : std::nullopt;
}

void DecryptConfig::set_allow_device_credentials(bool value_arg) {
  allow_device_credentials_ = value_arg;
}


const bool* DecryptConfig::should_migrate() const {
  return should_migrate_ ? &(*should_migrate_) : nullptr;
}

void DecryptConfig::set_should_migrate(const bool* value_arg) {
  should_migrate_ = value_arg ? std::optional<bool>(*value_arg) : std::nullopt;
}

void DecryptConfig::set_should_migrate(bool value_arg) {
  should_migrate_ = value_arg;
}


EncodableList DecryptConfig::ToEncodableList() const {
  EncodableList list;
  list.reserve(5);
  list.push_back(prompt_subtitle_ ? EncodableValue(*prompt_subtitle_) : EncodableValue());
  list.push_back(prompt_description_ ? EncodableValue(*prompt_description_) : EncodableValue());
  list.push_back(cancel_button_text_ ? EncodableValue(*cancel_button_text_) : EncodableValue());
  list.push_back(allow_device_credentials_ ? EncodableValue(*allow_device_credentials_) : EncodableValue());
  list.push_back(should_migrate_ ? EncodableValue(*should_migrate_) : EncodableValue());
  return list;
}

DecryptConfig DecryptConfig::FromEncodableList(const EncodableList& list) {
  DecryptConfig decoded;
  auto& encodable_prompt_subtitle = list[0];
  if (!encodable_prompt_subtitle.IsNull()) {
    decoded.set_prompt_subtitle(std::get<std::string>(encodable_prompt_subtitle));
  }
  auto& encodable_prompt_description = list[1];
  if (!encodable_prompt_description.IsNull()) {
    decoded.set_prompt_description(std::get<std::string>(encodable_prompt_description));
  }
  auto& encodable_cancel_button_text = list[2];
  if (!encodable_cancel_button_text.IsNull()) {
    decoded.set_cancel_button_text(std::get<std::string>(encodable_cancel_button_text));
  }
  auto& encodable_allow_device_credentials = list[3];
  if (!encodable_allow_device_credentials.IsNull()) {
    decoded.set_allow_device_credentials(std::get<bool>(encodable_allow_device_credentials));
  }
  auto& encodable_should_migrate = list[4];
  if (!encodable_should_migrate.IsNull()) {
    decoded.set_should_migrate(std::get<bool>(encodable_should_migrate));
  }
  return decoded;
}

// SimplePromptConfig

SimplePromptConfig::SimplePromptConfig() {}

SimplePromptConfig::SimplePromptConfig(
  const std::string* subtitle,
  const std::string* description,
  const std::string* cancel_button_text,
  const bool* allow_device_credentials,
  const BiometricStrength* biometric_strength)
 : subtitle_(subtitle ? std::optional<std::string>(*subtitle) : std::nullopt),
    description_(description ? std::optional<std::string>(*description) : std::nullopt),
    cancel_button_text_(cancel_button_text ? std::optional<std::string>(*cancel_button_text) : std::nullopt),
    allow_device_credentials_(allow_device_credentials ? std::optional<bool>(*allow_device_credentials) : std::nullopt),
    biometric_strength_(biometric_strength ? std::optional<BiometricStrength>(*biometric_strength) : std::nullopt) {}

const std::string* SimplePromptConfig::subtitle() const {
  return subtitle_ ? &(*subtitle_) : nullptr;
}

void SimplePromptConfig::set_subtitle(const std::string_view* value_arg) {
  subtitle_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void SimplePromptConfig::set_subtitle(std::string_view value_arg) {
  subtitle_ = value_arg;
}


const std::string* SimplePromptConfig::description() const {
  return description_ ? &(*description_) : nullptr;
}

void SimplePromptConfig::set_description(const std::string_view* value_arg) {
  description_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void SimplePromptConfig::set_description(std::string_view value_arg) {
  description_ = value_arg;
}


const std::string* SimplePromptConfig::cancel_button_text() const {
  return cancel_button_text_ ? &(*cancel_button_text_) : nullptr;
}

void SimplePromptConfig::set_cancel_button_text(const std::string_view* value_arg) {
  cancel_button_text_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void SimplePromptConfig::set_cancel_button_text(std::string_view value_arg) {
  cancel_button_text_ = value_arg;
}


const bool* SimplePromptConfig::allow_device_credentials() const {
  return allow_device_credentials_ ? &(*allow_device_credentials_) : nullptr;
}

void SimplePromptConfig::set_allow_device_credentials(const bool* value_arg) {
  allow_device_credentials_ = value_arg ? std::optional<bool>(*value_arg) : std::nullopt;
}

void SimplePromptConfig::set_allow_device_credentials(bool value_arg) {
  allow_device_credentials_ = value_arg;
}


const BiometricStrength* SimplePromptConfig::biometric_strength() const {
  return biometric_strength_ ? &(*biometric_strength_) : nullptr;
}

void SimplePromptConfig::set_biometric_strength(const BiometricStrength* value_arg) {
  biometric_strength_ = value_arg ? std::optional<BiometricStrength>(*value_arg) : std::nullopt;
}

void SimplePromptConfig::set_biometric_strength(const BiometricStrength& value_arg) {
  biometric_strength_ = value_arg;
}


EncodableList SimplePromptConfig::ToEncodableList() const {
  EncodableList list;
  list.reserve(5);
  list.push_back(subtitle_ ? EncodableValue(*subtitle_) : EncodableValue());
  list.push_back(description_ ? EncodableValue(*description_) : EncodableValue());
  list.push_back(cancel_button_text_ ? EncodableValue(*cancel_button_text_) : EncodableValue());
  list.push_back(allow_device_credentials_ ? EncodableValue(*allow_device_credentials_) : EncodableValue());
  list.push_back(biometric_strength_ ? CustomEncodableValue(*biometric_strength_) : EncodableValue());
  return list;
}

SimplePromptConfig SimplePromptConfig::FromEncodableList(const EncodableList& list) {
  SimplePromptConfig decoded;
  auto& encodable_subtitle = list[0];
  if (!encodable_subtitle.IsNull()) {
    decoded.set_subtitle(std::get<std::string>(encodable_subtitle));
  }
  auto& encodable_description = list[1];
  if (!encodable_description.IsNull()) {
    decoded.set_description(std::get<std::string>(encodable_description));
  }
  auto& encodable_cancel_button_text = list[2];
  if (!encodable_cancel_button_text.IsNull()) {
    decoded.set_cancel_button_text(std::get<std::string>(encodable_cancel_button_text));
  }
  auto& encodable_allow_device_credentials = list[3];
  if (!encodable_allow_device_credentials.IsNull()) {
    decoded.set_allow_device_credentials(std::get<bool>(encodable_allow_device_credentials));
  }
  auto& encodable_biometric_strength = list[4];
  if (!encodable_biometric_strength.IsNull()) {
    decoded.set_biometric_strength(std::any_cast<const BiometricStrength&>(std::get<CustomEncodableValue>(encodable_biometric_strength)));
  }
  return decoded;
}

// SimplePromptResult

SimplePromptResult::SimplePromptResult() {}

SimplePromptResult::SimplePromptResult(
  const bool* success,
  const std::string* error,
  const BiometricError* code,
  const AuthenticationType* authentication_type)
 : success_(success ? std::optional<bool>(*success) : std::nullopt),
    error_(error ? std::optional<std::string>(*error) : std::nullopt),
    code_(code ? std::optional<BiometricError>(*code) : std::nullopt),
    authentication_type_(authentication_type ? std::optional<AuthenticationType>(*authentication_type) : std::nullopt) {}

const bool* SimplePromptResult::success() const {
  return success_ ? &(*success_) : nullptr;
}

void SimplePromptResult::set_success(const bool* value_arg) {
  success_ = value_arg ? std::optional<bool>(*value_arg) : std::nullopt;
}

void SimplePromptResult::set_success(bool value_arg) {
  success_ = value_arg;
}


const std::string* SimplePromptResult::error() const {
  return error_ ? &(*error_) : nullptr;
}

void SimplePromptResult::set_error(const std::string_view* value_arg) {
  error_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void SimplePromptResult::set_error(std::string_view value_arg) {
  error_ = value_arg;
}


const BiometricError* SimplePromptResult::code() const {
  return code_ ? &(*code_) : nullptr;
}

void SimplePromptResult::set_code(const BiometricError* value_arg) {
  code_ = value_arg ? std::optional<BiometricError>(*value_arg) : std::nullopt;
}

void SimplePromptResult::set_code(const BiometricError& value_arg) {
  code_ = value_arg;
}


const AuthenticationType* SimplePromptResult::authentication_type() const {
  return authentication_type_ ? &(*authentication_type_) : nullptr;
}

void SimplePromptResult::set_authentication_type(const AuthenticationType* value_arg) {
  authentication_type_ = value_arg ? std::optional<AuthenticationType>(*value_arg) : std::nullopt;
}

void SimplePromptResult::set_authentication_type(const AuthenticationType& value_arg) {
  authentication_type_ = value_arg;
}


EncodableList SimplePromptResult::ToEncodableList() const {
  EncodableList list;
  list.reserve(4);
  list.push_back(success_ ? EncodableValue(*success_) : EncodableValue());
  list.push_back(error_ ? EncodableValue(*error_) : EncodableValue());
  list.push_back(code_ ? CustomEncodableValue(*code_) : EncodableValue());
  list.push_back(authentication_type_ ? CustomEncodableValue(*authentication_type_) : EncodableValue());
  return list;
}

SimplePromptResult SimplePromptResult::FromEncodableList(const EncodableList& list) {
  SimplePromptResult decoded;
  auto& encodable_success = list[0];
  if (!encodable_success.IsNull()) {
    decoded.set_success(std::get<bool>(encodable_success));
  }
  auto& encodable_error = list[1];
  if (!encodable_error.IsNull()) {
    decoded.set_error(std::get<std::string>(encodable_error));
  }
  auto& encodable_code = list[2];
  if (!encodable_code.IsNull()) {
    decoded.set_code(std::any_cast<const BiometricError&>(std::get<CustomEncodableValue>(encodable_code)));
  }
  auto& encodable_authentication_type = list[3];
  if (!encodable_authentication_type.IsNull()) {
    decoded.set_authentication_type(std::any_cast<const AuthenticationType&>(std::get<CustomEncodableValue>(encodable_authentication_type)));
  }
  return decoded;
}


PigeonInternalCodecSerializer::PigeonInternalCodecSerializer() {}

EncodableValue PigeonInternalCodecSerializer::ReadValueOfType(
  uint8_t type,
  flutter::ByteStreamReader* stream) const {
  switch (type) {
    case 129: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<AuthenticationType>(enum_arg_value));
      }
    case 130: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<BiometricType>(enum_arg_value));
      }
    case 131: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<BiometricStrength>(enum_arg_value));
      }
    case 132: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<BiometricError>(enum_arg_value));
      }
    case 133: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<SignatureType>(enum_arg_value));
      }
    case 134: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<KeyFormat>(enum_arg_value));
      }
    case 135: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<SignatureFormat>(enum_arg_value));
      }
    case 136: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<PayloadFormat>(enum_arg_value));
      }
    case 137: {
        return CustomEncodableValue(BiometricAvailability::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 138: {
        return CustomEncodableValue(KeyCreationResult::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 139: {
        return CustomEncodableValue(SignatureResult::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 140: {
        return CustomEncodableValue(DecryptResult::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 141: {
        return CustomEncodableValue(KeyInfo::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 142: {
        return CustomEncodableValue(CreateKeysConfig::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 143: {
        return CustomEncodableValue(CreateSignatureConfig::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 144: {
        return CustomEncodableValue(DecryptConfig::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 145: {
        return CustomEncodableValue(SimplePromptConfig::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 146: {
        return CustomEncodableValue(SimplePromptResult::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    default:
      return flutter::StandardCodecSerializer::ReadValueOfType(type, stream);
    }
}

void PigeonInternalCodecSerializer::WriteValue(
  const EncodableValue& value,
  flutter::ByteStreamWriter* stream) const {
  if (const CustomEncodableValue* custom_value = std::get_if<CustomEncodableValue>(&value)) {
    if (custom_value->type() == typeid(AuthenticationType)) {
      stream->WriteByte(129);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<AuthenticationType>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(BiometricType)) {
      stream->WriteByte(130);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<BiometricType>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(BiometricStrength)) {
      stream->WriteByte(131);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<BiometricStrength>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(BiometricError)) {
      stream->WriteByte(132);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<BiometricError>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(SignatureType)) {
      stream->WriteByte(133);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<SignatureType>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(KeyFormat)) {
      stream->WriteByte(134);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<KeyFormat>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(SignatureFormat)) {
      stream->WriteByte(135);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<SignatureFormat>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(PayloadFormat)) {
      stream->WriteByte(136);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<PayloadFormat>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(BiometricAvailability)) {
      stream->WriteByte(137);
      WriteValue(EncodableValue(std::any_cast<BiometricAvailability>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(KeyCreationResult)) {
      stream->WriteByte(138);
      WriteValue(EncodableValue(std::any_cast<KeyCreationResult>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(SignatureResult)) {
      stream->WriteByte(139);
      WriteValue(EncodableValue(std::any_cast<SignatureResult>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(DecryptResult)) {
      stream->WriteByte(140);
      WriteValue(EncodableValue(std::any_cast<DecryptResult>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(KeyInfo)) {
      stream->WriteByte(141);
      WriteValue(EncodableValue(std::any_cast<KeyInfo>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(CreateKeysConfig)) {
      stream->WriteByte(142);
      WriteValue(EncodableValue(std::any_cast<CreateKeysConfig>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(CreateSignatureConfig)) {
      stream->WriteByte(143);
      WriteValue(EncodableValue(std::any_cast<CreateSignatureConfig>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(DecryptConfig)) {
      stream->WriteByte(144);
      WriteValue(EncodableValue(std::any_cast<DecryptConfig>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(SimplePromptConfig)) {
      stream->WriteByte(145);
      WriteValue(EncodableValue(std::any_cast<SimplePromptConfig>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(SimplePromptResult)) {
      stream->WriteByte(146);
      WriteValue(EncodableValue(std::any_cast<SimplePromptResult>(*custom_value).ToEncodableList()), stream);
      return;
    }
  }
  flutter::StandardCodecSerializer::WriteValue(value, stream);
}

/// The codec used by BiometricSignatureApi.
const flutter::StandardMessageCodec& BiometricSignatureApi::GetCodec() {
  return flutter::StandardMessageCodec::GetInstance(&PigeonInternalCodecSerializer::GetInstance());
}

// Sets up an instance of `BiometricSignatureApi` to handle messages through the `binary_messenger`.
void BiometricSignatureApi::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  BiometricSignatureApi* api) {
  BiometricSignatureApi::SetUp(binary_messenger, api, "");
}

void BiometricSignatureApi::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  BiometricSignatureApi* api,
  const std::string& message_channel_suffix) {
  const std::string prepended_suffix = message_channel_suffix.length() > 0 ? std::string(".") + message_channel_suffix : "";
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.biometricAuthAvailable" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          api->BiometricAuthAvailable([reply](ErrorOr<BiometricAvailability>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.createKeys" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_key_alias_arg = args.at(0);
          const auto* key_alias_arg = std::get_if<std::string>(&encodable_key_alias_arg);
          const auto& encodable_config_arg = args.at(1);
          const auto* config_arg = encodable_config_arg.IsNull() ? nullptr : &(std::any_cast<const CreateKeysConfig&>(std::get<CustomEncodableValue>(encodable_config_arg)));
          const auto& encodable_key_format_arg = args.at(2);
          if (encodable_key_format_arg.IsNull()) {
            reply(WrapError("key_format_arg unexpectedly null."));
            return;
          }
          const auto& key_format_arg = std::any_cast<const KeyFormat&>(std::get<CustomEncodableValue>(encodable_key_format_arg));
          const auto& encodable_prompt_message_arg = args.at(3);
          const auto* prompt_message_arg = std::get_if<std::string>(&encodable_prompt_message_arg);
          api->CreateKeys(key_alias_arg, config_arg, key_format_arg, prompt_message_arg, [reply](ErrorOr<KeyCreationResult>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.createSignature" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_payload_arg = args.at(0);
          if (encodable_payload_arg.IsNull()) {
            reply(WrapError("payload_arg unexpectedly null."));
            return;
          }
          const auto& payload_arg = std::get<std::string>(encodable_payload_arg);
          const auto& encodable_key_alias_arg = args.at(1);
          const auto* key_alias_arg = std::get_if<std::string>(&encodable_key_alias_arg);
          const auto& encodable_config_arg = args.at(2);
          const auto* config_arg = encodable_config_arg.IsNull() ? nullptr : &(std::any_cast<const CreateSignatureConfig&>(std::get<CustomEncodableValue>(encodable_config_arg)));
          const auto& encodable_signature_format_arg = args.at(3);
          if (encodable_signature_format_arg.IsNull()) {
            reply(WrapError("signature_format_arg unexpectedly null."));
            return;
          }
          const auto& signature_format_arg = std::any_cast<const SignatureFormat&>(std::get<CustomEncodableValue>(encodable_signature_format_arg));
          const auto& encodable_key_format_arg = args.at(4);
          if (encodable_key_format_arg.IsNull()) {
            reply(WrapError("key_format_arg unexpectedly null."));
            return;
          }
          const auto& key_format_arg = std::any_cast<const KeyFormat&>(std::get<CustomEncodableValue>(encodable_key_format_arg));
          const auto& encodable_prompt_message_arg = args.at(5);
          const auto* prompt_message_arg = std::get_if<std::string>(&encodable_prompt_message_arg);
          api->CreateSignature(payload_arg, key_alias_arg, config_arg, signature_format_arg, key_format_arg, prompt_message_arg, [reply](ErrorOr<SignatureResult>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.decrypt" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_payload_arg = args.at(0);
          if (encodable_payload_arg.IsNull()) {
            reply(WrapError("payload_arg unexpectedly null."));
            return;
          }
          const auto& payload_arg = std::get<std::string>(encodable_payload_arg);
          const auto& encodable_key_alias_arg = args.at(1);
          const auto* key_alias_arg = std::get_if<std::string>(&encodable_key_alias_arg);
          const auto& encodable_payload_format_arg = args.at(2);
          if (encodable_payload_format_arg.IsNull()) {
            reply(WrapError("payload_format_arg unexpectedly null."));
            return;
          }
          const auto& payload_format_arg = std::any_cast<const PayloadFormat&>(std::get<CustomEncodableValue>(encodable_payload_format_arg));
          const auto& encodable_config_arg = args.at(3);
          const auto* config_arg = encodable_config_arg.IsNull() ? nullptr : &(std::any_cast<const DecryptConfig&>(std::get<CustomEncodableValue>(encodable_config_arg)));
          const auto& encodable_prompt_message_arg = args.at(4);
          const auto* prompt_message_arg = std::get_if<std::string>(&encodable_prompt_message_arg);
          api->Decrypt(payload_arg, key_alias_arg, payload_format_arg, config_arg, prompt_message_arg, [reply](ErrorOr<DecryptResult>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.deleteKeys" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_key_alias_arg = args.at(0);
          const auto* key_alias_arg = std::get_if<std::string>(&encodable_key_alias_arg);
          api->DeleteKeys(key_alias_arg, [reply](ErrorOr<bool>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.deleteAllKeys" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          api->DeleteAllKeys([reply](ErrorOr<bool>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.getKeyInfo" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_key_alias_arg = args.at(0);
          const auto* key_alias_arg = std::get_if<std::string>(&encodable_key_alias_arg);
          const auto& encodable_check_validity_arg = args.at(1);
          if (encodable_check_validity_arg.IsNull()) {
            reply(WrapError("check_validity_arg unexpectedly null."));
            return;
          }
          const auto& check_validity_arg = std::get<bool>(encodable_check_validity_arg);
          const auto& encodable_key_format_arg = args.at(2);
          if (encodable_key_format_arg.IsNull()) {
            reply(WrapError("key_format_arg unexpectedly null."));
            return;
          }
          const auto& key_format_arg = std::any_cast<const KeyFormat&>(std::get<CustomEncodableValue>(encodable_key_format_arg));
          api->GetKeyInfo(key_alias_arg, check_validity_arg, key_format_arg, [reply](ErrorOr<KeyInfo>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.simplePrompt" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_prompt_message_arg = args.at(0);
          if (encodable_prompt_message_arg.IsNull()) {
            reply(WrapError("prompt_message_arg unexpectedly null."));
            return;
          }
          const auto& prompt_message_arg = std::get<std::string>(encodable_prompt_message_arg);
          const auto& encodable_config_arg = args.at(1);
          const auto* config_arg = encodable_config_arg.IsNull() ? nullptr : &(std::any_cast<const SimplePromptConfig&>(std::get<CustomEncodableValue>(encodable_config_arg)));
          api->SimplePrompt(prompt_message_arg, config_arg, [reply](ErrorOr<SimplePromptResult>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.isDeviceLockSet" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          api->IsDeviceLockSet([reply](ErrorOr<bool>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
}

EncodableValue BiometricSignatureApi::WrapError(std::string_view error_message) {
  return EncodableValue(EncodableList{
    EncodableValue(std::string(error_message)),
    EncodableValue("Error"),
    EncodableValue()
  });
}

EncodableValue BiometricSignatureApi::WrapError(const FlutterError& error) {
  return EncodableValue(EncodableList{
    EncodableValue(error.code()),
    EncodableValue(error.message()),
    error.details()
  });
}

}  // namespace biometric_signature
