// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_MESSAGES_G_H_
#define PIGEON_MESSAGES_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace biometric_signature {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const ::flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const ::flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  ::flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class BiometricSignatureApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};


// The type of authentication that was used to complete an operation.
//
// On Android, this is determined by the platform's `AuthenticationResult.getAuthenticationType()`.
// On iOS/macOS, this is inferred: [biometric] if device credentials are not allowed,
// [credential] if no biometric hardware is available, [unknown] otherwise.
// On Windows, this is always [unknown] as Windows Hello handles auth internally.
enum class AuthenticationType {
  // The user authenticated using device credentials (PIN, pattern, or password).
  kCredential = 0,
  // The user authenticated using a biometric (fingerprint, face, iris).
  kBiometric = 1,
  // The authentication type could not be determined.
  kUnknown = 2
};

// Types of biometric authentication supported by the device.
enum class BiometricType {
  // Face recognition (Face ID on iOS, face unlock on Android).
  kFace = 0,
  // Fingerprint recognition (Touch ID on iOS/macOS, fingerprint on Android).
  kFingerprint = 1,
  // Iris scanner (Android only, rare on consumer devices).
  kIris = 2,
  // Multiple biometric types are available on the device.
  kMultiple = 3,
  // No biometric hardware available or biometrics are disabled.
  kUnavailable = 4
};

// Biometric authentication strength level.
//
// This affects which biometric sensors can be used for authentication.
// Note: On iOS/macOS, only strong biometrics are available (Face ID, Touch ID, Optic ID).
// On Windows, Windows Hello always uses strong authentication.
enum class BiometricStrength {
  // Strong biometrics only (e.g., fingerprint, face recognition with depth sensing).
  // This is the most secure option and is required for cryptographic operations.
  kStrong = 0,
  // Weak biometrics allowed (e.g., face recognition without depth sensing).
  // This option provides more device compatibility but lower security.
  kWeak = 1
};

// Standardized error codes for the plugin.
enum class BiometricError {
  // The operation was successful.
  kSuccess = 0,
  // The user canceled the operation.
  kUserCanceled = 1,
  // Biometric authentication is not available on this device.
  kNotAvailable = 2,
  // No biometrics are enrolled.
  kNotEnrolled = 3,
  // The user is temporarily locked out due to too many failed attempts.
  kLockedOut = 4,
  // The user is permanently locked out until they log in with a strong method.
  kLockedOutPermanent = 5,
  // The requested key was not found.
  kKeyNotFound = 6,
  // The key has been invalidated (e.g. by new biometric enrollment).
  kKeyInvalidated = 7,
  // An unknown error occurred.
  kUnknown = 8,
  // The input payload was invalid (e.g. not valid Base64).
  kInvalidInput = 9,
  // A security update is required before biometrics can be used.
  kSecurityUpdateRequired = 10,
  // Biometric authentication is not supported on this device/OS version.
  kNotSupported = 11,
  // The system canceled the operation (e.g., app went to background).
  kSystemCanceled = 12,
  // Failed to show the biometric prompt (e.g., activity not available).
  kPromptError = 13,
  // A key with the specified alias already exists and failIfExists was set.
  kKeyAlreadyExists = 14,
  // The user selected a custom fallback option instead of authenticating.
  // [Android 15+ only] Check `selectedFallbackIndex` and `selectedFallbackText`
  // on the result object to determine which option was selected.
  kFallbackSelected = 15,
  // The device does not have a screen lock (PIN, pattern, password, or
  // passcode) configured.
  //
  // A screen lock is a prerequisite for biometric enrollment and for
  // hardware-backed key storage on all platforms:
  // - **iOS/macOS**: Maps from `kLAErrorPasscodeNotSet`. Can surface during
  //   any operation that requires Secure Enclave access (key creation,
  //   signing, decryption, and simple prompt).
  // - **Android**: Maps from `ERROR_NO_DEVICE_CREDENTIAL` (cause code 14).
  //   Only surfaces when `allowDeviceCredentials: true` is set; for
  //   biometric-only flows Android reports [notAvailable] or [notEnrolled]
  //   instead.
  // - **Windows**: Not applicable — Windows Hello manages its own credential
  //   requirements.
  //
  // Use [BiometricSignatureApi.isDeviceLockSet] as a proactive precondition
  // check before attempting operations. This error is the reactive
  // counterpart when the check is skipped or the user removes their screen
  // lock between the check and the operation.
  kPasscodeNotSet = 16
};

// The cryptographic algorithm to use for key generation.
enum class SignatureType {
  // RSA-2048 (Android: native, iOS/macOS: hybrid mode with Secure Enclave EC).
  kRsa = 0,
  // ECDSA P-256 (hardware-backed on all platforms).
  kEcdsa = 1
};

// Output format for public keys.
enum class KeyFormat {
  // Base64-encoded DER (SubjectPublicKeyInfo).
  kBase64 = 0,
  // PEM format with BEGIN/END PUBLIC KEY headers.
  kPem = 1,
  // Hexadecimal-encoded DER.
  kHex = 2,
  // Raw DER bytes (returned via `publicKeyBytes`).
  kRaw = 3
};

// Output format for cryptographic signatures.
enum class SignatureFormat {
  // Base64-encoded signature bytes.
  kBase64 = 0,
  // Hexadecimal-encoded signature bytes.
  kHex = 1,
  // Raw signature bytes (returned via `signatureBytes`).
  kRaw = 2
};

// Input format for encrypted payloads to decrypt.
enum class PayloadFormat {
  // Base64-encoded ciphertext.
  kBase64 = 0,
  // Hexadecimal-encoded ciphertext.
  kHex = 1,
  // Raw UTF-8 string (not recommended for binary data).
  kRaw = 2
};


// A custom fallback option shown on the biometric prompt.
//
// [Android 15+ only] When provided in a config's `fallbackOptions` list,
// these appear as alternative buttons on the biometric prompt dialog.
// If the user taps one, the result will have code [BiometricError.fallbackSelected]
// with the selected option's index and text.
//
// On iOS, macOS, and Windows this class is ignored.
//
// Generated class from Pigeon that represents data sent in messages.
class BiometricFallbackOption {
 public:
  // Constructs an object setting all non-nullable fields.
  BiometricFallbackOption();

  // Constructs an object setting all fields.
  explicit BiometricFallbackOption(
    const std::string* text,
    const std::string* icon_name);

  // The text label displayed on the fallback button.
  const std::string* text() const;
  void set_text(const std::string_view* value_arg);
  void set_text(std::string_view value_arg);

  // [Android] Optional icon type name for the fallback button.
  // Valid values: `"password"`, `"qr_code"`, `"account"`, `"generic"`.
  // Maps to `AuthenticationRequest.Biometric.Fallback.ICON_TYPE_*` constants.
  // When null, defaults to `"generic"`.
  const std::string* icon_name() const;
  void set_icon_name(const std::string_view* value_arg);
  void set_icon_name(std::string_view value_arg);

  bool operator==(const BiometricFallbackOption& other) const;
  bool operator!=(const BiometricFallbackOption& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
 private:
  static BiometricFallbackOption FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class BiometricSignatureApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<std::string> text_;
  std::optional<std::string> icon_name_;
};


// Generated class from Pigeon that represents data sent in messages.
class BiometricAvailability {
 public:
  // Constructs an object setting all non-nullable fields.
  BiometricAvailability();

  // Constructs an object setting all fields.
  explicit BiometricAvailability(
    const bool* can_authenticate,
    const bool* has_enrolled_biometrics,
    const ::flutter::EncodableList* available_biometrics,
    const std::string* reason);

  const bool* can_authenticate() const;
  void set_can_authenticate(const bool* value_arg);
  void set_can_authenticate(bool value_arg);

  const bool* has_enrolled_biometrics() const;
  void set_has_enrolled_biometrics(const bool* value_arg);
  void set_has_enrolled_biometrics(bool value_arg);

  const ::flutter::EncodableList* available_biometrics() const;
  void set_available_biometrics(const ::flutter::EncodableList* value_arg);
  void set_available_biometrics(const ::flutter::EncodableList& value_arg);

  const std::string* reason() const;
  void set_reason(const std::string_view* value_arg);
  void set_reason(std::string_view value_arg);

  bool operator==(const BiometricAvailability& other) const;
  bool operator!=(const BiometricAvailability& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
 private:
  static BiometricAvailability FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class BiometricSignatureApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<bool> can_authenticate_;
  std::optional<bool> has_enrolled_biometrics_;
  std::optional<::flutter::EncodableList> available_biometrics_;
  std::optional<std::string> reason_;
};


// Generated class from Pigeon that represents data sent in messages.
class KeyCreationResult {
 public:
  // Constructs an object setting all non-nullable fields.
  KeyCreationResult();

  // Constructs an object setting all fields.
  explicit KeyCreationResult(
    const std::string* public_key,
    const std::vector<uint8_t>* public_key_bytes,
    const std::string* error,
    const BiometricError* code,
    const std::string* algorithm,
    const int64_t* key_size,
    const std::string* decrypting_public_key,
    const std::string* decrypting_algorithm,
    const int64_t* decrypting_key_size,
    const bool* is_hybrid_mode,
    const AuthenticationType* authentication_type);

  const std::string* public_key() const;
  void set_public_key(const std::string_view* value_arg);
  void set_public_key(std::string_view value_arg);

  const std::vector<uint8_t>* public_key_bytes() const;
  void set_public_key_bytes(const std::vector<uint8_t>* value_arg);
  void set_public_key_bytes(const std::vector<uint8_t>& value_arg);

  const std::string* error() const;
  void set_error(const std::string_view* value_arg);
  void set_error(std::string_view value_arg);

  const BiometricError* code() const;
  void set_code(const BiometricError* value_arg);
  void set_code(const BiometricError& value_arg);

  const std::string* algorithm() const;
  void set_algorithm(const std::string_view* value_arg);
  void set_algorithm(std::string_view value_arg);

  const int64_t* key_size() const;
  void set_key_size(const int64_t* value_arg);
  void set_key_size(int64_t value_arg);

  const std::string* decrypting_public_key() const;
  void set_decrypting_public_key(const std::string_view* value_arg);
  void set_decrypting_public_key(std::string_view value_arg);

  const std::string* decrypting_algorithm() const;
  void set_decrypting_algorithm(const std::string_view* value_arg);
  void set_decrypting_algorithm(std::string_view value_arg);

  const int64_t* decrypting_key_size() const;
  void set_decrypting_key_size(const int64_t* value_arg);
  void set_decrypting_key_size(int64_t value_arg);

  const bool* is_hybrid_mode() const;
  void set_is_hybrid_mode(const bool* value_arg);
  void set_is_hybrid_mode(bool value_arg);

  // The type of authentication used to complete this operation.
  const AuthenticationType* authentication_type() const;
  void set_authentication_type(const AuthenticationType* value_arg);
  void set_authentication_type(const AuthenticationType& value_arg);

  bool operator==(const KeyCreationResult& other) const;
  bool operator!=(const KeyCreationResult& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
 private:
  static KeyCreationResult FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class BiometricSignatureApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<std::string> public_key_;
  std::optional<std::vector<uint8_t>> public_key_bytes_;
  std::optional<std::string> error_;
  std::optional<BiometricError> code_;
  std::optional<std::string> algorithm_;
  std::optional<int64_t> key_size_;
  std::optional<std::string> decrypting_public_key_;
  std::optional<std::string> decrypting_algorithm_;
  std::optional<int64_t> decrypting_key_size_;
  std::optional<bool> is_hybrid_mode_;
  std::optional<AuthenticationType> authentication_type_;
};


// Generated class from Pigeon that represents data sent in messages.
class SignatureResult {
 public:
  // Constructs an object setting all non-nullable fields.
  SignatureResult();

  // Constructs an object setting all fields.
  explicit SignatureResult(
    const std::string* signature,
    const std::vector<uint8_t>* signature_bytes,
    const std::string* public_key,
    const std::string* error,
    const BiometricError* code,
    const std::string* algorithm,
    const int64_t* key_size,
    const int64_t* selected_fallback_index,
    const std::string* selected_fallback_text,
    const AuthenticationType* authentication_type);

  const std::string* signature() const;
  void set_signature(const std::string_view* value_arg);
  void set_signature(std::string_view value_arg);

  const std::vector<uint8_t>* signature_bytes() const;
  void set_signature_bytes(const std::vector<uint8_t>* value_arg);
  void set_signature_bytes(const std::vector<uint8_t>& value_arg);

  const std::string* public_key() const;
  void set_public_key(const std::string_view* value_arg);
  void set_public_key(std::string_view value_arg);

  const std::string* error() const;
  void set_error(const std::string_view* value_arg);
  void set_error(std::string_view value_arg);

  const BiometricError* code() const;
  void set_code(const BiometricError* value_arg);
  void set_code(const BiometricError& value_arg);

  const std::string* algorithm() const;
  void set_algorithm(const std::string_view* value_arg);
  void set_algorithm(std::string_view value_arg);

  const int64_t* key_size() const;
  void set_key_size(const int64_t* value_arg);
  void set_key_size(int64_t value_arg);

  // [Android 15+] Index of the selected fallback option in the original list.
  // Only populated when `code == BiometricError.fallbackSelected`.
  const int64_t* selected_fallback_index() const;
  void set_selected_fallback_index(const int64_t* value_arg);
  void set_selected_fallback_index(int64_t value_arg);

  // [Android 15+] Text of the selected fallback option.
  // Only populated when `code == BiometricError.fallbackSelected`.
  const std::string* selected_fallback_text() const;
  void set_selected_fallback_text(const std::string_view* value_arg);
  void set_selected_fallback_text(std::string_view value_arg);

  // The type of authentication used to complete this operation.
  const AuthenticationType* authentication_type() const;
  void set_authentication_type(const AuthenticationType* value_arg);
  void set_authentication_type(const AuthenticationType& value_arg);

  bool operator==(const SignatureResult& other) const;
  bool operator!=(const SignatureResult& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
 private:
  static SignatureResult FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class BiometricSignatureApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<std::string> signature_;
  std::optional<std::vector<uint8_t>> signature_bytes_;
  std::optional<std::string> public_key_;
  std::optional<std::string> error_;
  std::optional<BiometricError> code_;
  std::optional<std::string> algorithm_;
  std::optional<int64_t> key_size_;
  std::optional<int64_t> selected_fallback_index_;
  std::optional<std::string> selected_fallback_text_;
  std::optional<AuthenticationType> authentication_type_;
};


// Generated class from Pigeon that represents data sent in messages.
class DecryptResult {
 public:
  // Constructs an object setting all non-nullable fields.
  DecryptResult();

  // Constructs an object setting all fields.
  explicit DecryptResult(
    const std::string* decrypted_data,
    const std::string* error,
    const BiometricError* code,
    const int64_t* selected_fallback_index,
    const std::string* selected_fallback_text,
    const AuthenticationType* authentication_type);

  const std::string* decrypted_data() const;
  void set_decrypted_data(const std::string_view* value_arg);
  void set_decrypted_data(std::string_view value_arg);

  const std::string* error() const;
  void set_error(const std::string_view* value_arg);
  void set_error(std::string_view value_arg);

  const BiometricError* code() const;
  void set_code(const BiometricError* value_arg);
  void set_code(const BiometricError& value_arg);

  // [Android 15+] Index of the selected fallback option in the original list.
  // Only populated when `code == BiometricError.fallbackSelected`.
  const int64_t* selected_fallback_index() const;
  void set_selected_fallback_index(const int64_t* value_arg);
  void set_selected_fallback_index(int64_t value_arg);

  // [Android 15+] Text of the selected fallback option.
  // Only populated when `code == BiometricError.fallbackSelected`.
  const std::string* selected_fallback_text() const;
  void set_selected_fallback_text(const std::string_view* value_arg);
  void set_selected_fallback_text(std::string_view value_arg);

  // The type of authentication used to complete this operation.
  const AuthenticationType* authentication_type() const;
  void set_authentication_type(const AuthenticationType* value_arg);
  void set_authentication_type(const AuthenticationType& value_arg);

  bool operator==(const DecryptResult& other) const;
  bool operator!=(const DecryptResult& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
 private:
  static DecryptResult FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class BiometricSignatureApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<std::string> decrypted_data_;
  std::optional<std::string> error_;
  std::optional<BiometricError> code_;
  std::optional<int64_t> selected_fallback_index_;
  std::optional<std::string> selected_fallback_text_;
  std::optional<AuthenticationType> authentication_type_;
};


// Detailed information about existing biometric keys.
//
// Generated class from Pigeon that represents data sent in messages.
class KeyInfo {
 public:
  // Constructs an object setting all non-nullable fields.
  KeyInfo();

  // Constructs an object setting all fields.
  explicit KeyInfo(
    const bool* exists,
    const bool* is_valid,
    const std::string* algorithm,
    const int64_t* key_size,
    const bool* is_hybrid_mode,
    const std::string* public_key,
    const std::string* decrypting_public_key,
    const std::string* decrypting_algorithm,
    const int64_t* decrypting_key_size);

  // Whether any biometric key exists on the device.
  const bool* exists() const;
  void set_exists(const bool* value_arg);
  void set_exists(bool value_arg);

  // Whether the key is still valid (not invalidated by biometric changes).
  // Only populated when `checkValidity: true` is passed.
  const bool* is_valid() const;
  void set_is_valid(const bool* value_arg);
  void set_is_valid(bool value_arg);

  // The algorithm of the signing key (e.g., "RSA", "EC").
  const std::string* algorithm() const;
  void set_algorithm(const std::string_view* value_arg);
  void set_algorithm(std::string_view value_arg);

  // The key size in bits (e.g., 2048 for RSA, 256 for EC).
  const int64_t* key_size() const;
  void set_key_size(const int64_t* value_arg);
  void set_key_size(int64_t value_arg);

  // Whether the key is in hybrid mode (separate signing and decryption keys).
  const bool* is_hybrid_mode() const;
  void set_is_hybrid_mode(const bool* value_arg);
  void set_is_hybrid_mode(bool value_arg);

  // Signing key public key (formatted according to the requested format).
  const std::string* public_key() const;
  void set_public_key(const std::string_view* value_arg);
  void set_public_key(std::string_view value_arg);

  // Decryption key public key for hybrid mode.
  const std::string* decrypting_public_key() const;
  void set_decrypting_public_key(const std::string_view* value_arg);
  void set_decrypting_public_key(std::string_view value_arg);

  // Algorithm of the decryption key (hybrid mode only).
  const std::string* decrypting_algorithm() const;
  void set_decrypting_algorithm(const std::string_view* value_arg);
  void set_decrypting_algorithm(std::string_view value_arg);

  // Key size of the decryption key in bits (hybrid mode only).
  const int64_t* decrypting_key_size() const;
  void set_decrypting_key_size(const int64_t* value_arg);
  void set_decrypting_key_size(int64_t value_arg);

  bool operator==(const KeyInfo& other) const;
  bool operator!=(const KeyInfo& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
 private:
  static KeyInfo FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class BiometricSignatureApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<bool> exists_;
  std::optional<bool> is_valid_;
  std::optional<std::string> algorithm_;
  std::optional<int64_t> key_size_;
  std::optional<bool> is_hybrid_mode_;
  std::optional<std::string> public_key_;
  std::optional<std::string> decrypting_public_key_;
  std::optional<std::string> decrypting_algorithm_;
  std::optional<int64_t> decrypting_key_size_;
};


// Configuration for key creation (all platforms).
//
// Fields are documented with which platform(s) they apply to.
// Windows ignores most fields as it only supports RSA with mandatory
// Windows Hello authentication.
//
// Generated class from Pigeon that represents data sent in messages.
class CreateKeysConfig {
 public:
  // Constructs an object setting all non-nullable fields.
  CreateKeysConfig();

  // Constructs an object setting all fields.
  explicit CreateKeysConfig(
    const SignatureType* signature_type,
    const bool* enforce_biometric,
    const bool* set_invalidated_by_biometric_enrollment,
    const bool* use_device_credentials,
    const bool* enable_decryption,
    const std::string* prompt_subtitle,
    const std::string* prompt_description,
    const std::string* cancel_button_text,
    const bool* fail_if_exists,
    const ::flutter::EncodableList* fallback_options);

  // [Android/iOS/macOS] The cryptographic algorithm to use.
  // Windows only supports RSA and ignores this field.
  const SignatureType* signature_type() const;
  void set_signature_type(const SignatureType* value_arg);
  void set_signature_type(const SignatureType& value_arg);

  // [Android/iOS/macOS] Whether to require biometric authentication
  // during key creation. Windows always authenticates via Windows Hello.
  const bool* enforce_biometric() const;
  void set_enforce_biometric(const bool* value_arg);
  void set_enforce_biometric(bool value_arg);

  // [Android/iOS/macOS] Whether to invalidate the key when new biometrics
  // are enrolled. Not supported on Windows.
  //
  // **Security Note**: When `true`, keys become invalid if fingerprints/faces
  // are added or removed, preventing unauthorized access if an attacker
  // enrolls their own biometrics on a compromised device.
  const bool* set_invalidated_by_biometric_enrollment() const;
  void set_set_invalidated_by_biometric_enrollment(const bool* value_arg);
  void set_set_invalidated_by_biometric_enrollment(bool value_arg);

  // [Android/iOS/macOS] Whether to allow device credentials (PIN/pattern/passcode)
  // as fallback for biometric authentication. Not supported on Windows.
  const bool* use_device_credentials() const;
  void set_use_device_credentials(const bool* value_arg);
  void set_use_device_credentials(bool value_arg);

  // [Android] Whether to enable decryption capability for the key.
  // On iOS/macOS, decryption is always available with EC keys.
  const bool* enable_decryption() const;
  void set_enable_decryption(const bool* value_arg);
  void set_enable_decryption(bool value_arg);

  // [Android] Subtitle text for the biometric prompt.
  const std::string* prompt_subtitle() const;
  void set_prompt_subtitle(const std::string_view* value_arg);
  void set_prompt_subtitle(std::string_view value_arg);

  // [Android] Description text for the biometric prompt.
  const std::string* prompt_description() const;
  void set_prompt_description(const std::string_view* value_arg);
  void set_prompt_description(std::string_view value_arg);

  // [Android] Text for the cancel button in the biometric prompt.
  const std::string* cancel_button_text() const;
  void set_cancel_button_text(const std::string_view* value_arg);
  void set_cancel_button_text(std::string_view value_arg);

  // [All platforms] When `true`, key creation will fail with
  // [BiometricError.keyAlreadyExists] if a key with the specified alias
  // (or the default alias) already exists.
  //
  // When `false` (default), existing keys are silently replaced.
  const bool* fail_if_exists() const;
  void set_fail_if_exists(const bool* value_arg);
  void set_fail_if_exists(bool value_arg);

  // [Android 15+] Custom fallback buttons shown on the biometric prompt.
  // When provided, these replace the default cancel button.
  // If the user taps a fallback option, the result will have
  // `code == BiometricError.fallbackSelected` with the selected option's
  // index and text. On other platforms, this field is ignored.
  const ::flutter::EncodableList* fallback_options() const;
  void set_fallback_options(const ::flutter::EncodableList* value_arg);
  void set_fallback_options(const ::flutter::EncodableList& value_arg);

  bool operator==(const CreateKeysConfig& other) const;
  bool operator!=(const CreateKeysConfig& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
 private:
  static CreateKeysConfig FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class BiometricSignatureApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<SignatureType> signature_type_;
  std::optional<bool> enforce_biometric_;
  std::optional<bool> set_invalidated_by_biometric_enrollment_;
  std::optional<bool> use_device_credentials_;
  std::optional<bool> enable_decryption_;
  std::optional<std::string> prompt_subtitle_;
  std::optional<std::string> prompt_description_;
  std::optional<std::string> cancel_button_text_;
  std::optional<bool> fail_if_exists_;
  std::optional<::flutter::EncodableList> fallback_options_;
};


// Configuration for signature creation (all platforms).
//
// Fields are documented with which platform(s) they apply to.
//
// Generated class from Pigeon that represents data sent in messages.
class CreateSignatureConfig {
 public:
  // Constructs an object setting all non-nullable fields.
  CreateSignatureConfig();

  // Constructs an object setting all fields.
  explicit CreateSignatureConfig(
    const std::string* prompt_subtitle,
    const std::string* prompt_description,
    const std::string* cancel_button_text,
    const bool* allow_device_credentials,
    const bool* should_migrate,
    const ::flutter::EncodableList* fallback_options);

  // [Android] Subtitle text for the biometric prompt.
  const std::string* prompt_subtitle() const;
  void set_prompt_subtitle(const std::string_view* value_arg);
  void set_prompt_subtitle(std::string_view value_arg);

  // [Android] Description text for the biometric prompt.
  const std::string* prompt_description() const;
  void set_prompt_description(const std::string_view* value_arg);
  void set_prompt_description(std::string_view value_arg);

  // [Android] Text for the cancel button in the biometric prompt.
  const std::string* cancel_button_text() const;
  void set_cancel_button_text(const std::string_view* value_arg);
  void set_cancel_button_text(std::string_view value_arg);

  // [Android] Whether to allow device credentials (PIN/pattern) as fallback.
  const bool* allow_device_credentials() const;
  void set_allow_device_credentials(const bool* value_arg);
  void set_allow_device_credentials(bool value_arg);

  // [iOS] Whether to migrate from legacy keychain storage.
  const bool* should_migrate() const;
  void set_should_migrate(const bool* value_arg);
  void set_should_migrate(bool value_arg);

  // [Android 15+] Custom fallback buttons shown on the biometric prompt.
  // When provided, these replace the default cancel button.
  // If the user taps a fallback option, the result will have
  // `code == BiometricError.fallbackSelected` with the selected option's
  // index and text. On other platforms, this field is ignored.
  const ::flutter::EncodableList* fallback_options() const;
  void set_fallback_options(const ::flutter::EncodableList* value_arg);
  void set_fallback_options(const ::flutter::EncodableList& value_arg);

  bool operator==(const CreateSignatureConfig& other) const;
  bool operator!=(const CreateSignatureConfig& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
 private:
  static CreateSignatureConfig FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class BiometricSignatureApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<std::string> prompt_subtitle_;
  std::optional<std::string> prompt_description_;
  std::optional<std::string> cancel_button_text_;
  std::optional<bool> allow_device_credentials_;
  std::optional<bool> should_migrate_;
  std::optional<::flutter::EncodableList> fallback_options_;
};


// Configuration for decryption (all platforms).
//
// Fields are documented with which platform(s) they apply to.
// Note: Decryption is not supported on Windows.
//
// Generated class from Pigeon that represents data sent in messages.
class DecryptConfig {
 public:
  // Constructs an object setting all non-nullable fields.
  DecryptConfig();

  // Constructs an object setting all fields.
  explicit DecryptConfig(
    const std::string* prompt_subtitle,
    const std::string* prompt_description,
    const std::string* cancel_button_text,
    const bool* allow_device_credentials,
    const bool* should_migrate,
    const ::flutter::EncodableList* fallback_options);

  // [Android] Subtitle text for the biometric prompt.
  const std::string* prompt_subtitle() const;
  void set_prompt_subtitle(const std::string_view* value_arg);
  void set_prompt_subtitle(std::string_view value_arg);

  // [Android] Description text for the biometric prompt.
  const std::string* prompt_description() const;
  void set_prompt_description(const std::string_view* value_arg);
  void set_prompt_description(std::string_view value_arg);

  // [Android] Text for the cancel button in the biometric prompt.
  const std::string* cancel_button_text() const;
  void set_cancel_button_text(const std::string_view* value_arg);
  void set_cancel_button_text(std::string_view value_arg);

  // [Android] Whether to allow device credentials (PIN/pattern) as fallback.
  const bool* allow_device_credentials() const;
  void set_allow_device_credentials(const bool* value_arg);
  void set_allow_device_credentials(bool value_arg);

  // [iOS] Whether to migrate from legacy keychain storage.
  const bool* should_migrate() const;
  void set_should_migrate(const bool* value_arg);
  void set_should_migrate(bool value_arg);

  // [Android 15+] Custom fallback buttons shown on the biometric prompt.
  // When provided, these replace the default cancel button.
  // If the user taps a fallback option, the result will have
  // `code == BiometricError.fallbackSelected` with the selected option's
  // index and text. On other platforms, this field is ignored.
  const ::flutter::EncodableList* fallback_options() const;
  void set_fallback_options(const ::flutter::EncodableList* value_arg);
  void set_fallback_options(const ::flutter::EncodableList& value_arg);

  bool operator==(const DecryptConfig& other) const;
  bool operator!=(const DecryptConfig& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
 private:
  static DecryptConfig FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class BiometricSignatureApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<std::string> prompt_subtitle_;
  std::optional<std::string> prompt_description_;
  std::optional<std::string> cancel_button_text_;
  std::optional<bool> allow_device_credentials_;
  std::optional<bool> should_migrate_;
  std::optional<::flutter::EncodableList> fallback_options_;
};


// Configuration for simple biometric prompt (authentication without crypto ops).
//
// This allows customization of the biometric prompt across platforms.
//
// Generated class from Pigeon that represents data sent in messages.
class SimplePromptConfig {
 public:
  // Constructs an object setting all non-nullable fields.
  SimplePromptConfig();

  // Constructs an object setting all fields.
  explicit SimplePromptConfig(
    const std::string* subtitle,
    const std::string* description,
    const std::string* cancel_button_text,
    const bool* allow_device_credentials,
    const BiometricStrength* biometric_strength,
    const ::flutter::EncodableList* fallback_options);

  // [Android] Subtitle text displayed below the title in the biometric prompt.
  const std::string* subtitle() const;
  void set_subtitle(const std::string_view* value_arg);
  void set_subtitle(std::string_view value_arg);

  // [Android] Description text displayed in the biometric prompt body.
  const std::string* description() const;
  void set_description(const std::string_view* value_arg);
  void set_description(std::string_view value_arg);

  // [Android] Text for the cancel/negative button.
  // Default: "Cancel" on Android, system default on iOS/macOS.
  const std::string* cancel_button_text() const;
  void set_cancel_button_text(const std::string_view* value_arg);
  void set_cancel_button_text(std::string_view value_arg);

  // [Android/iOS/macOS] Whether to allow device credentials (PIN/pattern/passcode)
  // as a fallback for biometric authentication.
  //
  // When true:
  // - Android: Shows "Use PIN" option after biometric failure
  // - iOS/macOS: Uses .deviceOwnerAuthentication policy
  // - Windows: Not applicable (Windows Hello handles fallback internally)
  //
  // Default: false (biometric-only authentication)
  const bool* allow_device_credentials() const;
  void set_allow_device_credentials(const bool* value_arg);
  void set_allow_device_credentials(bool value_arg);

  // [Android] The required biometric strength level.
  //
  // - strong: Only Class 3 biometrics (e.g., fingerprint, in-screen fingerprint)
  // - weak: Class 2 biometrics allowed (e.g., face unlock without depth)
  //
  // Note: iOS/macOS always use strong biometrics. Windows Hello also uses strong.
  // If strong biometrics are not available but weak are, and strength is set to
  // strong, authentication will fail with [BiometricError.notEnrolled].
  //
  // Default: strong
  const BiometricStrength* biometric_strength() const;
  void set_biometric_strength(const BiometricStrength* value_arg);
  void set_biometric_strength(const BiometricStrength& value_arg);

  // [Android 15+] Custom fallback buttons shown on the biometric prompt.
  // When provided, these replace the default cancel button.
  // If the user taps a fallback option, the result will have
  // `code == BiometricError.fallbackSelected` with the selected option's
  // index and text. On other platforms, this field is ignored.
  const ::flutter::EncodableList* fallback_options() const;
  void set_fallback_options(const ::flutter::EncodableList* value_arg);
  void set_fallback_options(const ::flutter::EncodableList& value_arg);

  bool operator==(const SimplePromptConfig& other) const;
  bool operator!=(const SimplePromptConfig& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
 private:
  static SimplePromptConfig FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class BiometricSignatureApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<std::string> subtitle_;
  std::optional<std::string> description_;
  std::optional<std::string> cancel_button_text_;
  std::optional<bool> allow_device_credentials_;
  std::optional<BiometricStrength> biometric_strength_;
  std::optional<::flutter::EncodableList> fallback_options_;
};


// Result from simple biometric prompt authentication.
//
// Generated class from Pigeon that represents data sent in messages.
class SimplePromptResult {
 public:
  // Constructs an object setting all non-nullable fields.
  SimplePromptResult();

  // Constructs an object setting all fields.
  explicit SimplePromptResult(
    const bool* success,
    const std::string* error,
    const BiometricError* code,
    const int64_t* selected_fallback_index,
    const std::string* selected_fallback_text,
    const AuthenticationType* authentication_type);

  // Whether authentication was successful.
  const bool* success() const;
  void set_success(const bool* value_arg);
  void set_success(bool value_arg);

  // Error message if authentication failed.
  // This is a human-readable description of what went wrong.
  const std::string* error() const;
  void set_error(const std::string_view* value_arg);
  void set_error(std::string_view value_arg);

  // Standardized error code if authentication failed.
  // Use this for programmatic error handling.
  const BiometricError* code() const;
  void set_code(const BiometricError* value_arg);
  void set_code(const BiometricError& value_arg);

  // [Android 15+] Index of the selected fallback option in the original list.
  // Only populated when `code == BiometricError.fallbackSelected`.
  const int64_t* selected_fallback_index() const;
  void set_selected_fallback_index(const int64_t* value_arg);
  void set_selected_fallback_index(int64_t value_arg);

  // [Android 15+] Text of the selected fallback option.
  // Only populated when `code == BiometricError.fallbackSelected`.
  const std::string* selected_fallback_text() const;
  void set_selected_fallback_text(const std::string_view* value_arg);
  void set_selected_fallback_text(std::string_view value_arg);

  // The type of authentication used to complete this operation.
  const AuthenticationType* authentication_type() const;
  void set_authentication_type(const AuthenticationType* value_arg);
  void set_authentication_type(const AuthenticationType& value_arg);

  bool operator==(const SimplePromptResult& other) const;
  bool operator!=(const SimplePromptResult& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
 private:
  static SimplePromptResult FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class BiometricSignatureApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<bool> success_;
  std::optional<std::string> error_;
  std::optional<BiometricError> code_;
  std::optional<int64_t> selected_fallback_index_;
  std::optional<std::string> selected_fallback_text_;
  std::optional<AuthenticationType> authentication_type_;
};


class PigeonInternalCodecSerializer : public ::flutter::StandardCodecSerializer {
 public:
  PigeonInternalCodecSerializer();
  inline static PigeonInternalCodecSerializer& GetInstance() {
    static PigeonInternalCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const ::flutter::EncodableValue& value,
    ::flutter::ByteStreamWriter* stream) const override;
 protected:
  ::flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    ::flutter::ByteStreamReader* stream) const override;
};

// Generated interface from Pigeon that represents a handler of messages from Flutter.
class BiometricSignatureApi {
 public:
  BiometricSignatureApi(const BiometricSignatureApi&) = delete;
  BiometricSignatureApi& operator=(const BiometricSignatureApi&) = delete;
  virtual ~BiometricSignatureApi() {}
  // Checks if biometric authentication is available.
  virtual void BiometricAuthAvailable(std::function<void(ErrorOr<BiometricAvailability> reply)> result) = 0;
  // Creates a new key pair.
  //
  // [keyAlias] is an optional alias for the key. When null, the default
  // alias is used. Different aliases create independent key pairs.
  // [config] contains platform-specific options. See [CreateKeysConfig].
  // [keyFormat] specifies the output format for the public key.
  // [promptMessage] is the message shown to the user during authentication.
  virtual void CreateKeys(
    const std::string* key_alias,
    const CreateKeysConfig* config,
    const KeyFormat& key_format,
    const std::string* prompt_message,
    std::function<void(ErrorOr<KeyCreationResult> reply)> result) = 0;
  // Creates a signature.
  //
  // [payload] is the data to sign.
  // [keyAlias] specifies which key to sign with. Defaults to the default alias.
  // [config] contains platform-specific options. See [CreateSignatureConfig].
  // [signatureFormat] specifies the output format for the signature.
  // [keyFormat] specifies the output format for the public key.
  // [promptMessage] is the message shown to the user during authentication.
  virtual void CreateSignature(
    const std::string& payload,
    const std::string* key_alias,
    const CreateSignatureConfig* config,
    const SignatureFormat& signature_format,
    const KeyFormat& key_format,
    const std::string* prompt_message,
    std::function<void(ErrorOr<SignatureResult> reply)> result) = 0;
  // Decrypts data.
  //
  // Note: Not supported on Windows.
  // [payload] is the encrypted data.
  // [keyAlias] specifies which key to decrypt with. Defaults to the default alias.
  // [payloadFormat] specifies the format of the encrypted data.
  // [config] contains platform-specific options. See [DecryptConfig].
  // [promptMessage] is the message shown to the user during authentication.
  virtual void Decrypt(
    const std::string& payload,
    const std::string* key_alias,
    const PayloadFormat& payload_format,
    const DecryptConfig* config,
    const std::string* prompt_message,
    std::function<void(ErrorOr<DecryptResult> reply)> result) = 0;
  // Deletes keys for a specific alias.
  //
  // [keyAlias] specifies which key to delete. When null, deletes the
  // default alias only. Other aliases are not affected.
  virtual void DeleteKeys(
    const std::string* key_alias,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  // Deletes all biometric keys across all aliases.
  //
  // This is a destructive operation that removes every key managed by
  // this plugin. Use [deleteKeys] for targeted deletion.
  virtual void DeleteAllKeys(std::function<void(ErrorOr<bool> reply)> result) = 0;
  // Gets detailed information about existing biometric keys.
  //
  // [keyAlias] specifies which key to query. Defaults to the default alias.
  // Returns key metadata including algorithm, size, validity, and public keys.
  virtual void GetKeyInfo(
    const std::string* key_alias,
    bool check_validity,
    const KeyFormat& key_format,
    std::function<void(ErrorOr<KeyInfo> reply)> result) = 0;
  // Performs simple biometric authentication without cryptographic operations.
  //
  // This is useful for:
  // - Quick re-authentication flows
  // - Confirming user presence before sensitive operations
  // - Simple access control without key management
  //
  // [promptMessage] is the main message shown to the user (title on Android).
  // [config] contains optional platform-specific configuration.
  //
  // Returns a [SimplePromptResult] indicating success or failure.
  virtual void SimplePrompt(
    const std::string& prompt_message,
    const SimplePromptConfig* config,
    std::function<void(ErrorOr<SimplePromptResult> reply)> result) = 0;
  // Checks whether the device has a screen lock (PIN, pattern, password, or
  // passcode) configured.
  //
  // This is a precondition for biometric enrollment on most platforms:
  // - Android: Uses `KeyguardManager.isDeviceSecure()`
  // - iOS/macOS: Evaluates `LAPolicy.deviceOwnerAuthentication` to detect
  //   `kLAErrorPasscodeNotSet`
  // - Windows: Checks Windows Hello availability via
  //   `KeyCredentialManager.IsSupportedAsync()`
  //
  // Returns `true` if the device has a screen lock configured.
  virtual void IsDeviceLockSet(std::function<void(ErrorOr<bool> reply)> result) = 0;

  // The codec used by BiometricSignatureApi.
  static const ::flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `BiometricSignatureApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    BiometricSignatureApi* api);
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    BiometricSignatureApi* api,
    const std::string& message_channel_suffix);
  static ::flutter::EncodableValue WrapError(std::string_view error_message);
  static ::flutter::EncodableValue WrapError(const FlutterError& error);
 protected:
  BiometricSignatureApi() = default;
};
}  // namespace biometric_signature
#endif  // PIGEON_MESSAGES_G_H_
