// Re-fetches Google's hardware attestation roots and prints a new
// lib/src/attestation/google_roots.dart to stdout.
//
//   dart run tool/update_google_roots.dart > lib/src/attestation/google_roots.dart
//   dart run tool/update_google_roots.dart --from roots.json --fetched-on 2026-09-27
//
// Review the diff: a new root is a trust decision, not a routine update.
// Then run `dart format lib` and `flutter test test/google_roots_test.dart`.

import 'dart:convert';
import 'dart:io';

import 'package:examples_shared/crypto.dart';
import 'package:examples_shared/src/attestation/x509.dart';

const _url = 'https://android.googleapis.com/attestation/root';

Future<void> main(List<String> args) async {
  String? option(String name) {
    final i = args.indexOf(name);
    return i >= 0 && i + 1 < args.length ? args[i + 1] : null;
  }

  final from = option('--from');
  final String body;
  if (from != null) {
    body = File(from).readAsStringSync();
  } else {
    final client = HttpClient();
    try {
      final request = await client.getUrl(Uri.parse(_url));
      final response = await request.close();
      if (response.statusCode != 200) {
        stderr.writeln('HTTP ${response.statusCode} from $_url');
        exitCode = 1;
        return;
      }
      body = await response.transform(utf8.decoder).join();
    } finally {
      client.close();
    }
  }
  final pems = (jsonDecode(body) as List<dynamic>).cast<String>();
  final today = option('--fetched-on') ??
      DateTime.now().toUtc().toIso8601String().substring(0, 10);

  final out = StringBuffer()
    ..writeln('// GENERATED by tool/update_google_roots.dart — do not edit by '
        'hand.')
    ..writeln()
    ..writeln("import 'dart:collection';")
    ..writeln()
    ..writeln('/// Where the roots were fetched from.')
    ..writeln("const String googleRootsSourceUrl = '$_url';")
    ..writeln()
    ..writeln('/// The date (UTC) the roots were fetched.')
    ..writeln("const String googleRootsFetchedOn = '$today';")
    ..writeln()
    ..writeln('/// One Google hardware attestation root.')
    ..writeln('class GoogleAttestationRoot {')
    ..writeln('  /// Creates a root entry.')
    ..writeln('  const GoogleAttestationRoot({')
    ..writeln('    required this.name,')
    ..writeln('    required this.spkiSha256,')
    ..writeln('    required this.pem,')
    ..writeln('  });')
    ..writeln()
    ..writeln('  /// Descriptive name (key type and subject).')
    ..writeln('  final String name;')
    ..writeln()
    ..writeln(
        '  /// SHA-256 of the SubjectPublicKeyInfo, lower-case hex. Chains')
    ..writeln(
        '  /// are trusted by this *key* hash: the RSA root was re-issued')
    ..writeln('  /// with the same key, so matching whole certificates would')
    ..writeln('  /// reject valid older chains.')
    ..writeln('  final String spkiSha256;')
    ..writeln()
    ..writeln('  /// The root certificate as served by Google.')
    ..writeln('  final String pem;')
    ..writeln('}')
    ..writeln()
    ..writeln('/// The roots from [googleRootsSourceUrl].')
    ..writeln('const List<GoogleAttestationRoot> googleAttestationRoots = [');
  for (final pem in pems) {
    final cert = X509Certificate.parse(certificatesFromPem(pem).single);
    final name = '${cert.publicKey.description} root (${cert.subject})';
    out
      ..writeln('  GoogleAttestationRoot(')
      ..writeln("    name: '$name',")
      ..writeln("    spkiSha256: '${toHex(cert.spkiSha256)}',")
      ..writeln("    pem: '''")
      ..writeln(pem.trim())
      ..writeln("''',")
      ..writeln('  ),');
  }
  out
    ..writeln('];')
    ..writeln()
    ..writeln('/// SPKI SHA-256 fingerprints of [googleAttestationRoots]: the '
        'default')
    ..writeln(
        '/// trust anchors of `ChainValidator` and `AttestationVerifier`.')
    ..writeln('final Set<String> googleRootSpkiSha256 = UnmodifiableSetView(')
    ..writeln('  {for (final root in googleAttestationRoots) root.spkiSha256},')
    ..writeln(');');
  stdout.write(out.toString());
}
