// Autogenerated from Pigeon (v25.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.visionflutter.biometric_signature

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object BiometricSignatureApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).containsKey(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * The type of authentication that was used to complete an operation.
 *
 * On Android, this is determined by the platform's `AuthenticationResult.getAuthenticationType()`.
 * On iOS/macOS, this is inferred: [biometric] if device credentials are not allowed,
 * [credential] if no biometric hardware is available, [unknown] otherwise.
 * On Windows, this is always [unknown] as Windows Hello handles auth internally.
 */
enum class AuthenticationType(val raw: Int) {
  /** The user authenticated using device credentials (PIN, pattern, or password). */
  CREDENTIAL(0),
  /** The user authenticated using a biometric (fingerprint, face, iris). */
  BIOMETRIC(1),
  /** The authentication type could not be determined. */
  UNKNOWN(2);

  companion object {
    fun ofRaw(raw: Int): AuthenticationType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Types of biometric authentication supported by the device. */
enum class BiometricType(val raw: Int) {
  /** Face recognition (Face ID on iOS, face unlock on Android). */
  FACE(0),
  /** Fingerprint recognition (Touch ID on iOS/macOS, fingerprint on Android). */
  FINGERPRINT(1),
  /** Iris scanner (Android only, rare on consumer devices). */
  IRIS(2),
  /** Multiple biometric types are available on the device. */
  MULTIPLE(3),
  /** No biometric hardware available or biometrics are disabled. */
  UNAVAILABLE(4);

  companion object {
    fun ofRaw(raw: Int): BiometricType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Biometric authentication strength level.
 *
 * This affects which biometric sensors can be used for authentication.
 * Note: On iOS/macOS, only strong biometrics are available (Face ID, Touch ID, Optic ID).
 * On Windows, Windows Hello always uses strong authentication.
 */
enum class BiometricStrength(val raw: Int) {
  /**
   * Strong biometrics only (e.g., fingerprint, face recognition with depth sensing).
   * This is the most secure option and is required for cryptographic operations.
   */
  STRONG(0),
  /**
   * Weak biometrics allowed (e.g., face recognition without depth sensing).
   * This option provides more device compatibility but lower security.
   */
  WEAK(1);

  companion object {
    fun ofRaw(raw: Int): BiometricStrength? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Standardized error codes for the plugin. */
enum class BiometricError(val raw: Int) {
  /** The operation was successful. */
  SUCCESS(0),
  /** The user canceled the operation. */
  USER_CANCELED(1),
  /** Biometric authentication is not available on this device. */
  NOT_AVAILABLE(2),
  /** No biometrics are enrolled. */
  NOT_ENROLLED(3),
  /** The user is temporarily locked out due to too many failed attempts. */
  LOCKED_OUT(4),
  /** The user is permanently locked out until they log in with a strong method. */
  LOCKED_OUT_PERMANENT(5),
  /** The requested key was not found. */
  KEY_NOT_FOUND(6),
  /** The key has been invalidated (e.g. by new biometric enrollment). */
  KEY_INVALIDATED(7),
  /** An unknown error occurred. */
  UNKNOWN(8),
  /** The input payload was invalid (e.g. not valid Base64). */
  INVALID_INPUT(9),
  /** A security update is required before biometrics can be used. */
  SECURITY_UPDATE_REQUIRED(10),
  /** Biometric authentication is not supported on this device/OS version. */
  NOT_SUPPORTED(11),
  /** The system canceled the operation (e.g., app went to background). */
  SYSTEM_CANCELED(12),
  /** Failed to show the biometric prompt (e.g., activity not available). */
  PROMPT_ERROR(13),
  /** A key with the specified alias already exists and failIfExists was set. */
  KEY_ALREADY_EXISTS(14),
  /**
   * The device does not have a screen lock (PIN, pattern, password, or
   * passcode) configured.
   *
   * A screen lock is a prerequisite for biometric enrollment and for
   * hardware-backed key storage on all platforms:
   * - **iOS/macOS**: Maps from `kLAErrorPasscodeNotSet`. Can surface during
   *   any operation that requires Secure Enclave access (key creation,
   *   signing, decryption, and simple prompt).
   * - **Android**: Maps from `ERROR_NO_DEVICE_CREDENTIAL` (cause code 14).
   *   Only surfaces when `allowDeviceCredentials: true` is set; for
   *   biometric-only flows Android reports [notAvailable] or [notEnrolled]
   *   instead.
   * - **Windows**: Not applicable — Windows Hello manages its own credential
   *   requirements.
   *
   * Use [BiometricSignatureApi.isDeviceLockSet] as a proactive precondition
   * check before attempting operations. This error is the reactive
   * counterpart when the check is skipped or the user removes their screen
   * lock between the check and the operation.
   *
   * **Migration from 11.0.x → 11.1.0**: On Android, `ERROR_NO_DEVICE_CREDENTIAL`
   * (cause code 14) was previously mapped to [notAvailable]. Consumers that
   * were pattern-matching on [notAvailable] to drive a "no screen lock" UX
   * should migrate to [passcodeNotSet]. iOS/macOS mapping of
   * `kLAErrorPasscodeNotSet` changed in the same release.
   */
  PASSCODE_NOT_SET(15);

  companion object {
    fun ofRaw(raw: Int): BiometricError? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** The cryptographic algorithm to use for key generation. */
enum class SignatureType(val raw: Int) {
  /** RSA-2048 (Android: native, iOS/macOS: hybrid mode with Secure Enclave EC). */
  RSA(0),
  /** ECDSA P-256 (hardware-backed on all platforms). */
  ECDSA(1);

  companion object {
    fun ofRaw(raw: Int): SignatureType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Output format for public keys. */
enum class KeyFormat(val raw: Int) {
  /** Base64-encoded DER (SubjectPublicKeyInfo). */
  BASE64(0),
  /** PEM format with BEGIN/END PUBLIC KEY headers. */
  PEM(1),
  /** Hexadecimal-encoded DER. */
  HEX(2),
  /** Raw DER bytes (returned via `publicKeyBytes`). */
  RAW(3);

  companion object {
    fun ofRaw(raw: Int): KeyFormat? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Output format for cryptographic signatures. */
enum class SignatureFormat(val raw: Int) {
  /** Base64-encoded signature bytes. */
  BASE64(0),
  /** Hexadecimal-encoded signature bytes. */
  HEX(1),
  /** Raw signature bytes (returned via `signatureBytes`). */
  RAW(2);

  companion object {
    fun ofRaw(raw: Int): SignatureFormat? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Input format for encrypted payloads to decrypt. */
enum class PayloadFormat(val raw: Int) {
  /** Base64-encoded ciphertext. */
  BASE64(0),
  /** Hexadecimal-encoded ciphertext. */
  HEX(1),
  /** Raw UTF-8 string (not recommended for binary data). */
  RAW(2);

  companion object {
    fun ofRaw(raw: Int): PayloadFormat? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BiometricAvailability (
  val canAuthenticate: Boolean? = null,
  val hasEnrolledBiometrics: Boolean? = null,
  val availableBiometrics: List<BiometricType?>? = null,
  val reason: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BiometricAvailability {
      val canAuthenticate = pigeonVar_list[0] as Boolean?
      val hasEnrolledBiometrics = pigeonVar_list[1] as Boolean?
      val availableBiometrics = pigeonVar_list[2] as List<BiometricType?>?
      val reason = pigeonVar_list[3] as String?
      return BiometricAvailability(canAuthenticate, hasEnrolledBiometrics, availableBiometrics, reason)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      canAuthenticate,
      hasEnrolledBiometrics,
      availableBiometrics,
      reason,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is BiometricAvailability) {
      return false
    }
    if (this === other) {
      return true
    }
    return BiometricSignatureApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class KeyCreationResult (
  val publicKey: String? = null,
  val publicKeyBytes: ByteArray? = null,
  val error: String? = null,
  val code: BiometricError? = null,
  val algorithm: String? = null,
  val keySize: Long? = null,
  val decryptingPublicKey: String? = null,
  val decryptingAlgorithm: String? = null,
  val decryptingKeySize: Long? = null,
  val isHybridMode: Boolean? = null,
  /**
   * The type of authentication used to complete this operation.
   *
   * Inferred on Apple platforms (iOS/macOS), authoritative on Android.
   * See [AuthenticationType] for how inference is performed when the
   * platform does not report the method directly.
   */
  val authenticationType: AuthenticationType? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KeyCreationResult {
      val publicKey = pigeonVar_list[0] as String?
      val publicKeyBytes = pigeonVar_list[1] as ByteArray?
      val error = pigeonVar_list[2] as String?
      val code = pigeonVar_list[3] as BiometricError?
      val algorithm = pigeonVar_list[4] as String?
      val keySize = pigeonVar_list[5] as Long?
      val decryptingPublicKey = pigeonVar_list[6] as String?
      val decryptingAlgorithm = pigeonVar_list[7] as String?
      val decryptingKeySize = pigeonVar_list[8] as Long?
      val isHybridMode = pigeonVar_list[9] as Boolean?
      val authenticationType = pigeonVar_list[10] as AuthenticationType?
      return KeyCreationResult(publicKey, publicKeyBytes, error, code, algorithm, keySize, decryptingPublicKey, decryptingAlgorithm, decryptingKeySize, isHybridMode, authenticationType)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      publicKey,
      publicKeyBytes,
      error,
      code,
      algorithm,
      keySize,
      decryptingPublicKey,
      decryptingAlgorithm,
      decryptingKeySize,
      isHybridMode,
      authenticationType,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is KeyCreationResult) {
      return false
    }
    if (this === other) {
      return true
    }
    return BiometricSignatureApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SignatureResult (
  val signature: String? = null,
  val signatureBytes: ByteArray? = null,
  val publicKey: String? = null,
  val error: String? = null,
  val code: BiometricError? = null,
  val algorithm: String? = null,
  val keySize: Long? = null,
  /**
   * The type of authentication used to complete this operation.
   *
   * Inferred on Apple platforms (iOS/macOS), authoritative on Android.
   * See [AuthenticationType] for how inference is performed when the
   * platform does not report the method directly.
   */
  val authenticationType: AuthenticationType? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SignatureResult {
      val signature = pigeonVar_list[0] as String?
      val signatureBytes = pigeonVar_list[1] as ByteArray?
      val publicKey = pigeonVar_list[2] as String?
      val error = pigeonVar_list[3] as String?
      val code = pigeonVar_list[4] as BiometricError?
      val algorithm = pigeonVar_list[5] as String?
      val keySize = pigeonVar_list[6] as Long?
      val authenticationType = pigeonVar_list[7] as AuthenticationType?
      return SignatureResult(signature, signatureBytes, publicKey, error, code, algorithm, keySize, authenticationType)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      signature,
      signatureBytes,
      publicKey,
      error,
      code,
      algorithm,
      keySize,
      authenticationType,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is SignatureResult) {
      return false
    }
    if (this === other) {
      return true
    }
    return BiometricSignatureApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class DecryptResult (
  val decryptedData: String? = null,
  val error: String? = null,
  val code: BiometricError? = null,
  /**
   * The type of authentication used to complete this operation.
   *
   * Inferred on Apple platforms (iOS/macOS), authoritative on Android.
   * See [AuthenticationType] for how inference is performed when the
   * platform does not report the method directly.
   */
  val authenticationType: AuthenticationType? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DecryptResult {
      val decryptedData = pigeonVar_list[0] as String?
      val error = pigeonVar_list[1] as String?
      val code = pigeonVar_list[2] as BiometricError?
      val authenticationType = pigeonVar_list[3] as AuthenticationType?
      return DecryptResult(decryptedData, error, code, authenticationType)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      decryptedData,
      error,
      code,
      authenticationType,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is DecryptResult) {
      return false
    }
    if (this === other) {
      return true
    }
    return BiometricSignatureApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Detailed information about existing biometric keys.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class KeyInfo (
  /** Whether any biometric key exists on the device. */
  val exists: Boolean? = null,
  /**
   * Whether the key is still valid (not invalidated by biometric changes).
   * Only populated when `checkValidity: true` is passed.
   */
  val isValid: Boolean? = null,
  /** The algorithm of the signing key (e.g., "RSA", "EC"). */
  val algorithm: String? = null,
  /** The key size in bits (e.g., 2048 for RSA, 256 for EC). */
  val keySize: Long? = null,
  /** Whether the key is in hybrid mode (separate signing and decryption keys). */
  val isHybridMode: Boolean? = null,
  /** Signing key public key (formatted according to the requested format). */
  val publicKey: String? = null,
  /** Decryption key public key for hybrid mode. */
  val decryptingPublicKey: String? = null,
  /** Algorithm of the decryption key (hybrid mode only). */
  val decryptingAlgorithm: String? = null,
  /** Key size of the decryption key in bits (hybrid mode only). */
  val decryptingKeySize: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KeyInfo {
      val exists = pigeonVar_list[0] as Boolean?
      val isValid = pigeonVar_list[1] as Boolean?
      val algorithm = pigeonVar_list[2] as String?
      val keySize = pigeonVar_list[3] as Long?
      val isHybridMode = pigeonVar_list[4] as Boolean?
      val publicKey = pigeonVar_list[5] as String?
      val decryptingPublicKey = pigeonVar_list[6] as String?
      val decryptingAlgorithm = pigeonVar_list[7] as String?
      val decryptingKeySize = pigeonVar_list[8] as Long?
      return KeyInfo(exists, isValid, algorithm, keySize, isHybridMode, publicKey, decryptingPublicKey, decryptingAlgorithm, decryptingKeySize)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      exists,
      isValid,
      algorithm,
      keySize,
      isHybridMode,
      publicKey,
      decryptingPublicKey,
      decryptingAlgorithm,
      decryptingKeySize,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is KeyInfo) {
      return false
    }
    if (this === other) {
      return true
    }
    return BiometricSignatureApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Configuration for key creation (all platforms).
 *
 * Fields are documented with which platform(s) they apply to.
 * Windows ignores most fields as it only supports RSA with mandatory
 * Windows Hello authentication.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CreateKeysConfig (
  /**
   * [Android/iOS/macOS] The cryptographic algorithm to use.
   * Windows only supports RSA and ignores this field.
   */
  val signatureType: SignatureType? = null,
  /**
   * [Android/iOS/macOS] Whether to require biometric authentication
   * during key creation. Windows always authenticates via Windows Hello.
   */
  val enforceBiometric: Boolean? = null,
  /**
   * [Android/iOS/macOS] Whether to invalidate the key when new biometrics
   * are enrolled. Not supported on Windows.
   *
   * **Security Note**: When `true`, keys become invalid if fingerprints/faces
   * are added or removed, preventing unauthorized access if an attacker
   * enrolls their own biometrics on a compromised device.
   */
  val setInvalidatedByBiometricEnrollment: Boolean? = null,
  /**
   * [Android/iOS/macOS] Whether to allow device credentials (PIN/pattern/passcode)
   * as fallback for biometric authentication. Not supported on Windows.
   */
  val useDeviceCredentials: Boolean? = null,
  /**
   * [Android] Whether to enable decryption capability for the key.
   * On iOS/macOS, decryption is always available with EC keys.
   */
  val enableDecryption: Boolean? = null,
  /** [Android] Subtitle text for the biometric prompt. */
  val promptSubtitle: String? = null,
  /** [Android] Description text for the biometric prompt. */
  val promptDescription: String? = null,
  /** [Android] Text for the cancel button in the biometric prompt. */
  val cancelButtonText: String? = null,
  /**
   * [All platforms] When `true`, key creation will fail with
   * [BiometricError.keyAlreadyExists] if a key with the specified alias
   * (or the default alias) already exists.
   *
   * When `false` (default), existing keys are silently replaced.
   */
  val failIfExists: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CreateKeysConfig {
      val signatureType = pigeonVar_list[0] as SignatureType?
      val enforceBiometric = pigeonVar_list[1] as Boolean?
      val setInvalidatedByBiometricEnrollment = pigeonVar_list[2] as Boolean?
      val useDeviceCredentials = pigeonVar_list[3] as Boolean?
      val enableDecryption = pigeonVar_list[4] as Boolean?
      val promptSubtitle = pigeonVar_list[5] as String?
      val promptDescription = pigeonVar_list[6] as String?
      val cancelButtonText = pigeonVar_list[7] as String?
      val failIfExists = pigeonVar_list[8] as Boolean?
      return CreateKeysConfig(signatureType, enforceBiometric, setInvalidatedByBiometricEnrollment, useDeviceCredentials, enableDecryption, promptSubtitle, promptDescription, cancelButtonText, failIfExists)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      signatureType,
      enforceBiometric,
      setInvalidatedByBiometricEnrollment,
      useDeviceCredentials,
      enableDecryption,
      promptSubtitle,
      promptDescription,
      cancelButtonText,
      failIfExists,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is CreateKeysConfig) {
      return false
    }
    if (this === other) {
      return true
    }
    return BiometricSignatureApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Configuration for signature creation (all platforms).
 *
 * Fields are documented with which platform(s) they apply to.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CreateSignatureConfig (
  /** [Android] Subtitle text for the biometric prompt. */
  val promptSubtitle: String? = null,
  /** [Android] Description text for the biometric prompt. */
  val promptDescription: String? = null,
  /** [Android] Text for the cancel button in the biometric prompt. */
  val cancelButtonText: String? = null,
  /** [Android] Whether to allow device credentials (PIN/pattern) as fallback. */
  val allowDeviceCredentials: Boolean? = null,
  /** [iOS] Whether to migrate from legacy keychain storage. */
  val shouldMigrate: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CreateSignatureConfig {
      val promptSubtitle = pigeonVar_list[0] as String?
      val promptDescription = pigeonVar_list[1] as String?
      val cancelButtonText = pigeonVar_list[2] as String?
      val allowDeviceCredentials = pigeonVar_list[3] as Boolean?
      val shouldMigrate = pigeonVar_list[4] as Boolean?
      return CreateSignatureConfig(promptSubtitle, promptDescription, cancelButtonText, allowDeviceCredentials, shouldMigrate)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      promptSubtitle,
      promptDescription,
      cancelButtonText,
      allowDeviceCredentials,
      shouldMigrate,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is CreateSignatureConfig) {
      return false
    }
    if (this === other) {
      return true
    }
    return BiometricSignatureApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Configuration for decryption (all platforms).
 *
 * Fields are documented with which platform(s) they apply to.
 * Note: Decryption is not supported on Windows.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class DecryptConfig (
  /** [Android] Subtitle text for the biometric prompt. */
  val promptSubtitle: String? = null,
  /** [Android] Description text for the biometric prompt. */
  val promptDescription: String? = null,
  /** [Android] Text for the cancel button in the biometric prompt. */
  val cancelButtonText: String? = null,
  /** [Android] Whether to allow device credentials (PIN/pattern) as fallback. */
  val allowDeviceCredentials: Boolean? = null,
  /** [iOS] Whether to migrate from legacy keychain storage. */
  val shouldMigrate: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DecryptConfig {
      val promptSubtitle = pigeonVar_list[0] as String?
      val promptDescription = pigeonVar_list[1] as String?
      val cancelButtonText = pigeonVar_list[2] as String?
      val allowDeviceCredentials = pigeonVar_list[3] as Boolean?
      val shouldMigrate = pigeonVar_list[4] as Boolean?
      return DecryptConfig(promptSubtitle, promptDescription, cancelButtonText, allowDeviceCredentials, shouldMigrate)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      promptSubtitle,
      promptDescription,
      cancelButtonText,
      allowDeviceCredentials,
      shouldMigrate,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is DecryptConfig) {
      return false
    }
    if (this === other) {
      return true
    }
    return BiometricSignatureApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Configuration for simple biometric prompt (authentication without crypto ops).
 *
 * This allows customization of the biometric prompt across platforms.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class SimplePromptConfig (
  /** [Android] Subtitle text displayed below the title in the biometric prompt. */
  val subtitle: String? = null,
  /** [Android] Description text displayed in the biometric prompt body. */
  val description: String? = null,
  /**
   * [Android] Text for the cancel/negative button.
   * Default: "Cancel" on Android, system default on iOS/macOS.
   */
  val cancelButtonText: String? = null,
  /**
   * [Android/iOS/macOS] Whether to allow device credentials (PIN/pattern/passcode)
   * as a fallback for biometric authentication.
   *
   * When true:
   * - Android: Shows "Use PIN" option after biometric failure
   * - iOS/macOS: Uses .deviceOwnerAuthentication policy
   * - Windows: Not applicable (Windows Hello handles fallback internally)
   *
   * Default: false (biometric-only authentication)
   */
  val allowDeviceCredentials: Boolean? = null,
  /**
   * [Android] The required biometric strength level.
   *
   * - strong: Only Class 3 biometrics (e.g., fingerprint, in-screen fingerprint)
   * - weak: Class 2 biometrics allowed (e.g., face unlock without depth)
   *
   * Note: iOS/macOS always use strong biometrics. Windows Hello also uses strong.
   * If strong biometrics are not available but weak are, and strength is set to
   * strong, authentication will fail with [BiometricError.notEnrolled].
   *
   * Default: strong
   */
  val biometricStrength: BiometricStrength? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SimplePromptConfig {
      val subtitle = pigeonVar_list[0] as String?
      val description = pigeonVar_list[1] as String?
      val cancelButtonText = pigeonVar_list[2] as String?
      val allowDeviceCredentials = pigeonVar_list[3] as Boolean?
      val biometricStrength = pigeonVar_list[4] as BiometricStrength?
      return SimplePromptConfig(subtitle, description, cancelButtonText, allowDeviceCredentials, biometricStrength)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      subtitle,
      description,
      cancelButtonText,
      allowDeviceCredentials,
      biometricStrength,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is SimplePromptConfig) {
      return false
    }
    if (this === other) {
      return true
    }
    return BiometricSignatureApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Result from simple biometric prompt authentication.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class SimplePromptResult (
  /** Whether authentication was successful. */
  val success: Boolean? = null,
  /**
   * Error message if authentication failed.
   * This is a human-readable description of what went wrong.
   */
  val error: String? = null,
  /**
   * Standardized error code if authentication failed.
   * Use this for programmatic error handling.
   */
  val code: BiometricError? = null,
  /**
   * The type of authentication used to complete this operation.
   *
   * Inferred on Apple platforms (iOS/macOS), authoritative on Android.
   * See [AuthenticationType] for how inference is performed when the
   * platform does not report the method directly.
   */
  val authenticationType: AuthenticationType? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SimplePromptResult {
      val success = pigeonVar_list[0] as Boolean?
      val error = pigeonVar_list[1] as String?
      val code = pigeonVar_list[2] as BiometricError?
      val authenticationType = pigeonVar_list[3] as AuthenticationType?
      return SimplePromptResult(success, error, code, authenticationType)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      success,
      error,
      code,
      authenticationType,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is SimplePromptResult) {
      return false
    }
    if (this === other) {
      return true
    }
    return BiometricSignatureApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class BiometricSignatureApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          AuthenticationType.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          BiometricType.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          BiometricStrength.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          BiometricError.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          SignatureType.ofRaw(it.toInt())
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          KeyFormat.ofRaw(it.toInt())
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          SignatureFormat.ofRaw(it.toInt())
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PayloadFormat.ofRaw(it.toInt())
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BiometricAvailability.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KeyCreationResult.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SignatureResult.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DecryptResult.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KeyInfo.fromList(it)
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CreateKeysConfig.fromList(it)
        }
      }
      143.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CreateSignatureConfig.fromList(it)
        }
      }
      144.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DecryptConfig.fromList(it)
        }
      }
      145.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SimplePromptConfig.fromList(it)
        }
      }
      146.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SimplePromptResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is AuthenticationType -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is BiometricType -> {
        stream.write(130)
        writeValue(stream, value.raw)
      }
      is BiometricStrength -> {
        stream.write(131)
        writeValue(stream, value.raw)
      }
      is BiometricError -> {
        stream.write(132)
        writeValue(stream, value.raw)
      }
      is SignatureType -> {
        stream.write(133)
        writeValue(stream, value.raw)
      }
      is KeyFormat -> {
        stream.write(134)
        writeValue(stream, value.raw)
      }
      is SignatureFormat -> {
        stream.write(135)
        writeValue(stream, value.raw)
      }
      is PayloadFormat -> {
        stream.write(136)
        writeValue(stream, value.raw)
      }
      is BiometricAvailability -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is KeyCreationResult -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is SignatureResult -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is DecryptResult -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is KeyInfo -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      is CreateKeysConfig -> {
        stream.write(142)
        writeValue(stream, value.toList())
      }
      is CreateSignatureConfig -> {
        stream.write(143)
        writeValue(stream, value.toList())
      }
      is DecryptConfig -> {
        stream.write(144)
        writeValue(stream, value.toList())
      }
      is SimplePromptConfig -> {
        stream.write(145)
        writeValue(stream, value.toList())
      }
      is SimplePromptResult -> {
        stream.write(146)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface BiometricSignatureApi {
  /** Checks if biometric authentication is available. */
  fun biometricAuthAvailable(callback: (Result<BiometricAvailability>) -> Unit)
  /**
   * Creates a new key pair.
   *
   * [keyAlias] is an optional alias for the key. When null, the default
   * alias is used. Different aliases create independent key pairs.
   * [config] contains platform-specific options. See [CreateKeysConfig].
   * [keyFormat] specifies the output format for the public key.
   * [promptMessage] is the message shown to the user during authentication.
   */
  fun createKeys(keyAlias: String?, config: CreateKeysConfig?, keyFormat: KeyFormat, promptMessage: String?, callback: (Result<KeyCreationResult>) -> Unit)
  /**
   * Creates a signature.
   *
   * [payload] is the data to sign.
   * [keyAlias] specifies which key to sign with. Defaults to the default alias.
   * [config] contains platform-specific options. See [CreateSignatureConfig].
   * [signatureFormat] specifies the output format for the signature.
   * [keyFormat] specifies the output format for the public key.
   * [promptMessage] is the message shown to the user during authentication.
   */
  fun createSignature(payload: String, keyAlias: String?, config: CreateSignatureConfig?, signatureFormat: SignatureFormat, keyFormat: KeyFormat, promptMessage: String?, callback: (Result<SignatureResult>) -> Unit)
  /**
   * Decrypts data.
   *
   * Note: Not supported on Windows.
   * [payload] is the encrypted data.
   * [keyAlias] specifies which key to decrypt with. Defaults to the default alias.
   * [payloadFormat] specifies the format of the encrypted data.
   * [config] contains platform-specific options. See [DecryptConfig].
   * [promptMessage] is the message shown to the user during authentication.
   */
  fun decrypt(payload: String, keyAlias: String?, payloadFormat: PayloadFormat, config: DecryptConfig?, promptMessage: String?, callback: (Result<DecryptResult>) -> Unit)
  /**
   * Deletes keys for a specific alias.
   *
   * [keyAlias] specifies which key to delete. When null, deletes the
   * default alias only. Other aliases are not affected.
   */
  fun deleteKeys(keyAlias: String?, callback: (Result<Boolean>) -> Unit)
  /**
   * Deletes all biometric keys across all aliases.
   *
   * This is a destructive operation that removes every key managed by
   * this plugin. Use [deleteKeys] for targeted deletion.
   */
  fun deleteAllKeys(callback: (Result<Boolean>) -> Unit)
  /**
   * Gets detailed information about existing biometric keys.
   *
   * [keyAlias] specifies which key to query. Defaults to the default alias.
   * Returns key metadata including algorithm, size, validity, and public keys.
   */
  fun getKeyInfo(keyAlias: String?, checkValidity: Boolean, keyFormat: KeyFormat, callback: (Result<KeyInfo>) -> Unit)
  /**
   * Performs simple biometric authentication without cryptographic operations.
   *
   * This is useful for:
   * - Quick re-authentication flows
   * - Confirming user presence before sensitive operations
   * - Simple access control without key management
   *
   * [promptMessage] is the main message shown to the user (title on Android).
   * [config] contains optional platform-specific configuration.
   *
   * Returns a [SimplePromptResult] indicating success or failure.
   */
  fun simplePrompt(promptMessage: String, config: SimplePromptConfig?, callback: (Result<SimplePromptResult>) -> Unit)
  /**
   * Checks whether the device has a screen lock (PIN, pattern, password, or
   * passcode) configured.
   *
   * This is a precondition for biometric enrollment on most platforms, but
   * the precise meaning of `true` varies per platform:
   *
   * - **Android**: Authoritative. Uses `KeyguardManager.isDeviceSecure()`
   *   and reports exactly whether a lock credential is enrolled.
   * - **iOS/macOS**: Evaluates `LAPolicy.deviceOwnerAuthentication` and
   *   maps `kLAErrorPasscodeNotSet` to `false`. Any other failure to
   *   evaluate the policy (e.g. on unusual or very old devices) is treated
   *   as `true` to avoid false negatives. Therefore `true` means
   *   "lock is set **or** indeterminate". If you need a stronger guarantee,
   *   rely on the reactive [BiometricError.passcodeNotSet] surfaced during
   *   the next operation.
   * - **Windows**: Reports **Windows Hello availability**, not generic
   *   screen-lock state. Uses
   *   `KeyCredentialManager.IsSupportedAsync()`, which requires a Windows
   *   Hello PIN to be provisioned. Password-only local accounts will get
   *   `false` here even though a screen lock is set. Treat the Windows
   *   return value as "can this device use Windows Hello for biometric
   *   operations?" rather than a direct equivalent of the Android check.
   *
   * Returns `true` if the device has a screen lock configured (or the
   * platform-specific equivalent described above).
   */
  fun isDeviceLockSet(callback: (Result<Boolean>) -> Unit)

  companion object {
    /** The codec used by BiometricSignatureApi. */
    val codec: MessageCodec<Any?> by lazy {
      BiometricSignatureApiPigeonCodec()
    }
    /** Sets up an instance of `BiometricSignatureApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: BiometricSignatureApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.biometricAuthAvailable$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.biometricAuthAvailable{ result: Result<BiometricAvailability> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(BiometricSignatureApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(BiometricSignatureApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.createKeys$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyAliasArg = args[0] as String?
            val configArg = args[1] as CreateKeysConfig?
            val keyFormatArg = args[2] as KeyFormat
            val promptMessageArg = args[3] as String?
            api.createKeys(keyAliasArg, configArg, keyFormatArg, promptMessageArg) { result: Result<KeyCreationResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(BiometricSignatureApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(BiometricSignatureApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.createSignature$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val payloadArg = args[0] as String
            val keyAliasArg = args[1] as String?
            val configArg = args[2] as CreateSignatureConfig?
            val signatureFormatArg = args[3] as SignatureFormat
            val keyFormatArg = args[4] as KeyFormat
            val promptMessageArg = args[5] as String?
            api.createSignature(payloadArg, keyAliasArg, configArg, signatureFormatArg, keyFormatArg, promptMessageArg) { result: Result<SignatureResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(BiometricSignatureApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(BiometricSignatureApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.decrypt$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val payloadArg = args[0] as String
            val keyAliasArg = args[1] as String?
            val payloadFormatArg = args[2] as PayloadFormat
            val configArg = args[3] as DecryptConfig?
            val promptMessageArg = args[4] as String?
            api.decrypt(payloadArg, keyAliasArg, payloadFormatArg, configArg, promptMessageArg) { result: Result<DecryptResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(BiometricSignatureApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(BiometricSignatureApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.deleteKeys$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyAliasArg = args[0] as String?
            api.deleteKeys(keyAliasArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(BiometricSignatureApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(BiometricSignatureApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.deleteAllKeys$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.deleteAllKeys{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(BiometricSignatureApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(BiometricSignatureApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.getKeyInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyAliasArg = args[0] as String?
            val checkValidityArg = args[1] as Boolean
            val keyFormatArg = args[2] as KeyFormat
            api.getKeyInfo(keyAliasArg, checkValidityArg, keyFormatArg) { result: Result<KeyInfo> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(BiometricSignatureApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(BiometricSignatureApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.simplePrompt$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val promptMessageArg = args[0] as String
            val configArg = args[1] as SimplePromptConfig?
            api.simplePrompt(promptMessageArg, configArg) { result: Result<SimplePromptResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(BiometricSignatureApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(BiometricSignatureApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.isDeviceLockSet$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.isDeviceLockSet{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(BiometricSignatureApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(BiometricSignatureApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
