// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.visionflutter.biometric_signature

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object BiometricSignatureApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * The type of authentication that was used to complete an operation.
 *
 * On Android, this is determined by the platform's `AuthenticationResult.getAuthenticationType()`.
 * On iOS/macOS, this is inferred: [biometric] if device credentials are not allowed,
 * [credential] if no biometric hardware is available, [unknown] otherwise.
 * On Windows, this is always [unknown] as Windows Hello handles auth internally.
 */
enum class AuthenticationType(val raw: Int) {
  /** The user authenticated using device credentials (PIN, pattern, or password). */
  CREDENTIAL(0),
  /** The user authenticated using a biometric (fingerprint, face, iris). */
  BIOMETRIC(1),
  /** The authentication type could not be determined. */
  UNKNOWN(2);

  companion object {
    fun ofRaw(raw: Int): AuthenticationType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Types of biometric authentication supported by the device. */
enum class BiometricType(val raw: Int) {
  /** Face recognition (Face ID on iOS, face unlock on Android). */
  FACE(0),
  /** Fingerprint recognition (Touch ID on iOS/macOS, fingerprint on Android). */
  FINGERPRINT(1),
  /** Iris scanner (Android only, rare on consumer devices). */
  IRIS(2),
  /** Multiple biometric types are available on the device. */
  MULTIPLE(3),
  /** No biometric hardware available or biometrics are disabled. */
  UNAVAILABLE(4);

  companion object {
    fun ofRaw(raw: Int): BiometricType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Biometric authentication strength level.
 *
 * This affects which biometric sensors can be used for authentication.
 * Note: On iOS/macOS, only strong biometrics are available (Face ID, Touch ID, Optic ID).
 * On Windows, Windows Hello always uses strong authentication.
 */
enum class BiometricStrength(val raw: Int) {
  /**
   * Strong biometrics only (e.g., fingerprint, face recognition with depth sensing).
   * This is the most secure option and is required for cryptographic operations.
   */
  STRONG(0),
  /**
   * Weak biometrics allowed (e.g., face recognition without depth sensing).
   * This option provides more device compatibility but lower security.
   */
  WEAK(1);

  companion object {
    fun ofRaw(raw: Int): BiometricStrength? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Standardized error codes for the plugin. */
enum class BiometricError(val raw: Int) {
  /** The operation was successful. */
  SUCCESS(0),
  /** The user canceled the operation. */
  USER_CANCELED(1),
  /** Biometric authentication is not available on this device. */
  NOT_AVAILABLE(2),
  /** No biometrics are enrolled. */
  NOT_ENROLLED(3),
  /** The user is temporarily locked out due to too many failed attempts. */
  LOCKED_OUT(4),
  /** The user is permanently locked out until they log in with a strong method. */
  LOCKED_OUT_PERMANENT(5),
  /** The requested key was not found. */
  KEY_NOT_FOUND(6),
  /** The key has been invalidated (e.g. by new biometric enrollment). */
  KEY_INVALIDATED(7),
  /** An unknown error occurred. */
  UNKNOWN(8),
  /** The input payload was invalid (e.g. not valid Base64). */
  INVALID_INPUT(9),
  /** A security update is required before biometrics can be used. */
  SECURITY_UPDATE_REQUIRED(10),
  /** Biometric authentication is not supported on this device/OS version. */
  NOT_SUPPORTED(11),
  /** The system canceled the operation (e.g., app went to background). */
  SYSTEM_CANCELED(12),
  /** Failed to show the biometric prompt (e.g., activity not available). */
  PROMPT_ERROR(13),
  /** A key with the specified alias already exists and failIfExists was set. */
  KEY_ALREADY_EXISTS(14),
  /**
   * The user selected a custom fallback option instead of authenticating.
   * [Android 15+ only] Check `selectedFallbackIndex` and `selectedFallbackText`
   * on the result object to determine which option was selected.
   */
  FALLBACK_SELECTED(15),
  /**
   * The device does not have a screen lock (PIN, pattern, password, or
   * passcode) configured.
   *
   * A screen lock is a prerequisite for biometric enrollment and for
   * hardware-backed key storage on all platforms:
   * - **iOS/macOS**: Maps from `kLAErrorPasscodeNotSet`. Can surface during
   *   any operation that requires Secure Enclave access (key creation,
   *   signing, decryption, and simple prompt).
   * - **Android**: Maps from `ERROR_NO_DEVICE_CREDENTIAL` (cause code 14).
   *   Only surfaces when `allowDeviceCredentials: true` is set; for
   *   biometric-only flows Android reports [notAvailable] or [notEnrolled]
   *   instead.
   * - **Windows**: Not applicable — Windows Hello manages its own credential
   *   requirements.
   *
   * Use [BiometricSignatureApi.isDeviceLockSet] as a proactive precondition
   * check before attempting operations. This error is the reactive
   * counterpart when the check is skipped or the user removes their screen
   * lock between the check and the operation.
   */
  PASSCODE_NOT_SET(16);

  companion object {
    fun ofRaw(raw: Int): BiometricError? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** The cryptographic algorithm to use for key generation. */
enum class SignatureType(val raw: Int) {
  /** RSA-2048 (Android: native, iOS/macOS: hybrid mode with Secure Enclave EC). */
  RSA(0),
  /** ECDSA P-256 (hardware-backed on all platforms). */
  ECDSA(1);

  companion object {
    fun ofRaw(raw: Int): SignatureType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Output format for public keys. */
enum class KeyFormat(val raw: Int) {
  /** Base64-encoded DER (SubjectPublicKeyInfo). */
  BASE64(0),
  /** PEM format with BEGIN/END PUBLIC KEY headers. */
  PEM(1),
  /** Hexadecimal-encoded DER. */
  HEX(2),
  /** Raw DER bytes (returned via `publicKeyBytes`). */
  RAW(3);

  companion object {
    fun ofRaw(raw: Int): KeyFormat? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Output format for cryptographic signatures. */
enum class SignatureFormat(val raw: Int) {
  /** Base64-encoded signature bytes. */
  BASE64(0),
  /** Hexadecimal-encoded signature bytes. */
  HEX(1),
  /** Raw signature bytes (returned via `signatureBytes`). */
  RAW(2);

  companion object {
    fun ofRaw(raw: Int): SignatureFormat? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Input format for encrypted payloads to decrypt. */
enum class PayloadFormat(val raw: Int) {
  /** Base64-encoded ciphertext. */
  BASE64(0),
  /** Hexadecimal-encoded ciphertext. */
  HEX(1),
  /** Raw UTF-8 string (not recommended for binary data). */
  RAW(2);

  companion object {
    fun ofRaw(raw: Int): PayloadFormat? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * A custom fallback option shown on the biometric prompt.
 *
 * [Android 15+ only] When provided in a config's `fallbackOptions` list,
 * these appear as alternative buttons on the biometric prompt dialog.
 * If the user taps one, the result will have code [BiometricError.fallbackSelected]
 * with the selected option's index and text.
 *
 * On iOS, macOS, and Windows this class is ignored.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class BiometricFallbackOption (
  /** The text label displayed on the fallback button. */
  val text: String? = null,
  /**
   * [Android] Optional icon type name for the fallback button.
   * Valid values: `"password"`, `"qr_code"`, `"account"`, `"generic"`.
   * Maps to `AuthenticationRequest.Biometric.Fallback.ICON_TYPE_*` constants.
   * When null, defaults to `"generic"`.
   */
  val iconName: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BiometricFallbackOption {
      val text = pigeonVar_list[0] as String?
      val iconName = pigeonVar_list[1] as String?
      return BiometricFallbackOption(text, iconName)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      text,
      iconName,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BiometricFallbackOption
    return BiometricSignatureApiPigeonUtils.deepEquals(this.text, other.text) && BiometricSignatureApiPigeonUtils.deepEquals(this.iconName, other.iconName)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.text)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.iconName)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BiometricAvailability (
  val canAuthenticate: Boolean? = null,
  val hasEnrolledBiometrics: Boolean? = null,
  val availableBiometrics: List<BiometricType?>? = null,
  val reason: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BiometricAvailability {
      val canAuthenticate = pigeonVar_list[0] as Boolean?
      val hasEnrolledBiometrics = pigeonVar_list[1] as Boolean?
      val availableBiometrics = pigeonVar_list[2] as List<BiometricType?>?
      val reason = pigeonVar_list[3] as String?
      return BiometricAvailability(canAuthenticate, hasEnrolledBiometrics, availableBiometrics, reason)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      canAuthenticate,
      hasEnrolledBiometrics,
      availableBiometrics,
      reason,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BiometricAvailability
    return BiometricSignatureApiPigeonUtils.deepEquals(this.canAuthenticate, other.canAuthenticate) && BiometricSignatureApiPigeonUtils.deepEquals(this.hasEnrolledBiometrics, other.hasEnrolledBiometrics) && BiometricSignatureApiPigeonUtils.deepEquals(this.availableBiometrics, other.availableBiometrics) && BiometricSignatureApiPigeonUtils.deepEquals(this.reason, other.reason)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.canAuthenticate)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.hasEnrolledBiometrics)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.availableBiometrics)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.reason)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class KeyCreationResult (
  val publicKey: String? = null,
  val publicKeyBytes: ByteArray? = null,
  val error: String? = null,
  val code: BiometricError? = null,
  val algorithm: String? = null,
  val keySize: Long? = null,
  val decryptingPublicKey: String? = null,
  val decryptingAlgorithm: String? = null,
  val decryptingKeySize: Long? = null,
  val isHybridMode: Boolean? = null,
  /** The type of authentication used to complete this operation. */
  val authenticationType: AuthenticationType? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KeyCreationResult {
      val publicKey = pigeonVar_list[0] as String?
      val publicKeyBytes = pigeonVar_list[1] as ByteArray?
      val error = pigeonVar_list[2] as String?
      val code = pigeonVar_list[3] as BiometricError?
      val algorithm = pigeonVar_list[4] as String?
      val keySize = pigeonVar_list[5] as Long?
      val decryptingPublicKey = pigeonVar_list[6] as String?
      val decryptingAlgorithm = pigeonVar_list[7] as String?
      val decryptingKeySize = pigeonVar_list[8] as Long?
      val isHybridMode = pigeonVar_list[9] as Boolean?
      val authenticationType = pigeonVar_list[10] as AuthenticationType?
      return KeyCreationResult(publicKey, publicKeyBytes, error, code, algorithm, keySize, decryptingPublicKey, decryptingAlgorithm, decryptingKeySize, isHybridMode, authenticationType)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      publicKey,
      publicKeyBytes,
      error,
      code,
      algorithm,
      keySize,
      decryptingPublicKey,
      decryptingAlgorithm,
      decryptingKeySize,
      isHybridMode,
      authenticationType,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as KeyCreationResult
    return BiometricSignatureApiPigeonUtils.deepEquals(this.publicKey, other.publicKey) && BiometricSignatureApiPigeonUtils.deepEquals(this.publicKeyBytes, other.publicKeyBytes) && BiometricSignatureApiPigeonUtils.deepEquals(this.error, other.error) && BiometricSignatureApiPigeonUtils.deepEquals(this.code, other.code) && BiometricSignatureApiPigeonUtils.deepEquals(this.algorithm, other.algorithm) && BiometricSignatureApiPigeonUtils.deepEquals(this.keySize, other.keySize) && BiometricSignatureApiPigeonUtils.deepEquals(this.decryptingPublicKey, other.decryptingPublicKey) && BiometricSignatureApiPigeonUtils.deepEquals(this.decryptingAlgorithm, other.decryptingAlgorithm) && BiometricSignatureApiPigeonUtils.deepEquals(this.decryptingKeySize, other.decryptingKeySize) && BiometricSignatureApiPigeonUtils.deepEquals(this.isHybridMode, other.isHybridMode) && BiometricSignatureApiPigeonUtils.deepEquals(this.authenticationType, other.authenticationType)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.publicKey)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.publicKeyBytes)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.error)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.code)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.algorithm)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.keySize)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.decryptingPublicKey)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.decryptingAlgorithm)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.decryptingKeySize)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.isHybridMode)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.authenticationType)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SignatureResult (
  val signature: String? = null,
  val signatureBytes: ByteArray? = null,
  val publicKey: String? = null,
  val error: String? = null,
  val code: BiometricError? = null,
  val algorithm: String? = null,
  val keySize: Long? = null,
  /**
   * [Android 15+] Index of the selected fallback option in the original list.
   * Only populated when `code == BiometricError.fallbackSelected`.
   */
  val selectedFallbackIndex: Long? = null,
  /**
   * [Android 15+] Text of the selected fallback option.
   * Only populated when `code == BiometricError.fallbackSelected`.
   */
  val selectedFallbackText: String? = null,
  /** The type of authentication used to complete this operation. */
  val authenticationType: AuthenticationType? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SignatureResult {
      val signature = pigeonVar_list[0] as String?
      val signatureBytes = pigeonVar_list[1] as ByteArray?
      val publicKey = pigeonVar_list[2] as String?
      val error = pigeonVar_list[3] as String?
      val code = pigeonVar_list[4] as BiometricError?
      val algorithm = pigeonVar_list[5] as String?
      val keySize = pigeonVar_list[6] as Long?
      val selectedFallbackIndex = pigeonVar_list[7] as Long?
      val selectedFallbackText = pigeonVar_list[8] as String?
      val authenticationType = pigeonVar_list[9] as AuthenticationType?
      return SignatureResult(signature, signatureBytes, publicKey, error, code, algorithm, keySize, selectedFallbackIndex, selectedFallbackText, authenticationType)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      signature,
      signatureBytes,
      publicKey,
      error,
      code,
      algorithm,
      keySize,
      selectedFallbackIndex,
      selectedFallbackText,
      authenticationType,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as SignatureResult
    return BiometricSignatureApiPigeonUtils.deepEquals(this.signature, other.signature) && BiometricSignatureApiPigeonUtils.deepEquals(this.signatureBytes, other.signatureBytes) && BiometricSignatureApiPigeonUtils.deepEquals(this.publicKey, other.publicKey) && BiometricSignatureApiPigeonUtils.deepEquals(this.error, other.error) && BiometricSignatureApiPigeonUtils.deepEquals(this.code, other.code) && BiometricSignatureApiPigeonUtils.deepEquals(this.algorithm, other.algorithm) && BiometricSignatureApiPigeonUtils.deepEquals(this.keySize, other.keySize) && BiometricSignatureApiPigeonUtils.deepEquals(this.selectedFallbackIndex, other.selectedFallbackIndex) && BiometricSignatureApiPigeonUtils.deepEquals(this.selectedFallbackText, other.selectedFallbackText) && BiometricSignatureApiPigeonUtils.deepEquals(this.authenticationType, other.authenticationType)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.signature)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.signatureBytes)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.publicKey)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.error)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.code)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.algorithm)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.keySize)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.selectedFallbackIndex)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.selectedFallbackText)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.authenticationType)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class DecryptResult (
  val decryptedData: String? = null,
  val error: String? = null,
  val code: BiometricError? = null,
  /**
   * [Android 15+] Index of the selected fallback option in the original list.
   * Only populated when `code == BiometricError.fallbackSelected`.
   */
  val selectedFallbackIndex: Long? = null,
  /**
   * [Android 15+] Text of the selected fallback option.
   * Only populated when `code == BiometricError.fallbackSelected`.
   */
  val selectedFallbackText: String? = null,
  /** The type of authentication used to complete this operation. */
  val authenticationType: AuthenticationType? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DecryptResult {
      val decryptedData = pigeonVar_list[0] as String?
      val error = pigeonVar_list[1] as String?
      val code = pigeonVar_list[2] as BiometricError?
      val selectedFallbackIndex = pigeonVar_list[3] as Long?
      val selectedFallbackText = pigeonVar_list[4] as String?
      val authenticationType = pigeonVar_list[5] as AuthenticationType?
      return DecryptResult(decryptedData, error, code, selectedFallbackIndex, selectedFallbackText, authenticationType)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      decryptedData,
      error,
      code,
      selectedFallbackIndex,
      selectedFallbackText,
      authenticationType,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as DecryptResult
    return BiometricSignatureApiPigeonUtils.deepEquals(this.decryptedData, other.decryptedData) && BiometricSignatureApiPigeonUtils.deepEquals(this.error, other.error) && BiometricSignatureApiPigeonUtils.deepEquals(this.code, other.code) && BiometricSignatureApiPigeonUtils.deepEquals(this.selectedFallbackIndex, other.selectedFallbackIndex) && BiometricSignatureApiPigeonUtils.deepEquals(this.selectedFallbackText, other.selectedFallbackText) && BiometricSignatureApiPigeonUtils.deepEquals(this.authenticationType, other.authenticationType)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.decryptedData)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.error)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.code)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.selectedFallbackIndex)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.selectedFallbackText)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.authenticationType)
    return result
  }
}

/**
 * Detailed information about existing biometric keys.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class KeyInfo (
  /** Whether any biometric key exists on the device. */
  val exists: Boolean? = null,
  /**
   * Whether the key is still valid (not invalidated by biometric changes).
   * Only populated when `checkValidity: true` is passed.
   */
  val isValid: Boolean? = null,
  /** The algorithm of the signing key (e.g., "RSA", "EC"). */
  val algorithm: String? = null,
  /** The key size in bits (e.g., 2048 for RSA, 256 for EC). */
  val keySize: Long? = null,
  /** Whether the key is in hybrid mode (separate signing and decryption keys). */
  val isHybridMode: Boolean? = null,
  /** Signing key public key (formatted according to the requested format). */
  val publicKey: String? = null,
  /** Decryption key public key for hybrid mode. */
  val decryptingPublicKey: String? = null,
  /** Algorithm of the decryption key (hybrid mode only). */
  val decryptingAlgorithm: String? = null,
  /** Key size of the decryption key in bits (hybrid mode only). */
  val decryptingKeySize: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KeyInfo {
      val exists = pigeonVar_list[0] as Boolean?
      val isValid = pigeonVar_list[1] as Boolean?
      val algorithm = pigeonVar_list[2] as String?
      val keySize = pigeonVar_list[3] as Long?
      val isHybridMode = pigeonVar_list[4] as Boolean?
      val publicKey = pigeonVar_list[5] as String?
      val decryptingPublicKey = pigeonVar_list[6] as String?
      val decryptingAlgorithm = pigeonVar_list[7] as String?
      val decryptingKeySize = pigeonVar_list[8] as Long?
      return KeyInfo(exists, isValid, algorithm, keySize, isHybridMode, publicKey, decryptingPublicKey, decryptingAlgorithm, decryptingKeySize)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      exists,
      isValid,
      algorithm,
      keySize,
      isHybridMode,
      publicKey,
      decryptingPublicKey,
      decryptingAlgorithm,
      decryptingKeySize,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as KeyInfo
    return BiometricSignatureApiPigeonUtils.deepEquals(this.exists, other.exists) && BiometricSignatureApiPigeonUtils.deepEquals(this.isValid, other.isValid) && BiometricSignatureApiPigeonUtils.deepEquals(this.algorithm, other.algorithm) && BiometricSignatureApiPigeonUtils.deepEquals(this.keySize, other.keySize) && BiometricSignatureApiPigeonUtils.deepEquals(this.isHybridMode, other.isHybridMode) && BiometricSignatureApiPigeonUtils.deepEquals(this.publicKey, other.publicKey) && BiometricSignatureApiPigeonUtils.deepEquals(this.decryptingPublicKey, other.decryptingPublicKey) && BiometricSignatureApiPigeonUtils.deepEquals(this.decryptingAlgorithm, other.decryptingAlgorithm) && BiometricSignatureApiPigeonUtils.deepEquals(this.decryptingKeySize, other.decryptingKeySize)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.exists)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.isValid)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.algorithm)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.keySize)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.isHybridMode)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.publicKey)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.decryptingPublicKey)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.decryptingAlgorithm)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.decryptingKeySize)
    return result
  }
}

/**
 * Configuration for key creation (all platforms).
 *
 * Fields are documented with which platform(s) they apply to.
 * Windows ignores most fields as it only supports RSA with mandatory
 * Windows Hello authentication.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CreateKeysConfig (
  /**
   * [Android/iOS/macOS] The cryptographic algorithm to use.
   * Windows only supports RSA and ignores this field.
   */
  val signatureType: SignatureType? = null,
  /**
   * [Android/iOS/macOS] Whether to require biometric authentication
   * during key creation. Windows always authenticates via Windows Hello.
   */
  val enforceBiometric: Boolean? = null,
  /**
   * [Android/iOS/macOS] Whether to invalidate the key when new biometrics
   * are enrolled. Not supported on Windows.
   *
   * **Security Note**: When `true`, keys become invalid if fingerprints/faces
   * are added or removed, preventing unauthorized access if an attacker
   * enrolls their own biometrics on a compromised device.
   */
  val setInvalidatedByBiometricEnrollment: Boolean? = null,
  /**
   * [Android/iOS/macOS] Whether to allow device credentials (PIN/pattern/passcode)
   * as fallback for biometric authentication. Not supported on Windows.
   */
  val useDeviceCredentials: Boolean? = null,
  /**
   * [Android] Whether to enable decryption capability for the key.
   * On iOS/macOS, decryption is always available with EC keys.
   */
  val enableDecryption: Boolean? = null,
  /** [Android] Subtitle text for the biometric prompt. */
  val promptSubtitle: String? = null,
  /** [Android] Description text for the biometric prompt. */
  val promptDescription: String? = null,
  /** [Android] Text for the cancel button in the biometric prompt. */
  val cancelButtonText: String? = null,
  /**
   * [All platforms] When `true`, key creation will fail with
   * [BiometricError.keyAlreadyExists] if a key with the specified alias
   * (or the default alias) already exists.
   *
   * When `false` (default), existing keys are silently replaced.
   */
  val failIfExists: Boolean? = null,
  /**
   * [Android 15+] Custom fallback buttons shown on the biometric prompt.
   * When provided, these replace the default cancel button.
   * If the user taps a fallback option, the result will have
   * `code == BiometricError.fallbackSelected` with the selected option's
   * index and text. On other platforms, this field is ignored.
   */
  val fallbackOptions: List<BiometricFallbackOption?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CreateKeysConfig {
      val signatureType = pigeonVar_list[0] as SignatureType?
      val enforceBiometric = pigeonVar_list[1] as Boolean?
      val setInvalidatedByBiometricEnrollment = pigeonVar_list[2] as Boolean?
      val useDeviceCredentials = pigeonVar_list[3] as Boolean?
      val enableDecryption = pigeonVar_list[4] as Boolean?
      val promptSubtitle = pigeonVar_list[5] as String?
      val promptDescription = pigeonVar_list[6] as String?
      val cancelButtonText = pigeonVar_list[7] as String?
      val failIfExists = pigeonVar_list[8] as Boolean?
      val fallbackOptions = pigeonVar_list[9] as List<BiometricFallbackOption?>?
      return CreateKeysConfig(signatureType, enforceBiometric, setInvalidatedByBiometricEnrollment, useDeviceCredentials, enableDecryption, promptSubtitle, promptDescription, cancelButtonText, failIfExists, fallbackOptions)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      signatureType,
      enforceBiometric,
      setInvalidatedByBiometricEnrollment,
      useDeviceCredentials,
      enableDecryption,
      promptSubtitle,
      promptDescription,
      cancelButtonText,
      failIfExists,
      fallbackOptions,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CreateKeysConfig
    return BiometricSignatureApiPigeonUtils.deepEquals(this.signatureType, other.signatureType) && BiometricSignatureApiPigeonUtils.deepEquals(this.enforceBiometric, other.enforceBiometric) && BiometricSignatureApiPigeonUtils.deepEquals(this.setInvalidatedByBiometricEnrollment, other.setInvalidatedByBiometricEnrollment) && BiometricSignatureApiPigeonUtils.deepEquals(this.useDeviceCredentials, other.useDeviceCredentials) && BiometricSignatureApiPigeonUtils.deepEquals(this.enableDecryption, other.enableDecryption) && BiometricSignatureApiPigeonUtils.deepEquals(this.promptSubtitle, other.promptSubtitle) && BiometricSignatureApiPigeonUtils.deepEquals(this.promptDescription, other.promptDescription) && BiometricSignatureApiPigeonUtils.deepEquals(this.cancelButtonText, other.cancelButtonText) && BiometricSignatureApiPigeonUtils.deepEquals(this.failIfExists, other.failIfExists) && BiometricSignatureApiPigeonUtils.deepEquals(this.fallbackOptions, other.fallbackOptions)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.signatureType)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.enforceBiometric)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.setInvalidatedByBiometricEnrollment)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.useDeviceCredentials)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.enableDecryption)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.promptSubtitle)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.promptDescription)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.cancelButtonText)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.failIfExists)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.fallbackOptions)
    return result
  }
}

/**
 * Configuration for signature creation (all platforms).
 *
 * Fields are documented with which platform(s) they apply to.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CreateSignatureConfig (
  /** [Android] Subtitle text for the biometric prompt. */
  val promptSubtitle: String? = null,
  /** [Android] Description text for the biometric prompt. */
  val promptDescription: String? = null,
  /** [Android] Text for the cancel button in the biometric prompt. */
  val cancelButtonText: String? = null,
  /** [Android] Whether to allow device credentials (PIN/pattern) as fallback. */
  val allowDeviceCredentials: Boolean? = null,
  /** [iOS] Whether to migrate from legacy keychain storage. */
  val shouldMigrate: Boolean? = null,
  /**
   * [Android 15+] Custom fallback buttons shown on the biometric prompt.
   * When provided, these replace the default cancel button.
   * If the user taps a fallback option, the result will have
   * `code == BiometricError.fallbackSelected` with the selected option's
   * index and text. On other platforms, this field is ignored.
   */
  val fallbackOptions: List<BiometricFallbackOption?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CreateSignatureConfig {
      val promptSubtitle = pigeonVar_list[0] as String?
      val promptDescription = pigeonVar_list[1] as String?
      val cancelButtonText = pigeonVar_list[2] as String?
      val allowDeviceCredentials = pigeonVar_list[3] as Boolean?
      val shouldMigrate = pigeonVar_list[4] as Boolean?
      val fallbackOptions = pigeonVar_list[5] as List<BiometricFallbackOption?>?
      return CreateSignatureConfig(promptSubtitle, promptDescription, cancelButtonText, allowDeviceCredentials, shouldMigrate, fallbackOptions)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      promptSubtitle,
      promptDescription,
      cancelButtonText,
      allowDeviceCredentials,
      shouldMigrate,
      fallbackOptions,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CreateSignatureConfig
    return BiometricSignatureApiPigeonUtils.deepEquals(this.promptSubtitle, other.promptSubtitle) && BiometricSignatureApiPigeonUtils.deepEquals(this.promptDescription, other.promptDescription) && BiometricSignatureApiPigeonUtils.deepEquals(this.cancelButtonText, other.cancelButtonText) && BiometricSignatureApiPigeonUtils.deepEquals(this.allowDeviceCredentials, other.allowDeviceCredentials) && BiometricSignatureApiPigeonUtils.deepEquals(this.shouldMigrate, other.shouldMigrate) && BiometricSignatureApiPigeonUtils.deepEquals(this.fallbackOptions, other.fallbackOptions)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.promptSubtitle)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.promptDescription)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.cancelButtonText)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.allowDeviceCredentials)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.shouldMigrate)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.fallbackOptions)
    return result
  }
}

/**
 * Configuration for decryption (all platforms).
 *
 * Fields are documented with which platform(s) they apply to.
 * Note: Decryption is not supported on Windows.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class DecryptConfig (
  /** [Android] Subtitle text for the biometric prompt. */
  val promptSubtitle: String? = null,
  /** [Android] Description text for the biometric prompt. */
  val promptDescription: String? = null,
  /** [Android] Text for the cancel button in the biometric prompt. */
  val cancelButtonText: String? = null,
  /** [Android] Whether to allow device credentials (PIN/pattern) as fallback. */
  val allowDeviceCredentials: Boolean? = null,
  /** [iOS] Whether to migrate from legacy keychain storage. */
  val shouldMigrate: Boolean? = null,
  /**
   * [Android 15+] Custom fallback buttons shown on the biometric prompt.
   * When provided, these replace the default cancel button.
   * If the user taps a fallback option, the result will have
   * `code == BiometricError.fallbackSelected` with the selected option's
   * index and text. On other platforms, this field is ignored.
   */
  val fallbackOptions: List<BiometricFallbackOption?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DecryptConfig {
      val promptSubtitle = pigeonVar_list[0] as String?
      val promptDescription = pigeonVar_list[1] as String?
      val cancelButtonText = pigeonVar_list[2] as String?
      val allowDeviceCredentials = pigeonVar_list[3] as Boolean?
      val shouldMigrate = pigeonVar_list[4] as Boolean?
      val fallbackOptions = pigeonVar_list[5] as List<BiometricFallbackOption?>?
      return DecryptConfig(promptSubtitle, promptDescription, cancelButtonText, allowDeviceCredentials, shouldMigrate, fallbackOptions)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      promptSubtitle,
      promptDescription,
      cancelButtonText,
      allowDeviceCredentials,
      shouldMigrate,
      fallbackOptions,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as DecryptConfig
    return BiometricSignatureApiPigeonUtils.deepEquals(this.promptSubtitle, other.promptSubtitle) && BiometricSignatureApiPigeonUtils.deepEquals(this.promptDescription, other.promptDescription) && BiometricSignatureApiPigeonUtils.deepEquals(this.cancelButtonText, other.cancelButtonText) && BiometricSignatureApiPigeonUtils.deepEquals(this.allowDeviceCredentials, other.allowDeviceCredentials) && BiometricSignatureApiPigeonUtils.deepEquals(this.shouldMigrate, other.shouldMigrate) && BiometricSignatureApiPigeonUtils.deepEquals(this.fallbackOptions, other.fallbackOptions)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.promptSubtitle)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.promptDescription)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.cancelButtonText)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.allowDeviceCredentials)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.shouldMigrate)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.fallbackOptions)
    return result
  }
}

/**
 * Configuration for simple biometric prompt (authentication without crypto ops).
 *
 * This allows customization of the biometric prompt across platforms.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class SimplePromptConfig (
  /** [Android] Subtitle text displayed below the title in the biometric prompt. */
  val subtitle: String? = null,
  /** [Android] Description text displayed in the biometric prompt body. */
  val description: String? = null,
  /**
   * [Android] Text for the cancel/negative button.
   * Default: "Cancel" on Android, system default on iOS/macOS.
   */
  val cancelButtonText: String? = null,
  /**
   * [Android/iOS/macOS] Whether to allow device credentials (PIN/pattern/passcode)
   * as a fallback for biometric authentication.
   *
   * When true:
   * - Android: Shows "Use PIN" option after biometric failure
   * - iOS/macOS: Uses .deviceOwnerAuthentication policy
   * - Windows: Not applicable (Windows Hello handles fallback internally)
   *
   * Default: false (biometric-only authentication)
   */
  val allowDeviceCredentials: Boolean? = null,
  /**
   * [Android] The required biometric strength level.
   *
   * - strong: Only Class 3 biometrics (e.g., fingerprint, in-screen fingerprint)
   * - weak: Class 2 biometrics allowed (e.g., face unlock without depth)
   *
   * Note: iOS/macOS always use strong biometrics. Windows Hello also uses strong.
   * If strong biometrics are not available but weak are, and strength is set to
   * strong, authentication will fail with [BiometricError.notEnrolled].
   *
   * Default: strong
   */
  val biometricStrength: BiometricStrength? = null,
  /**
   * [Android 15+] Custom fallback buttons shown on the biometric prompt.
   * When provided, these replace the default cancel button.
   * If the user taps a fallback option, the result will have
   * `code == BiometricError.fallbackSelected` with the selected option's
   * index and text. On other platforms, this field is ignored.
   */
  val fallbackOptions: List<BiometricFallbackOption?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SimplePromptConfig {
      val subtitle = pigeonVar_list[0] as String?
      val description = pigeonVar_list[1] as String?
      val cancelButtonText = pigeonVar_list[2] as String?
      val allowDeviceCredentials = pigeonVar_list[3] as Boolean?
      val biometricStrength = pigeonVar_list[4] as BiometricStrength?
      val fallbackOptions = pigeonVar_list[5] as List<BiometricFallbackOption?>?
      return SimplePromptConfig(subtitle, description, cancelButtonText, allowDeviceCredentials, biometricStrength, fallbackOptions)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      subtitle,
      description,
      cancelButtonText,
      allowDeviceCredentials,
      biometricStrength,
      fallbackOptions,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as SimplePromptConfig
    return BiometricSignatureApiPigeonUtils.deepEquals(this.subtitle, other.subtitle) && BiometricSignatureApiPigeonUtils.deepEquals(this.description, other.description) && BiometricSignatureApiPigeonUtils.deepEquals(this.cancelButtonText, other.cancelButtonText) && BiometricSignatureApiPigeonUtils.deepEquals(this.allowDeviceCredentials, other.allowDeviceCredentials) && BiometricSignatureApiPigeonUtils.deepEquals(this.biometricStrength, other.biometricStrength) && BiometricSignatureApiPigeonUtils.deepEquals(this.fallbackOptions, other.fallbackOptions)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.subtitle)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.description)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.cancelButtonText)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.allowDeviceCredentials)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.biometricStrength)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.fallbackOptions)
    return result
  }
}

/**
 * Result from simple biometric prompt authentication.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class SimplePromptResult (
  /** Whether authentication was successful. */
  val success: Boolean? = null,
  /**
   * Error message if authentication failed.
   * This is a human-readable description of what went wrong.
   */
  val error: String? = null,
  /**
   * Standardized error code if authentication failed.
   * Use this for programmatic error handling.
   */
  val code: BiometricError? = null,
  /**
   * [Android 15+] Index of the selected fallback option in the original list.
   * Only populated when `code == BiometricError.fallbackSelected`.
   */
  val selectedFallbackIndex: Long? = null,
  /**
   * [Android 15+] Text of the selected fallback option.
   * Only populated when `code == BiometricError.fallbackSelected`.
   */
  val selectedFallbackText: String? = null,
  /** The type of authentication used to complete this operation. */
  val authenticationType: AuthenticationType? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SimplePromptResult {
      val success = pigeonVar_list[0] as Boolean?
      val error = pigeonVar_list[1] as String?
      val code = pigeonVar_list[2] as BiometricError?
      val selectedFallbackIndex = pigeonVar_list[3] as Long?
      val selectedFallbackText = pigeonVar_list[4] as String?
      val authenticationType = pigeonVar_list[5] as AuthenticationType?
      return SimplePromptResult(success, error, code, selectedFallbackIndex, selectedFallbackText, authenticationType)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      success,
      error,
      code,
      selectedFallbackIndex,
      selectedFallbackText,
      authenticationType,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as SimplePromptResult
    return BiometricSignatureApiPigeonUtils.deepEquals(this.success, other.success) && BiometricSignatureApiPigeonUtils.deepEquals(this.error, other.error) && BiometricSignatureApiPigeonUtils.deepEquals(this.code, other.code) && BiometricSignatureApiPigeonUtils.deepEquals(this.selectedFallbackIndex, other.selectedFallbackIndex) && BiometricSignatureApiPigeonUtils.deepEquals(this.selectedFallbackText, other.selectedFallbackText) && BiometricSignatureApiPigeonUtils.deepEquals(this.authenticationType, other.authenticationType)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.success)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.error)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.code)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.selectedFallbackIndex)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.selectedFallbackText)
    result = 31 * result + BiometricSignatureApiPigeonUtils.deepHash(this.authenticationType)
    return result
  }
}
private open class BiometricSignatureApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          AuthenticationType.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          BiometricType.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          BiometricStrength.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          BiometricError.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          SignatureType.ofRaw(it.toInt())
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          KeyFormat.ofRaw(it.toInt())
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          SignatureFormat.ofRaw(it.toInt())
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PayloadFormat.ofRaw(it.toInt())
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BiometricFallbackOption.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BiometricAvailability.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KeyCreationResult.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SignatureResult.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DecryptResult.fromList(it)
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KeyInfo.fromList(it)
        }
      }
      143.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CreateKeysConfig.fromList(it)
        }
      }
      144.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CreateSignatureConfig.fromList(it)
        }
      }
      145.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DecryptConfig.fromList(it)
        }
      }
      146.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SimplePromptConfig.fromList(it)
        }
      }
      147.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SimplePromptResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is AuthenticationType -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is BiometricType -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is BiometricStrength -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is BiometricError -> {
        stream.write(132)
        writeValue(stream, value.raw.toLong())
      }
      is SignatureType -> {
        stream.write(133)
        writeValue(stream, value.raw.toLong())
      }
      is KeyFormat -> {
        stream.write(134)
        writeValue(stream, value.raw.toLong())
      }
      is SignatureFormat -> {
        stream.write(135)
        writeValue(stream, value.raw.toLong())
      }
      is PayloadFormat -> {
        stream.write(136)
        writeValue(stream, value.raw.toLong())
      }
      is BiometricFallbackOption -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is BiometricAvailability -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is KeyCreationResult -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is SignatureResult -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is DecryptResult -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      is KeyInfo -> {
        stream.write(142)
        writeValue(stream, value.toList())
      }
      is CreateKeysConfig -> {
        stream.write(143)
        writeValue(stream, value.toList())
      }
      is CreateSignatureConfig -> {
        stream.write(144)
        writeValue(stream, value.toList())
      }
      is DecryptConfig -> {
        stream.write(145)
        writeValue(stream, value.toList())
      }
      is SimplePromptConfig -> {
        stream.write(146)
        writeValue(stream, value.toList())
      }
      is SimplePromptResult -> {
        stream.write(147)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface BiometricSignatureApi {
  /** Checks if biometric authentication is available. */
  fun biometricAuthAvailable(callback: (Result<BiometricAvailability>) -> Unit)
  /**
   * Creates a new key pair.
   *
   * [keyAlias] is an optional alias for the key. When null, the default
   * alias is used. Different aliases create independent key pairs.
   * [config] contains platform-specific options. See [CreateKeysConfig].
   * [keyFormat] specifies the output format for the public key.
   * [promptMessage] is the message shown to the user during authentication.
   */
  fun createKeys(keyAlias: String?, config: CreateKeysConfig?, keyFormat: KeyFormat, promptMessage: String?, callback: (Result<KeyCreationResult>) -> Unit)
  /**
   * Creates a signature.
   *
   * [payload] is the data to sign.
   * [keyAlias] specifies which key to sign with. Defaults to the default alias.
   * [config] contains platform-specific options. See [CreateSignatureConfig].
   * [signatureFormat] specifies the output format for the signature.
   * [keyFormat] specifies the output format for the public key.
   * [promptMessage] is the message shown to the user during authentication.
   */
  fun createSignature(payload: String, keyAlias: String?, config: CreateSignatureConfig?, signatureFormat: SignatureFormat, keyFormat: KeyFormat, promptMessage: String?, callback: (Result<SignatureResult>) -> Unit)
  /**
   * Decrypts data.
   *
   * Note: Not supported on Windows.
   * [payload] is the encrypted data.
   * [keyAlias] specifies which key to decrypt with. Defaults to the default alias.
   * [payloadFormat] specifies the format of the encrypted data.
   * [config] contains platform-specific options. See [DecryptConfig].
   * [promptMessage] is the message shown to the user during authentication.
   */
  fun decrypt(payload: String, keyAlias: String?, payloadFormat: PayloadFormat, config: DecryptConfig?, promptMessage: String?, callback: (Result<DecryptResult>) -> Unit)
  /**
   * Deletes keys for a specific alias.
   *
   * [keyAlias] specifies which key to delete. When null, deletes the
   * default alias only. Other aliases are not affected.
   */
  fun deleteKeys(keyAlias: String?, callback: (Result<Boolean>) -> Unit)
  /**
   * Deletes all biometric keys across all aliases.
   *
   * This is a destructive operation that removes every key managed by
   * this plugin. Use [deleteKeys] for targeted deletion.
   */
  fun deleteAllKeys(callback: (Result<Boolean>) -> Unit)
  /**
   * Gets detailed information about existing biometric keys.
   *
   * [keyAlias] specifies which key to query. Defaults to the default alias.
   * Returns key metadata including algorithm, size, validity, and public keys.
   */
  fun getKeyInfo(keyAlias: String?, checkValidity: Boolean, keyFormat: KeyFormat, callback: (Result<KeyInfo>) -> Unit)
  /**
   * Performs simple biometric authentication without cryptographic operations.
   *
   * This is useful for:
   * - Quick re-authentication flows
   * - Confirming user presence before sensitive operations
   * - Simple access control without key management
   *
   * [promptMessage] is the main message shown to the user (title on Android).
   * [config] contains optional platform-specific configuration.
   *
   * Returns a [SimplePromptResult] indicating success or failure.
   */
  fun simplePrompt(promptMessage: String, config: SimplePromptConfig?, callback: (Result<SimplePromptResult>) -> Unit)
  /**
   * Checks whether the device has a screen lock (PIN, pattern, password, or
   * passcode) configured.
   *
   * This is a precondition for biometric enrollment on most platforms:
   * - Android: Uses `KeyguardManager.isDeviceSecure()`
   * - iOS/macOS: Evaluates `LAPolicy.deviceOwnerAuthentication` to detect
   *   `kLAErrorPasscodeNotSet`
   * - Windows: Checks Windows Hello availability via
   *   `KeyCredentialManager.IsSupportedAsync()`
   *
   * Returns `true` if the device has a screen lock configured.
   */
  fun isDeviceLockSet(callback: (Result<Boolean>) -> Unit)

  companion object {
    /** The codec used by BiometricSignatureApi. */
    val codec: MessageCodec<Any?> by lazy {
      BiometricSignatureApiPigeonCodec()
    }
    /** Sets up an instance of `BiometricSignatureApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: BiometricSignatureApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.biometricAuthAvailable$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.biometricAuthAvailable{ result: Result<BiometricAvailability> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(BiometricSignatureApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(BiometricSignatureApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.createKeys$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyAliasArg = args[0] as String?
            val configArg = args[1] as CreateKeysConfig?
            val keyFormatArg = args[2] as KeyFormat
            val promptMessageArg = args[3] as String?
            api.createKeys(keyAliasArg, configArg, keyFormatArg, promptMessageArg) { result: Result<KeyCreationResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(BiometricSignatureApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(BiometricSignatureApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.createSignature$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val payloadArg = args[0] as String
            val keyAliasArg = args[1] as String?
            val configArg = args[2] as CreateSignatureConfig?
            val signatureFormatArg = args[3] as SignatureFormat
            val keyFormatArg = args[4] as KeyFormat
            val promptMessageArg = args[5] as String?
            api.createSignature(payloadArg, keyAliasArg, configArg, signatureFormatArg, keyFormatArg, promptMessageArg) { result: Result<SignatureResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(BiometricSignatureApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(BiometricSignatureApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.decrypt$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val payloadArg = args[0] as String
            val keyAliasArg = args[1] as String?
            val payloadFormatArg = args[2] as PayloadFormat
            val configArg = args[3] as DecryptConfig?
            val promptMessageArg = args[4] as String?
            api.decrypt(payloadArg, keyAliasArg, payloadFormatArg, configArg, promptMessageArg) { result: Result<DecryptResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(BiometricSignatureApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(BiometricSignatureApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.deleteKeys$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyAliasArg = args[0] as String?
            api.deleteKeys(keyAliasArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(BiometricSignatureApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(BiometricSignatureApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.deleteAllKeys$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.deleteAllKeys{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(BiometricSignatureApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(BiometricSignatureApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.getKeyInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyAliasArg = args[0] as String?
            val checkValidityArg = args[1] as Boolean
            val keyFormatArg = args[2] as KeyFormat
            api.getKeyInfo(keyAliasArg, checkValidityArg, keyFormatArg) { result: Result<KeyInfo> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(BiometricSignatureApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(BiometricSignatureApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.simplePrompt$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val promptMessageArg = args[0] as String
            val configArg = args[1] as SimplePromptConfig?
            api.simplePrompt(promptMessageArg, configArg) { result: Result<SimplePromptResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(BiometricSignatureApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(BiometricSignatureApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.isDeviceLockSet$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.isDeviceLockSet{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(BiometricSignatureApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(BiometricSignatureApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
