// Autogenerated from Pigeon (v25.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsBiometricSignatureApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsBiometricSignatureApi(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsBiometricSignatureApi(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashBiometricSignatureApi(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashBiometricSignatureApi(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashBiometricSignatureApi(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// The type of authentication that was used to complete an operation.
///
/// On Android, this is determined by the platform's `AuthenticationResult.getAuthenticationType()`.
/// On iOS/macOS, this is inferred: [biometric] if device credentials are not allowed,
/// [credential] if no biometric hardware is available, [unknown] otherwise.
/// On Windows, this is always [unknown] as Windows Hello handles auth internally.
enum AuthenticationType: Int {
  /// The user authenticated using device credentials (PIN, pattern, or password).
  case credential = 0
  /// The user authenticated using a biometric (fingerprint, face, iris).
  case biometric = 1
  /// The authentication type could not be determined.
  case unknown = 2
}

/// Types of biometric authentication supported by the device.
enum BiometricType: Int {
  /// Face recognition (Face ID on iOS, face unlock on Android).
  case face = 0
  /// Fingerprint recognition (Touch ID on iOS/macOS, fingerprint on Android).
  case fingerprint = 1
  /// Iris scanner (Android only, rare on consumer devices).
  case iris = 2
  /// Multiple biometric types are available on the device.
  case multiple = 3
  /// No biometric hardware available or biometrics are disabled.
  case unavailable = 4
}

/// Biometric authentication strength level.
///
/// This affects which biometric sensors can be used for authentication.
/// Note: On iOS/macOS, only strong biometrics are available (Face ID, Touch ID, Optic ID).
/// On Windows, Windows Hello always uses strong authentication.
enum BiometricStrength: Int {
  /// Strong biometrics only (e.g., fingerprint, face recognition with depth sensing).
  /// This is the most secure option and is required for cryptographic operations.
  case strong = 0
  /// Weak biometrics allowed (e.g., face recognition without depth sensing).
  /// This option provides more device compatibility but lower security.
  case weak = 1
}

/// Standardized error codes for the plugin.
enum BiometricError: Int {
  /// The operation was successful.
  case success = 0
  /// The user canceled the operation.
  case userCanceled = 1
  /// Biometric authentication is not available on this device.
  case notAvailable = 2
  /// No biometrics are enrolled.
  case notEnrolled = 3
  /// The user is temporarily locked out due to too many failed attempts.
  case lockedOut = 4
  /// The user is permanently locked out until they log in with a strong method.
  case lockedOutPermanent = 5
  /// The requested key was not found.
  case keyNotFound = 6
  /// The key has been invalidated (e.g. by new biometric enrollment).
  case keyInvalidated = 7
  /// An unknown error occurred.
  case unknown = 8
  /// The input payload was invalid (e.g. not valid Base64).
  case invalidInput = 9
  /// A security update is required before biometrics can be used.
  case securityUpdateRequired = 10
  /// Biometric authentication is not supported on this device/OS version.
  case notSupported = 11
  /// The system canceled the operation (e.g., app went to background).
  case systemCanceled = 12
  /// Failed to show the biometric prompt (e.g., activity not available).
  case promptError = 13
  /// A key with the specified alias already exists and failIfExists was set.
  case keyAlreadyExists = 14
  /// The device does not have a screen lock (PIN, pattern, password, or
  /// passcode) configured.
  ///
  /// A screen lock is a prerequisite for biometric enrollment and for
  /// hardware-backed key storage on all platforms:
  /// - **iOS/macOS**: Maps from `kLAErrorPasscodeNotSet`. Can surface during
  ///   any operation that requires Secure Enclave access (key creation,
  ///   signing, decryption, and simple prompt).
  /// - **Android**: Maps from `ERROR_NO_DEVICE_CREDENTIAL` (cause code 14).
  ///   Only surfaces when `allowDeviceCredentials: true` is set; for
  ///   biometric-only flows Android reports [notAvailable] or [notEnrolled]
  ///   instead.
  /// - **Windows**: Not applicable — Windows Hello manages its own credential
  ///   requirements.
  ///
  /// Use [BiometricSignatureApi.isDeviceLockSet] as a proactive precondition
  /// check before attempting operations. This error is the reactive
  /// counterpart when the check is skipped or the user removes their screen
  /// lock between the check and the operation.
  ///
  /// **Migration from 11.0.x → 11.1.0**: On Android, `ERROR_NO_DEVICE_CREDENTIAL`
  /// (cause code 14) was previously mapped to [notAvailable]. Consumers that
  /// were pattern-matching on [notAvailable] to drive a "no screen lock" UX
  /// should migrate to [passcodeNotSet]. iOS/macOS mapping of
  /// `kLAErrorPasscodeNotSet` changed in the same release.
  case passcodeNotSet = 15
}

/// The cryptographic algorithm to use for key generation.
enum SignatureType: Int {
  /// RSA-2048 (Android: native, iOS/macOS: hybrid mode with Secure Enclave EC).
  case rsa = 0
  /// ECDSA P-256 (hardware-backed on all platforms).
  case ecdsa = 1
}

/// Output format for public keys.
enum KeyFormat: Int {
  /// Base64-encoded DER (SubjectPublicKeyInfo).
  case base64 = 0
  /// PEM format with BEGIN/END PUBLIC KEY headers.
  case pem = 1
  /// Hexadecimal-encoded DER.
  case hex = 2
  /// Raw DER bytes (returned via `publicKeyBytes`).
  case raw = 3
}

/// Output format for cryptographic signatures.
enum SignatureFormat: Int {
  /// Base64-encoded signature bytes.
  case base64 = 0
  /// Hexadecimal-encoded signature bytes.
  case hex = 1
  /// Raw signature bytes (returned via `signatureBytes`).
  case raw = 2
}

/// Input format for encrypted payloads to decrypt.
enum PayloadFormat: Int {
  /// Base64-encoded ciphertext.
  case base64 = 0
  /// Hexadecimal-encoded ciphertext.
  case hex = 1
  /// Raw UTF-8 string (not recommended for binary data).
  case raw = 2
}

/// Generated class from Pigeon that represents data sent in messages.
struct BiometricAvailability: Hashable {
  var canAuthenticate: Bool? = nil
  var hasEnrolledBiometrics: Bool? = nil
  var availableBiometrics: [BiometricType?]? = nil
  var reason: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BiometricAvailability? {
    let canAuthenticate: Bool? = nilOrValue(pigeonVar_list[0])
    let hasEnrolledBiometrics: Bool? = nilOrValue(pigeonVar_list[1])
    let availableBiometrics: [BiometricType?]? = nilOrValue(pigeonVar_list[2])
    let reason: String? = nilOrValue(pigeonVar_list[3])

    return BiometricAvailability(
      canAuthenticate: canAuthenticate,
      hasEnrolledBiometrics: hasEnrolledBiometrics,
      availableBiometrics: availableBiometrics,
      reason: reason
    )
  }
  func toList() -> [Any?] {
    return [
      canAuthenticate,
      hasEnrolledBiometrics,
      availableBiometrics,
      reason,
    ]
  }
  static func == (lhs: BiometricAvailability, rhs: BiometricAvailability) -> Bool {
    return deepEqualsBiometricSignatureApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashBiometricSignatureApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct KeyCreationResult: Hashable {
  var publicKey: String? = nil
  var publicKeyBytes: FlutterStandardTypedData? = nil
  var error: String? = nil
  var code: BiometricError? = nil
  var algorithm: String? = nil
  var keySize: Int64? = nil
  var decryptingPublicKey: String? = nil
  var decryptingAlgorithm: String? = nil
  var decryptingKeySize: Int64? = nil
  var isHybridMode: Bool? = nil
  /// The type of authentication used to complete this operation.
  ///
  /// Inferred on Apple platforms (iOS/macOS), authoritative on Android.
  /// See [AuthenticationType] for how inference is performed when the
  /// platform does not report the method directly.
  var authenticationType: AuthenticationType? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KeyCreationResult? {
    let publicKey: String? = nilOrValue(pigeonVar_list[0])
    let publicKeyBytes: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[1])
    let error: String? = nilOrValue(pigeonVar_list[2])
    let code: BiometricError? = nilOrValue(pigeonVar_list[3])
    let algorithm: String? = nilOrValue(pigeonVar_list[4])
    let keySize: Int64? = nilOrValue(pigeonVar_list[5])
    let decryptingPublicKey: String? = nilOrValue(pigeonVar_list[6])
    let decryptingAlgorithm: String? = nilOrValue(pigeonVar_list[7])
    let decryptingKeySize: Int64? = nilOrValue(pigeonVar_list[8])
    let isHybridMode: Bool? = nilOrValue(pigeonVar_list[9])
    let authenticationType: AuthenticationType? = nilOrValue(pigeonVar_list[10])

    return KeyCreationResult(
      publicKey: publicKey,
      publicKeyBytes: publicKeyBytes,
      error: error,
      code: code,
      algorithm: algorithm,
      keySize: keySize,
      decryptingPublicKey: decryptingPublicKey,
      decryptingAlgorithm: decryptingAlgorithm,
      decryptingKeySize: decryptingKeySize,
      isHybridMode: isHybridMode,
      authenticationType: authenticationType
    )
  }
  func toList() -> [Any?] {
    return [
      publicKey,
      publicKeyBytes,
      error,
      code,
      algorithm,
      keySize,
      decryptingPublicKey,
      decryptingAlgorithm,
      decryptingKeySize,
      isHybridMode,
      authenticationType,
    ]
  }
  static func == (lhs: KeyCreationResult, rhs: KeyCreationResult) -> Bool {
    return deepEqualsBiometricSignatureApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashBiometricSignatureApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct SignatureResult: Hashable {
  var signature: String? = nil
  var signatureBytes: FlutterStandardTypedData? = nil
  var publicKey: String? = nil
  var error: String? = nil
  var code: BiometricError? = nil
  var algorithm: String? = nil
  var keySize: Int64? = nil
  /// The type of authentication used to complete this operation.
  ///
  /// Inferred on Apple platforms (iOS/macOS), authoritative on Android.
  /// See [AuthenticationType] for how inference is performed when the
  /// platform does not report the method directly.
  var authenticationType: AuthenticationType? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SignatureResult? {
    let signature: String? = nilOrValue(pigeonVar_list[0])
    let signatureBytes: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[1])
    let publicKey: String? = nilOrValue(pigeonVar_list[2])
    let error: String? = nilOrValue(pigeonVar_list[3])
    let code: BiometricError? = nilOrValue(pigeonVar_list[4])
    let algorithm: String? = nilOrValue(pigeonVar_list[5])
    let keySize: Int64? = nilOrValue(pigeonVar_list[6])
    let authenticationType: AuthenticationType? = nilOrValue(pigeonVar_list[7])

    return SignatureResult(
      signature: signature,
      signatureBytes: signatureBytes,
      publicKey: publicKey,
      error: error,
      code: code,
      algorithm: algorithm,
      keySize: keySize,
      authenticationType: authenticationType
    )
  }
  func toList() -> [Any?] {
    return [
      signature,
      signatureBytes,
      publicKey,
      error,
      code,
      algorithm,
      keySize,
      authenticationType,
    ]
  }
  static func == (lhs: SignatureResult, rhs: SignatureResult) -> Bool {
    return deepEqualsBiometricSignatureApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashBiometricSignatureApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct DecryptResult: Hashable {
  var decryptedData: String? = nil
  var error: String? = nil
  var code: BiometricError? = nil
  /// The type of authentication used to complete this operation.
  ///
  /// Inferred on Apple platforms (iOS/macOS), authoritative on Android.
  /// See [AuthenticationType] for how inference is performed when the
  /// platform does not report the method directly.
  var authenticationType: AuthenticationType? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DecryptResult? {
    let decryptedData: String? = nilOrValue(pigeonVar_list[0])
    let error: String? = nilOrValue(pigeonVar_list[1])
    let code: BiometricError? = nilOrValue(pigeonVar_list[2])
    let authenticationType: AuthenticationType? = nilOrValue(pigeonVar_list[3])

    return DecryptResult(
      decryptedData: decryptedData,
      error: error,
      code: code,
      authenticationType: authenticationType
    )
  }
  func toList() -> [Any?] {
    return [
      decryptedData,
      error,
      code,
      authenticationType,
    ]
  }
  static func == (lhs: DecryptResult, rhs: DecryptResult) -> Bool {
    return deepEqualsBiometricSignatureApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashBiometricSignatureApi(value: toList(), hasher: &hasher)
  }
}

/// Detailed information about existing biometric keys.
///
/// Generated class from Pigeon that represents data sent in messages.
struct KeyInfo: Hashable {
  /// Whether any biometric key exists on the device.
  var exists: Bool? = nil
  /// Whether the key is still valid (not invalidated by biometric changes).
  /// Only populated when `checkValidity: true` is passed.
  var isValid: Bool? = nil
  /// The algorithm of the signing key (e.g., "RSA", "EC").
  var algorithm: String? = nil
  /// The key size in bits (e.g., 2048 for RSA, 256 for EC).
  var keySize: Int64? = nil
  /// Whether the key is in hybrid mode (separate signing and decryption keys).
  var isHybridMode: Bool? = nil
  /// Signing key public key (formatted according to the requested format).
  var publicKey: String? = nil
  /// Decryption key public key for hybrid mode.
  var decryptingPublicKey: String? = nil
  /// Algorithm of the decryption key (hybrid mode only).
  var decryptingAlgorithm: String? = nil
  /// Key size of the decryption key in bits (hybrid mode only).
  var decryptingKeySize: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KeyInfo? {
    let exists: Bool? = nilOrValue(pigeonVar_list[0])
    let isValid: Bool? = nilOrValue(pigeonVar_list[1])
    let algorithm: String? = nilOrValue(pigeonVar_list[2])
    let keySize: Int64? = nilOrValue(pigeonVar_list[3])
    let isHybridMode: Bool? = nilOrValue(pigeonVar_list[4])
    let publicKey: String? = nilOrValue(pigeonVar_list[5])
    let decryptingPublicKey: String? = nilOrValue(pigeonVar_list[6])
    let decryptingAlgorithm: String? = nilOrValue(pigeonVar_list[7])
    let decryptingKeySize: Int64? = nilOrValue(pigeonVar_list[8])

    return KeyInfo(
      exists: exists,
      isValid: isValid,
      algorithm: algorithm,
      keySize: keySize,
      isHybridMode: isHybridMode,
      publicKey: publicKey,
      decryptingPublicKey: decryptingPublicKey,
      decryptingAlgorithm: decryptingAlgorithm,
      decryptingKeySize: decryptingKeySize
    )
  }
  func toList() -> [Any?] {
    return [
      exists,
      isValid,
      algorithm,
      keySize,
      isHybridMode,
      publicKey,
      decryptingPublicKey,
      decryptingAlgorithm,
      decryptingKeySize,
    ]
  }
  static func == (lhs: KeyInfo, rhs: KeyInfo) -> Bool {
    return deepEqualsBiometricSignatureApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashBiometricSignatureApi(value: toList(), hasher: &hasher)
  }
}

/// Configuration for key creation (all platforms).
///
/// Fields are documented with which platform(s) they apply to.
/// Windows ignores most fields as it only supports RSA with mandatory
/// Windows Hello authentication.
///
/// Generated class from Pigeon that represents data sent in messages.
struct CreateKeysConfig: Hashable {
  /// [Android/iOS/macOS] The cryptographic algorithm to use.
  /// Windows only supports RSA and ignores this field.
  var signatureType: SignatureType? = nil
  /// [Android/iOS/macOS] Whether to require biometric authentication
  /// during key creation. Windows always authenticates via Windows Hello.
  var enforceBiometric: Bool? = nil
  /// [Android/iOS/macOS] Whether to invalidate the key when new biometrics
  /// are enrolled. Not supported on Windows.
  ///
  /// **Security Note**: When `true`, keys become invalid if fingerprints/faces
  /// are added or removed, preventing unauthorized access if an attacker
  /// enrolls their own biometrics on a compromised device.
  var setInvalidatedByBiometricEnrollment: Bool? = nil
  /// [Android/iOS/macOS] Whether to allow device credentials (PIN/pattern/passcode)
  /// as fallback for biometric authentication. Not supported on Windows.
  var useDeviceCredentials: Bool? = nil
  /// [Android] Whether to enable decryption capability for the key.
  /// On iOS/macOS, decryption is always available with EC keys.
  var enableDecryption: Bool? = nil
  /// [Android] Subtitle text for the biometric prompt.
  var promptSubtitle: String? = nil
  /// [Android] Description text for the biometric prompt.
  var promptDescription: String? = nil
  /// [Android] Text for the cancel button in the biometric prompt.
  var cancelButtonText: String? = nil
  /// [All platforms] When `true`, key creation will fail with
  /// [BiometricError.keyAlreadyExists] if a key with the specified alias
  /// (or the default alias) already exists.
  ///
  /// When `false` (default), existing keys are silently replaced.
  var failIfExists: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CreateKeysConfig? {
    let signatureType: SignatureType? = nilOrValue(pigeonVar_list[0])
    let enforceBiometric: Bool? = nilOrValue(pigeonVar_list[1])
    let setInvalidatedByBiometricEnrollment: Bool? = nilOrValue(pigeonVar_list[2])
    let useDeviceCredentials: Bool? = nilOrValue(pigeonVar_list[3])
    let enableDecryption: Bool? = nilOrValue(pigeonVar_list[4])
    let promptSubtitle: String? = nilOrValue(pigeonVar_list[5])
    let promptDescription: String? = nilOrValue(pigeonVar_list[6])
    let cancelButtonText: String? = nilOrValue(pigeonVar_list[7])
    let failIfExists: Bool? = nilOrValue(pigeonVar_list[8])

    return CreateKeysConfig(
      signatureType: signatureType,
      enforceBiometric: enforceBiometric,
      setInvalidatedByBiometricEnrollment: setInvalidatedByBiometricEnrollment,
      useDeviceCredentials: useDeviceCredentials,
      enableDecryption: enableDecryption,
      promptSubtitle: promptSubtitle,
      promptDescription: promptDescription,
      cancelButtonText: cancelButtonText,
      failIfExists: failIfExists
    )
  }
  func toList() -> [Any?] {
    return [
      signatureType,
      enforceBiometric,
      setInvalidatedByBiometricEnrollment,
      useDeviceCredentials,
      enableDecryption,
      promptSubtitle,
      promptDescription,
      cancelButtonText,
      failIfExists,
    ]
  }
  static func == (lhs: CreateKeysConfig, rhs: CreateKeysConfig) -> Bool {
    return deepEqualsBiometricSignatureApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashBiometricSignatureApi(value: toList(), hasher: &hasher)
  }
}

/// Configuration for signature creation (all platforms).
///
/// Fields are documented with which platform(s) they apply to.
///
/// Generated class from Pigeon that represents data sent in messages.
struct CreateSignatureConfig: Hashable {
  /// [Android] Subtitle text for the biometric prompt.
  var promptSubtitle: String? = nil
  /// [Android] Description text for the biometric prompt.
  var promptDescription: String? = nil
  /// [Android] Text for the cancel button in the biometric prompt.
  var cancelButtonText: String? = nil
  /// [Android] Whether to allow device credentials (PIN/pattern) as fallback.
  var allowDeviceCredentials: Bool? = nil
  /// [iOS] Whether to migrate from legacy keychain storage.
  var shouldMigrate: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CreateSignatureConfig? {
    let promptSubtitle: String? = nilOrValue(pigeonVar_list[0])
    let promptDescription: String? = nilOrValue(pigeonVar_list[1])
    let cancelButtonText: String? = nilOrValue(pigeonVar_list[2])
    let allowDeviceCredentials: Bool? = nilOrValue(pigeonVar_list[3])
    let shouldMigrate: Bool? = nilOrValue(pigeonVar_list[4])

    return CreateSignatureConfig(
      promptSubtitle: promptSubtitle,
      promptDescription: promptDescription,
      cancelButtonText: cancelButtonText,
      allowDeviceCredentials: allowDeviceCredentials,
      shouldMigrate: shouldMigrate
    )
  }
  func toList() -> [Any?] {
    return [
      promptSubtitle,
      promptDescription,
      cancelButtonText,
      allowDeviceCredentials,
      shouldMigrate,
    ]
  }
  static func == (lhs: CreateSignatureConfig, rhs: CreateSignatureConfig) -> Bool {
    return deepEqualsBiometricSignatureApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashBiometricSignatureApi(value: toList(), hasher: &hasher)
  }
}

/// Configuration for decryption (all platforms).
///
/// Fields are documented with which platform(s) they apply to.
/// Note: Decryption is not supported on Windows.
///
/// Generated class from Pigeon that represents data sent in messages.
struct DecryptConfig: Hashable {
  /// [Android] Subtitle text for the biometric prompt.
  var promptSubtitle: String? = nil
  /// [Android] Description text for the biometric prompt.
  var promptDescription: String? = nil
  /// [Android] Text for the cancel button in the biometric prompt.
  var cancelButtonText: String? = nil
  /// [Android] Whether to allow device credentials (PIN/pattern) as fallback.
  var allowDeviceCredentials: Bool? = nil
  /// [iOS] Whether to migrate from legacy keychain storage.
  var shouldMigrate: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DecryptConfig? {
    let promptSubtitle: String? = nilOrValue(pigeonVar_list[0])
    let promptDescription: String? = nilOrValue(pigeonVar_list[1])
    let cancelButtonText: String? = nilOrValue(pigeonVar_list[2])
    let allowDeviceCredentials: Bool? = nilOrValue(pigeonVar_list[3])
    let shouldMigrate: Bool? = nilOrValue(pigeonVar_list[4])

    return DecryptConfig(
      promptSubtitle: promptSubtitle,
      promptDescription: promptDescription,
      cancelButtonText: cancelButtonText,
      allowDeviceCredentials: allowDeviceCredentials,
      shouldMigrate: shouldMigrate
    )
  }
  func toList() -> [Any?] {
    return [
      promptSubtitle,
      promptDescription,
      cancelButtonText,
      allowDeviceCredentials,
      shouldMigrate,
    ]
  }
  static func == (lhs: DecryptConfig, rhs: DecryptConfig) -> Bool {
    return deepEqualsBiometricSignatureApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashBiometricSignatureApi(value: toList(), hasher: &hasher)
  }
}

/// Configuration for simple biometric prompt (authentication without crypto ops).
///
/// This allows customization of the biometric prompt across platforms.
///
/// Generated class from Pigeon that represents data sent in messages.
struct SimplePromptConfig: Hashable {
  /// [Android] Subtitle text displayed below the title in the biometric prompt.
  var subtitle: String? = nil
  /// [Android] Description text displayed in the biometric prompt body.
  var description: String? = nil
  /// [Android] Text for the cancel/negative button.
  /// Default: "Cancel" on Android, system default on iOS/macOS.
  var cancelButtonText: String? = nil
  /// [Android/iOS/macOS] Whether to allow device credentials (PIN/pattern/passcode)
  /// as a fallback for biometric authentication.
  ///
  /// When true:
  /// - Android: Shows "Use PIN" option after biometric failure
  /// - iOS/macOS: Uses .deviceOwnerAuthentication policy
  /// - Windows: Not applicable (Windows Hello handles fallback internally)
  ///
  /// Default: false (biometric-only authentication)
  var allowDeviceCredentials: Bool? = nil
  /// [Android] The required biometric strength level.
  ///
  /// - strong: Only Class 3 biometrics (e.g., fingerprint, in-screen fingerprint)
  /// - weak: Class 2 biometrics allowed (e.g., face unlock without depth)
  ///
  /// Note: iOS/macOS always use strong biometrics. Windows Hello also uses strong.
  /// If strong biometrics are not available but weak are, and strength is set to
  /// strong, authentication will fail with [BiometricError.notEnrolled].
  ///
  /// Default: strong
  var biometricStrength: BiometricStrength? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SimplePromptConfig? {
    let subtitle: String? = nilOrValue(pigeonVar_list[0])
    let description: String? = nilOrValue(pigeonVar_list[1])
    let cancelButtonText: String? = nilOrValue(pigeonVar_list[2])
    let allowDeviceCredentials: Bool? = nilOrValue(pigeonVar_list[3])
    let biometricStrength: BiometricStrength? = nilOrValue(pigeonVar_list[4])

    return SimplePromptConfig(
      subtitle: subtitle,
      description: description,
      cancelButtonText: cancelButtonText,
      allowDeviceCredentials: allowDeviceCredentials,
      biometricStrength: biometricStrength
    )
  }
  func toList() -> [Any?] {
    return [
      subtitle,
      description,
      cancelButtonText,
      allowDeviceCredentials,
      biometricStrength,
    ]
  }
  static func == (lhs: SimplePromptConfig, rhs: SimplePromptConfig) -> Bool {
    return deepEqualsBiometricSignatureApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashBiometricSignatureApi(value: toList(), hasher: &hasher)
  }
}

/// Result from simple biometric prompt authentication.
///
/// Generated class from Pigeon that represents data sent in messages.
struct SimplePromptResult: Hashable {
  /// Whether authentication was successful.
  var success: Bool? = nil
  /// Error message if authentication failed.
  /// This is a human-readable description of what went wrong.
  var error: String? = nil
  /// Standardized error code if authentication failed.
  /// Use this for programmatic error handling.
  var code: BiometricError? = nil
  /// The type of authentication used to complete this operation.
  ///
  /// Inferred on Apple platforms (iOS/macOS), authoritative on Android.
  /// See [AuthenticationType] for how inference is performed when the
  /// platform does not report the method directly.
  var authenticationType: AuthenticationType? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SimplePromptResult? {
    let success: Bool? = nilOrValue(pigeonVar_list[0])
    let error: String? = nilOrValue(pigeonVar_list[1])
    let code: BiometricError? = nilOrValue(pigeonVar_list[2])
    let authenticationType: AuthenticationType? = nilOrValue(pigeonVar_list[3])

    return SimplePromptResult(
      success: success,
      error: error,
      code: code,
      authenticationType: authenticationType
    )
  }
  func toList() -> [Any?] {
    return [
      success,
      error,
      code,
      authenticationType,
    ]
  }
  static func == (lhs: SimplePromptResult, rhs: SimplePromptResult) -> Bool {
    return deepEqualsBiometricSignatureApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashBiometricSignatureApi(value: toList(), hasher: &hasher)
  }
}

private class BiometricSignatureApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return AuthenticationType(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return BiometricType(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return BiometricStrength(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return BiometricError(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return SignatureType(rawValue: enumResultAsInt)
      }
      return nil
    case 134:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return KeyFormat(rawValue: enumResultAsInt)
      }
      return nil
    case 135:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return SignatureFormat(rawValue: enumResultAsInt)
      }
      return nil
    case 136:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PayloadFormat(rawValue: enumResultAsInt)
      }
      return nil
    case 137:
      return BiometricAvailability.fromList(self.readValue() as! [Any?])
    case 138:
      return KeyCreationResult.fromList(self.readValue() as! [Any?])
    case 139:
      return SignatureResult.fromList(self.readValue() as! [Any?])
    case 140:
      return DecryptResult.fromList(self.readValue() as! [Any?])
    case 141:
      return KeyInfo.fromList(self.readValue() as! [Any?])
    case 142:
      return CreateKeysConfig.fromList(self.readValue() as! [Any?])
    case 143:
      return CreateSignatureConfig.fromList(self.readValue() as! [Any?])
    case 144:
      return DecryptConfig.fromList(self.readValue() as! [Any?])
    case 145:
      return SimplePromptConfig.fromList(self.readValue() as! [Any?])
    case 146:
      return SimplePromptResult.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class BiometricSignatureApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? AuthenticationType {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? BiometricType {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? BiometricStrength {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? BiometricError {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? SignatureType {
      super.writeByte(133)
      super.writeValue(value.rawValue)
    } else if let value = value as? KeyFormat {
      super.writeByte(134)
      super.writeValue(value.rawValue)
    } else if let value = value as? SignatureFormat {
      super.writeByte(135)
      super.writeValue(value.rawValue)
    } else if let value = value as? PayloadFormat {
      super.writeByte(136)
      super.writeValue(value.rawValue)
    } else if let value = value as? BiometricAvailability {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? KeyCreationResult {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? SignatureResult {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? DecryptResult {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? KeyInfo {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else if let value = value as? CreateKeysConfig {
      super.writeByte(142)
      super.writeValue(value.toList())
    } else if let value = value as? CreateSignatureConfig {
      super.writeByte(143)
      super.writeValue(value.toList())
    } else if let value = value as? DecryptConfig {
      super.writeByte(144)
      super.writeValue(value.toList())
    } else if let value = value as? SimplePromptConfig {
      super.writeByte(145)
      super.writeValue(value.toList())
    } else if let value = value as? SimplePromptResult {
      super.writeByte(146)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class BiometricSignatureApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return BiometricSignatureApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return BiometricSignatureApiPigeonCodecWriter(data: data)
  }
}

class BiometricSignatureApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = BiometricSignatureApiPigeonCodec(readerWriter: BiometricSignatureApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol BiometricSignatureApi {
  /// Checks if biometric authentication is available.
  func biometricAuthAvailable(completion: @escaping (Result<BiometricAvailability, Error>) -> Void)
  /// Creates a new key pair.
  ///
  /// [keyAlias] is an optional alias for the key. When null, the default
  /// alias is used. Different aliases create independent key pairs.
  /// [config] contains platform-specific options. See [CreateKeysConfig].
  /// [keyFormat] specifies the output format for the public key.
  /// [promptMessage] is the message shown to the user during authentication.
  func createKeys(keyAlias: String?, config: CreateKeysConfig?, keyFormat: KeyFormat, promptMessage: String?, completion: @escaping (Result<KeyCreationResult, Error>) -> Void)
  /// Creates a signature.
  ///
  /// [payload] is the data to sign.
  /// [keyAlias] specifies which key to sign with. Defaults to the default alias.
  /// [config] contains platform-specific options. See [CreateSignatureConfig].
  /// [signatureFormat] specifies the output format for the signature.
  /// [keyFormat] specifies the output format for the public key.
  /// [promptMessage] is the message shown to the user during authentication.
  func createSignature(payload: String, keyAlias: String?, config: CreateSignatureConfig?, signatureFormat: SignatureFormat, keyFormat: KeyFormat, promptMessage: String?, completion: @escaping (Result<SignatureResult, Error>) -> Void)
  /// Decrypts data.
  ///
  /// Note: Not supported on Windows.
  /// [payload] is the encrypted data.
  /// [keyAlias] specifies which key to decrypt with. Defaults to the default alias.
  /// [payloadFormat] specifies the format of the encrypted data.
  /// [config] contains platform-specific options. See [DecryptConfig].
  /// [promptMessage] is the message shown to the user during authentication.
  func decrypt(payload: String, keyAlias: String?, payloadFormat: PayloadFormat, config: DecryptConfig?, promptMessage: String?, completion: @escaping (Result<DecryptResult, Error>) -> Void)
  /// Deletes keys for a specific alias.
  ///
  /// [keyAlias] specifies which key to delete. When null, deletes the
  /// default alias only. Other aliases are not affected.
  func deleteKeys(keyAlias: String?, completion: @escaping (Result<Bool, Error>) -> Void)
  /// Deletes all biometric keys across all aliases.
  ///
  /// This is a destructive operation that removes every key managed by
  /// this plugin. Use [deleteKeys] for targeted deletion.
  func deleteAllKeys(completion: @escaping (Result<Bool, Error>) -> Void)
  /// Gets detailed information about existing biometric keys.
  ///
  /// [keyAlias] specifies which key to query. Defaults to the default alias.
  /// Returns key metadata including algorithm, size, validity, and public keys.
  func getKeyInfo(keyAlias: String?, checkValidity: Bool, keyFormat: KeyFormat, completion: @escaping (Result<KeyInfo, Error>) -> Void)
  /// Performs simple biometric authentication without cryptographic operations.
  ///
  /// This is useful for:
  /// - Quick re-authentication flows
  /// - Confirming user presence before sensitive operations
  /// - Simple access control without key management
  ///
  /// [promptMessage] is the main message shown to the user (title on Android).
  /// [config] contains optional platform-specific configuration.
  ///
  /// Returns a [SimplePromptResult] indicating success or failure.
  func simplePrompt(promptMessage: String, config: SimplePromptConfig?, completion: @escaping (Result<SimplePromptResult, Error>) -> Void)
  /// Checks whether the device has a screen lock (PIN, pattern, password, or
  /// passcode) configured.
  ///
  /// This is a precondition for biometric enrollment on most platforms, but
  /// the precise meaning of `true` varies per platform:
  ///
  /// - **Android**: Authoritative. Uses `KeyguardManager.isDeviceSecure()`
  ///   and reports exactly whether a lock credential is enrolled.
  /// - **iOS/macOS**: Evaluates `LAPolicy.deviceOwnerAuthentication` and
  ///   maps `kLAErrorPasscodeNotSet` to `false`. Any other failure to
  ///   evaluate the policy (e.g. on unusual or very old devices) is treated
  ///   as `true` to avoid false negatives. Therefore `true` means
  ///   "lock is set **or** indeterminate". If you need a stronger guarantee,
  ///   rely on the reactive [BiometricError.passcodeNotSet] surfaced during
  ///   the next operation.
  /// - **Windows**: Reports **Windows Hello availability**, not generic
  ///   screen-lock state. Uses
  ///   `KeyCredentialManager.IsSupportedAsync()`, which requires a Windows
  ///   Hello PIN to be provisioned. Password-only local accounts will get
  ///   `false` here even though a screen lock is set. Treat the Windows
  ///   return value as "can this device use Windows Hello for biometric
  ///   operations?" rather than a direct equivalent of the Android check.
  ///
  /// Returns `true` if the device has a screen lock configured (or the
  /// platform-specific equivalent described above).
  func isDeviceLockSet(completion: @escaping (Result<Bool, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class BiometricSignatureApiSetup {
  static var codec: FlutterStandardMessageCodec { BiometricSignatureApiPigeonCodec.shared }
  /// Sets up an instance of `BiometricSignatureApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: BiometricSignatureApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Checks if biometric authentication is available.
    let biometricAuthAvailableChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.biometricAuthAvailable\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      biometricAuthAvailableChannel.setMessageHandler { _, reply in
        api.biometricAuthAvailable { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      biometricAuthAvailableChannel.setMessageHandler(nil)
    }
    /// Creates a new key pair.
    ///
    /// [keyAlias] is an optional alias for the key. When null, the default
    /// alias is used. Different aliases create independent key pairs.
    /// [config] contains platform-specific options. See [CreateKeysConfig].
    /// [keyFormat] specifies the output format for the public key.
    /// [promptMessage] is the message shown to the user during authentication.
    let createKeysChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.createKeys\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createKeysChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyAliasArg: String? = nilOrValue(args[0])
        let configArg: CreateKeysConfig? = nilOrValue(args[1])
        let keyFormatArg = args[2] as! KeyFormat
        let promptMessageArg: String? = nilOrValue(args[3])
        api.createKeys(keyAlias: keyAliasArg, config: configArg, keyFormat: keyFormatArg, promptMessage: promptMessageArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      createKeysChannel.setMessageHandler(nil)
    }
    /// Creates a signature.
    ///
    /// [payload] is the data to sign.
    /// [keyAlias] specifies which key to sign with. Defaults to the default alias.
    /// [config] contains platform-specific options. See [CreateSignatureConfig].
    /// [signatureFormat] specifies the output format for the signature.
    /// [keyFormat] specifies the output format for the public key.
    /// [promptMessage] is the message shown to the user during authentication.
    let createSignatureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.createSignature\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createSignatureChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let payloadArg = args[0] as! String
        let keyAliasArg: String? = nilOrValue(args[1])
        let configArg: CreateSignatureConfig? = nilOrValue(args[2])
        let signatureFormatArg = args[3] as! SignatureFormat
        let keyFormatArg = args[4] as! KeyFormat
        let promptMessageArg: String? = nilOrValue(args[5])
        api.createSignature(payload: payloadArg, keyAlias: keyAliasArg, config: configArg, signatureFormat: signatureFormatArg, keyFormat: keyFormatArg, promptMessage: promptMessageArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      createSignatureChannel.setMessageHandler(nil)
    }
    /// Decrypts data.
    ///
    /// Note: Not supported on Windows.
    /// [payload] is the encrypted data.
    /// [keyAlias] specifies which key to decrypt with. Defaults to the default alias.
    /// [payloadFormat] specifies the format of the encrypted data.
    /// [config] contains platform-specific options. See [DecryptConfig].
    /// [promptMessage] is the message shown to the user during authentication.
    let decryptChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.decrypt\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      decryptChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let payloadArg = args[0] as! String
        let keyAliasArg: String? = nilOrValue(args[1])
        let payloadFormatArg = args[2] as! PayloadFormat
        let configArg: DecryptConfig? = nilOrValue(args[3])
        let promptMessageArg: String? = nilOrValue(args[4])
        api.decrypt(payload: payloadArg, keyAlias: keyAliasArg, payloadFormat: payloadFormatArg, config: configArg, promptMessage: promptMessageArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      decryptChannel.setMessageHandler(nil)
    }
    /// Deletes keys for a specific alias.
    ///
    /// [keyAlias] specifies which key to delete. When null, deletes the
    /// default alias only. Other aliases are not affected.
    let deleteKeysChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.deleteKeys\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      deleteKeysChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyAliasArg: String? = nilOrValue(args[0])
        api.deleteKeys(keyAlias: keyAliasArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      deleteKeysChannel.setMessageHandler(nil)
    }
    /// Deletes all biometric keys across all aliases.
    ///
    /// This is a destructive operation that removes every key managed by
    /// this plugin. Use [deleteKeys] for targeted deletion.
    let deleteAllKeysChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.deleteAllKeys\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      deleteAllKeysChannel.setMessageHandler { _, reply in
        api.deleteAllKeys { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      deleteAllKeysChannel.setMessageHandler(nil)
    }
    /// Gets detailed information about existing biometric keys.
    ///
    /// [keyAlias] specifies which key to query. Defaults to the default alias.
    /// Returns key metadata including algorithm, size, validity, and public keys.
    let getKeyInfoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.getKeyInfo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getKeyInfoChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyAliasArg: String? = nilOrValue(args[0])
        let checkValidityArg = args[1] as! Bool
        let keyFormatArg = args[2] as! KeyFormat
        api.getKeyInfo(keyAlias: keyAliasArg, checkValidity: checkValidityArg, keyFormat: keyFormatArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getKeyInfoChannel.setMessageHandler(nil)
    }
    /// Performs simple biometric authentication without cryptographic operations.
    ///
    /// This is useful for:
    /// - Quick re-authentication flows
    /// - Confirming user presence before sensitive operations
    /// - Simple access control without key management
    ///
    /// [promptMessage] is the main message shown to the user (title on Android).
    /// [config] contains optional platform-specific configuration.
    ///
    /// Returns a [SimplePromptResult] indicating success or failure.
    let simplePromptChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.simplePrompt\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      simplePromptChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let promptMessageArg = args[0] as! String
        let configArg: SimplePromptConfig? = nilOrValue(args[1])
        api.simplePrompt(promptMessage: promptMessageArg, config: configArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      simplePromptChannel.setMessageHandler(nil)
    }
    /// Checks whether the device has a screen lock (PIN, pattern, password, or
    /// passcode) configured.
    ///
    /// This is a precondition for biometric enrollment on most platforms, but
    /// the precise meaning of `true` varies per platform:
    ///
    /// - **Android**: Authoritative. Uses `KeyguardManager.isDeviceSecure()`
    ///   and reports exactly whether a lock credential is enrolled.
    /// - **iOS/macOS**: Evaluates `LAPolicy.deviceOwnerAuthentication` and
    ///   maps `kLAErrorPasscodeNotSet` to `false`. Any other failure to
    ///   evaluate the policy (e.g. on unusual or very old devices) is treated
    ///   as `true` to avoid false negatives. Therefore `true` means
    ///   "lock is set **or** indeterminate". If you need a stronger guarantee,
    ///   rely on the reactive [BiometricError.passcodeNotSet] surfaced during
    ///   the next operation.
    /// - **Windows**: Reports **Windows Hello availability**, not generic
    ///   screen-lock state. Uses
    ///   `KeyCredentialManager.IsSupportedAsync()`, which requires a Windows
    ///   Hello PIN to be provisioned. Password-only local accounts will get
    ///   `false` here even though a screen lock is set. Treat the Windows
    ///   return value as "can this device use Windows Hello for biometric
    ///   operations?" rather than a direct equivalent of the Android check.
    ///
    /// Returns `true` if the device has a screen lock configured (or the
    /// platform-specific equivalent described above).
    let isDeviceLockSetChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.isDeviceLockSet\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isDeviceLockSetChannel.setMessageHandler { _, reply in
        api.isDeviceLockSet { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      isDeviceLockSetChannel.setMessageHandler(nil)
    }
  }
}
